// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_oauth

import (
	"database/sql"

	"github.com/leodip/goiabada/core/models"
	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewCodeIssuer creates a new instance of CodeIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeIssuer {
	mock := &CodeIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CodeIssuer is an autogenerated mock type for the CodeIssuer type
type CodeIssuer struct {
	mock.Mock
}

type CodeIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeIssuer) EXPECT() *CodeIssuer_Expecter {
	return &CodeIssuer_Expecter{mock: &_m.Mock}
}

// CreateAuthCode provides a mock function for the type CodeIssuer
func (_mock *CodeIssuer) CreateAuthCode(tx *sql.Tx, input *oauth.CreateCodeInput) (*models.Code, error) {
	ret := _mock.Called(tx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthCode")
	}

	var r0 *models.Code
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*sql.Tx, *oauth.CreateCodeInput) (*models.Code, error)); ok {
		return returnFunc(tx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(*sql.Tx, *oauth.CreateCodeInput) *models.Code); ok {
		r0 = returnFunc(tx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Code)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*sql.Tx, *oauth.CreateCodeInput) error); ok {
		r1 = returnFunc(tx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CodeIssuer_CreateAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthCode'
type CodeIssuer_CreateAuthCode_Call struct {
	*mock.Call
}

// CreateAuthCode is a helper method to define mock.On call
//   - tx *sql.Tx
//   - input *oauth.CreateCodeInput
func (_e *CodeIssuer_Expecter) CreateAuthCode(tx any, input any) *CodeIssuer_CreateAuthCode_Call {
	return &CodeIssuer_CreateAuthCode_Call{Call: _e.mock.On("CreateAuthCode", tx, input)}
}

func (_c *CodeIssuer_CreateAuthCode_Call) Run(run func(tx *sql.Tx, input *oauth.CreateCodeInput)) *CodeIssuer_CreateAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sql.Tx
		if args[0] != nil {
			arg0 = args[0].(*sql.Tx)
		}
		var arg1 *oauth.CreateCodeInput
		if args[1] != nil {
			arg1 = args[1].(*oauth.CreateCodeInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeIssuer_CreateAuthCode_Call) Return(code *models.Code, err error) *CodeIssuer_CreateAuthCode_Call {
	_c.Call.Return(code, err)
	return _c
}

func (_c *CodeIssuer_CreateAuthCode_Call) RunAndReturn(run func(tx *sql.Tx, input *oauth.CreateCodeInput) (*models.Code, error)) *CodeIssuer_CreateAuthCode_Call {
	_c.Call.Return(run)
	return _c
}
