//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_oauth

import (
	"crypto/rsa"

	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenParser creates a new instance of TokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParser {
	mock := &TokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenParser is an autogenerated mock type for the TokenParser type
type TokenParser struct {
	mock.Mock
}

type TokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenParser) EXPECT() *TokenParser_Expecter {
	return &TokenParser_Expecter{mock: &_m.Mock}
}

// DecodeAndValidateTokenResponse provides a mock function for the type TokenParser
func (_mock *TokenParser) DecodeAndValidateTokenResponse(tokenResponse *oauth.TokenResponse) (*oauth.JwtInfo, error) {
	ret := _mock.Called(tokenResponse)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateTokenResponse")
	}

	var r0 *oauth.JwtInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*oauth.TokenResponse) (*oauth.JwtInfo, error)); ok {
		return returnFunc(tokenResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(*oauth.TokenResponse) *oauth.JwtInfo); ok {
		r0 = returnFunc(tokenResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*oauth.TokenResponse) error); ok {
		r1 = returnFunc(tokenResponse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenParser_DecodeAndValidateTokenResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeAndValidateTokenResponse'
type TokenParser_DecodeAndValidateTokenResponse_Call struct {
	*mock.Call
}

// DecodeAndValidateTokenResponse is a helper method to define mock.On call
//   - tokenResponse *oauth.TokenResponse
func (_e *TokenParser_Expecter) DecodeAndValidateTokenResponse(tokenResponse interface{}) *TokenParser_DecodeAndValidateTokenResponse_Call {
	return &TokenParser_DecodeAndValidateTokenResponse_Call{Call: _e.mock.On("DecodeAndValidateTokenResponse", tokenResponse)}
}

func (_c *TokenParser_DecodeAndValidateTokenResponse_Call) Run(run func(tokenResponse *oauth.TokenResponse)) *TokenParser_DecodeAndValidateTokenResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *oauth.TokenResponse
		if args[0] != nil {
			arg0 = args[0].(*oauth.TokenResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenResponse_Call) Return(jwtInfo *oauth.JwtInfo, err error) *TokenParser_DecodeAndValidateTokenResponse_Call {
	_c.Call.Return(jwtInfo, err)
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenResponse_Call) RunAndReturn(run func(tokenResponse *oauth.TokenResponse) (*oauth.JwtInfo, error)) *TokenParser_DecodeAndValidateTokenResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeAndValidateTokenString provides a mock function for the type TokenParser
func (_mock *TokenParser) DecodeAndValidateTokenString(token string, pubKey *rsa.PublicKey, withExpirationCheck bool) (*oauth.JwtToken, error) {
	ret := _mock.Called(token, pubKey, withExpirationCheck)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateTokenString")
	}

	var r0 *oauth.JwtToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PublicKey, bool) (*oauth.JwtToken, error)); ok {
		return returnFunc(token, pubKey, withExpirationCheck)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PublicKey, bool) *oauth.JwtToken); ok {
		r0 = returnFunc(token, pubKey, withExpirationCheck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *rsa.PublicKey, bool) error); ok {
		r1 = returnFunc(token, pubKey, withExpirationCheck)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenParser_DecodeAndValidateTokenString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeAndValidateTokenString'
type TokenParser_DecodeAndValidateTokenString_Call struct {
	*mock.Call
}

// DecodeAndValidateTokenString is a helper method to define mock.On call
//   - token string
//   - pubKey *rsa.PublicKey
//   - withExpirationCheck bool
func (_e *TokenParser_Expecter) DecodeAndValidateTokenString(token interface{}, pubKey interface{}, withExpirationCheck interface{}) *TokenParser_DecodeAndValidateTokenString_Call {
	return &TokenParser_DecodeAndValidateTokenString_Call{Call: _e.mock.On("DecodeAndValidateTokenString", token, pubKey, withExpirationCheck)}
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) Run(run func(token string, pubKey *rsa.PublicKey, withExpirationCheck bool)) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *rsa.PublicKey
		if args[1] != nil {
			arg1 = args[1].(*rsa.PublicKey)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) Return(jwtToken *oauth.JwtToken, err error) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Return(jwtToken, err)
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) RunAndReturn(run func(token string, pubKey *rsa.PublicKey, withExpirationCheck bool) (*oauth.JwtToken, error)) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Return(run)
	return _c
}
