//go:build !production

// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks_oauth

import (
	oauth "github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// TokenParser is an autogenerated mock type for the TokenParser type
type TokenParser struct {
	mock.Mock
}

// DecodeAndValidateTokenResponse provides a mock function with given fields: tokenResponse
func (_m *TokenParser) DecodeAndValidateTokenResponse(tokenResponse *oauth.TokenResponse) (*oauth.JwtInfo, error) {
	ret := _m.Called(tokenResponse)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateTokenResponse")
	}

	var r0 *oauth.JwtInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(*oauth.TokenResponse) (*oauth.JwtInfo, error)); ok {
		return rf(tokenResponse)
	}
	if rf, ok := ret.Get(0).(func(*oauth.TokenResponse) *oauth.JwtInfo); ok {
		r0 = rf(tokenResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(*oauth.TokenResponse) error); ok {
		r1 = rf(tokenResponse)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecodeAndValidateTokenString provides a mock function with given fields: token, pubKey, withExpirationCheck
func (_m *TokenParser) DecodeAndValidateTokenString(token string, pubKey *rsa.PublicKey, withExpirationCheck bool) (*oauth.JwtToken, error) {
	ret := _m.Called(token, pubKey, withExpirationCheck)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateTokenString")
	}

	var r0 *oauth.JwtToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *rsa.PublicKey, bool) (*oauth.JwtToken, error)); ok {
		return rf(token, pubKey, withExpirationCheck)
	}
	if rf, ok := ret.Get(0).(func(string, *rsa.PublicKey, bool) *oauth.JwtToken); ok {
		r0 = rf(token, pubKey, withExpirationCheck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *rsa.PublicKey, bool) error); ok {
		r1 = rf(token, pubKey, withExpirationCheck)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenParser creates a new instance of TokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParser {
	mock := &TokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
