//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_oauth

import (
	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenExchanger creates a new instance of TokenExchanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenExchanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenExchanger {
	mock := &TokenExchanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenExchanger is an autogenerated mock type for the TokenExchanger type
type TokenExchanger struct {
	mock.Mock
}

type TokenExchanger_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenExchanger) EXPECT() *TokenExchanger_Expecter {
	return &TokenExchanger_Expecter{mock: &_m.Mock}
}

// ExchangeCodeForTokens provides a mock function for the type TokenExchanger
func (_mock *TokenExchanger) ExchangeCodeForTokens(code string, redirectURI string, clientId string, clientSecret string, codeVerifier string, tokenEndpoint string) (*oauth.TokenResponse, error) {
	ret := _mock.Called(code, redirectURI, clientId, clientSecret, codeVerifier, tokenEndpoint)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForTokens")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, string) (*oauth.TokenResponse, error)); ok {
		return returnFunc(code, redirectURI, clientId, clientSecret, codeVerifier, tokenEndpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, string) *oauth.TokenResponse); ok {
		r0 = returnFunc(code, redirectURI, clientId, clientSecret, codeVerifier, tokenEndpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string, string) error); ok {
		r1 = returnFunc(code, redirectURI, clientId, clientSecret, codeVerifier, tokenEndpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenExchanger_ExchangeCodeForTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForTokens'
type TokenExchanger_ExchangeCodeForTokens_Call struct {
	*mock.Call
}

// ExchangeCodeForTokens is a helper method to define mock.On call
//   - code string
//   - redirectURI string
//   - clientId string
//   - clientSecret string
//   - codeVerifier string
//   - tokenEndpoint string
func (_e *TokenExchanger_Expecter) ExchangeCodeForTokens(code interface{}, redirectURI interface{}, clientId interface{}, clientSecret interface{}, codeVerifier interface{}, tokenEndpoint interface{}) *TokenExchanger_ExchangeCodeForTokens_Call {
	return &TokenExchanger_ExchangeCodeForTokens_Call{Call: _e.mock.On("ExchangeCodeForTokens", code, redirectURI, clientId, clientSecret, codeVerifier, tokenEndpoint)}
}

func (_c *TokenExchanger_ExchangeCodeForTokens_Call) Run(run func(code string, redirectURI string, clientId string, clientSecret string, codeVerifier string, tokenEndpoint string)) *TokenExchanger_ExchangeCodeForTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *TokenExchanger_ExchangeCodeForTokens_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenExchanger_ExchangeCodeForTokens_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenExchanger_ExchangeCodeForTokens_Call) RunAndReturn(run func(code string, redirectURI string, clientId string, clientSecret string, codeVerifier string, tokenEndpoint string) (*oauth.TokenResponse, error)) *TokenExchanger_ExchangeCodeForTokens_Call {
	_c.Call.Return(run)
	return _c
}
