//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_tcputils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTCPConnectionTester creates a new instance of TCPConnectionTester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTCPConnectionTester(t interface {
	mock.TestingT
	Cleanup(func())
}) *TCPConnectionTester {
	mock := &TCPConnectionTester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TCPConnectionTester is an autogenerated mock type for the TCPConnectionTester type
type TCPConnectionTester struct {
	mock.Mock
}

type TCPConnectionTester_Expecter struct {
	mock *mock.Mock
}

func (_m *TCPConnectionTester) EXPECT() *TCPConnectionTester_Expecter {
	return &TCPConnectionTester_Expecter{mock: &_m.Mock}
}

// TestTCPConnection provides a mock function for the type TCPConnectionTester
func (_mock *TCPConnectionTester) TestTCPConnection(host string, port int) error {
	ret := _mock.Called(host, port)

	if len(ret) == 0 {
		panic("no return value specified for TestTCPConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(host, port)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TCPConnectionTester_TestTCPConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestTCPConnection'
type TCPConnectionTester_TestTCPConnection_Call struct {
	*mock.Call
}

// TestTCPConnection is a helper method to define mock.On call
//   - host string
//   - port int
func (_e *TCPConnectionTester_Expecter) TestTCPConnection(host interface{}, port interface{}) *TCPConnectionTester_TestTCPConnection_Call {
	return &TCPConnectionTester_TestTCPConnection_Call{Call: _e.mock.On("TestTCPConnection", host, port)}
}

func (_c *TCPConnectionTester_TestTCPConnection_Call) Run(run func(host string, port int)) *TCPConnectionTester_TestTCPConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TCPConnectionTester_TestTCPConnection_Call) Return(err error) *TCPConnectionTester_TestTCPConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TCPConnectionTester_TestTCPConnection_Call) RunAndReturn(run func(host string, port int) error) *TCPConnectionTester_TestTCPConnection_Call {
	_c.Call.Return(run)
	return _c
}
