// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package accounthandlersmocks

import (
	"context"
	"database/sql"

	"github.com/leodip/goiabada/authserver/internal/record"
	"github.com/leodip/goiabada/authserver/internal/usercreation"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionalUserCreator creates a new instance of TransactionalUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionalUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionalUserCreator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TransactionalUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TransactionalUserCreator is an autogenerated mock type for the TransactionalUserCreator type
type TransactionalUserCreator struct {
	mock.Mock
}

type TransactionalUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionalUserCreator) EXPECT() *TransactionalUserCreator_Expecter {
	return &TransactionalUserCreator_Expecter{mock: &_m.Mock}
}

// CreateUserInTransaction provides a mock function for the type TransactionalUserCreator
func (_mock *TransactionalUserCreator) CreateUserInTransaction(ctx context.Context, tx *sql.Tx, input *usercreation.Input) (*record.User, error) {
	ret := _mock.Called(ctx, tx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserInTransaction")
	}

	var r0 *record.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, *usercreation.Input) (*record.User, error)); ok {
		return returnFunc(ctx, tx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, *usercreation.Input) *record.User); ok {
		r0 = returnFunc(ctx, tx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, *usercreation.Input) error); ok {
		r1 = returnFunc(ctx, tx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionalUserCreator_CreateUserInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserInTransaction'
type TransactionalUserCreator_CreateUserInTransaction_Call struct {
	*mock.Call
}

// CreateUserInTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - input *usercreation.Input
func (_e *TransactionalUserCreator_Expecter) CreateUserInTransaction(ctx any, tx any, input any) *TransactionalUserCreator_CreateUserInTransaction_Call {
	return &TransactionalUserCreator_CreateUserInTransaction_Call{Call: _e.mock.On("CreateUserInTransaction", ctx, tx, input)}
}

func (_c *TransactionalUserCreator_CreateUserInTransaction_Call) Run(run func(ctx context.Context, tx *sql.Tx, input *usercreation.Input)) *TransactionalUserCreator_CreateUserInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 *usercreation.Input
		if args[2] != nil {
			arg2 = args[2].(*usercreation.Input)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionalUserCreator_CreateUserInTransaction_Call) Return(user *record.User, err error) *TransactionalUserCreator_CreateUserInTransaction_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *TransactionalUserCreator_CreateUserInTransaction_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, input *usercreation.Input) (*record.User, error)) *TransactionalUserCreator_CreateUserInTransaction_Call {
	_c.Call.Return(run)
	return _c
}
