// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package accounthandlersmocks

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/record"
	"github.com/leodip/goiabada/authserver/internal/usercreation"
	mock "github.com/stretchr/testify/mock"
)

// NewUserCreator creates a new instance of UserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &UserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// UserCreator is an autogenerated mock type for the UserCreator type
type UserCreator struct {
	mock.Mock
}

type UserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCreator) EXPECT() *UserCreator_Expecter {
	return &UserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserCreator
func (_mock *UserCreator) CreateUser(ctx context.Context, input *usercreation.Input) (*record.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *record.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *usercreation.Input) (*record.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *usercreation.Input) *record.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *usercreation.Input) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input *usercreation.Input
func (_e *UserCreator_Expecter) CreateUser(ctx any, input any) *UserCreator_CreateUser_Call {
	return &UserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, input)}
}

func (_c *UserCreator_CreateUser_Call) Run(run func(ctx context.Context, input *usercreation.Input)) *UserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *usercreation.Input
		if args[1] != nil {
			arg1 = args[1].(*usercreation.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserCreator_CreateUser_Call) Return(user *record.User, err error) *UserCreator_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserCreator_CreateUser_Call) RunAndReturn(run func(ctx context.Context, input *usercreation.Input) (*record.User, error)) *UserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}
