services:

  mailhog:
    image: mailhog/mailhog       
    networks: 
      - goiabada-network


  mysql-server:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data-tests:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySqlPass123
    healthcheck:      
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-pmySqlPass123",  "--protocol", "tcp"]
      interval: 1s
      timeout: 2s
      retries: 20
    networks: 
      - goiabada-network


  goiabada-test:
    container_name: goiabada-test
    user: root
    build:
      context: ..
      dockerfile: docker/Dockerfile-test
    restart: unless-stopped
    tty: true
    depends_on:
      mysql-server:
        condition: service_healthy    
      mailhog:
        condition: service_started     
    command: sleep infinity
    healthcheck:      
      test: "curl --silent --fail http://localhost:8080/health > /dev/null || exit 1"
      interval: 1s
      timeout: 2s
      retries: 20
    networks: 
      - goiabada-network    
    environment:
      - TEST_COMMAND=test-sqlite
      - TZ=Europe/Lisbon 
      - GOIABADA_AUTHSERVER_ADMIN_EMAIL=admin@example.com
      - GOIABADA_AUTHSERVER_ADMIN_PASSWORD=changeme
      - GOIABADA_AUTHSERVER_APPNAME=Goiabada      
      - GOIABADA_AUTHSERVER_BASEURL=http://localhost:8080
      - GOIABADA_AUTHSERVER_HOST=0.0.0.0
      - GOIABADA_AUTHSERVER_PORT=8080
      - GOIABADA_AUTHSERVER_CERTFILE=
      - GOIABADA_AUTHSERVER_KEYFILE=
      - GOIABADA_AUTHSERVER_ISBEHINDAREVERSEPROXY=false
      - GOIABADA_AUTHSERVER_RATELIMITER_ENABLED=false
      - GOIABADA_AUTHSERVER_RATELIMITER_MAXREQUESTS=50
      - GOIABADA_AUTHSERVER_RATELIMITER_WINDOWSIZEINSECONDS=10
      - GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=false
      - GOIABADA_AUTHSERVER_LOG_SQL=false
      - GOIABADA_AUTHSERVER_AUDIT_LOGS_IN_CONSOLE=false
      - GOIABADA_AUTHSERVER_STATICDIR=
      - GOIABADA_AUTHSERVER_TEMPLATEDIR=
      - GOIABADA_ADMINCONSOLE_BASEURL=http://localhost:8081
      - GOIABADA_ADMINCONSOLE_HOST=0.0.0.0
      - GOIABADA_ADMINCONSOLE_PORT=8081
      - GOIABADA_ADMINCONSOLE_CERTFILE=
      - GOIABADA_ADMINCONSOLE_KEYFILE=
      - GOIABADA_ADMINCONSOLE_ISBEHINDAREVERSEPROXY=false
      - GOIABADA_ADMINCONSOLE_RATELIMITER_ENABLED=false
      - GOIABADA_ADMINCONSOLE_RATELIMITER_MAXREQUESTS=50
      - GOIABADA_ADMINCONSOLE_RATELIMITER_WINDOWSIZEINSECONDS=10
      - GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=false
      - GOIABADA_ADMINCONSOLE_LOG_SQL=false
      - GOIABADA_ADMINCONSOLE_AUDIT_LOGS_IN_CONSOLE=false
      - GOIABADA_ADMINCONSOLE_STATICDIR=
      - GOIABADA_ADMINCONSOLE_TEMPLATEDIR=
      - GOIABADA_DB_TYPE=mysql
      - GOIABADA_DB_USERNAME=root
      - GOIABADA_DB_PASSWORD=mySqlPass123
      - GOIABADA_DB_HOST=mysql-server
      - GOIABADA_DB_PORT=3306
      - GOIABADA_DB_NAME=goiabada
      - GOIABADA_DB_DSN=file:/tmp/goiabada.db


volumes:
  mysql-data-tests:  

networks:
  goiabada-network:
