FROM golang:1.23.0-alpine AS build

RUN apk add --no-cache tzdata alpine-conf curl bash make
RUN /sbin/setup-timezone -z Europe/Lisbon

WORKDIR /app

# Tailwind CLI tool
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.10/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

COPY .. .

WORKDIR /app/core

RUN pwd
RUN ls -la
RUN go mod download

WORKDIR /app/authserver

RUN pwd
RUN ls -la
RUN go mod download

ENTRYPOINT ["/bin/bash", "-c", "make test-ci"]
