FROM golang:1.23.0-alpine AS buildStage

RUN apk add --no-cache tzdata alpine-conf curl bash make
RUN /sbin/setup-timezone -z Europe/Lisbon

WORKDIR /app/src

# Tailwind CLI tool
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.10/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

COPY ./authserver/go.mod ./authserver
COPY ./core/go.mod ./core

RUN go mod download

COPY ./authserver ./authserver
COPY ./core ./core

ENTRYPOINT ["/bin/bash", "-c" , "make test-ci"]