version: '3.8'
services:

  mysql-server:
    image: mysql:latest
    restart: unless-stopped    
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySqlPass123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-pmySqlPass123",  "--protocol", "tcp"]
      interval: 1s
      timeout: 2s
      retries: 20
    networks: 
      - goiabada-network

  goiabada-authserver:
    image: leodip/goiabada:authserver-latest
    restart: unless-stopped
    depends_on: 
      mysql-server:
        condition: service_healthy    
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/live/demo-authserver.example.com/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/demo-authserver.example.com/privkey.pem:/certs/privkey.pem:ro
    networks: 
      - goiabada-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://goiabada-authserver:9090/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - TZ=Europe/Lisbon 
      - GOIABADA_ADMIN_EMAIL=admin@example.com
      - GOIABADA_ADMIN_PASSWORD=changeme
      - GOIABADA_APPNAME=Goiabada

      # External HTTPS access
      - GOIABADA_AUTHSERVER_BASEURL=https://demo-authserver.example.com:8443
      - GOIABADA_AUTHSERVER_INTERNALBASEURL=http://goiabada-authserver:9090
      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTPS=0.0.0.0
      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTPS=8443
      - GOIABADA_AUTHSERVER_CERTFILE=/certs/fullchain.pem
      - GOIABADA_AUTHSERVER_KEYFILE=/certs/privkey.pem
      
      # Internal HTTP access (restricted to container name)
      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTP=goiabada-authserver
      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTP=9090
      
      - GOIABADA_AUTHSERVER_TRUST_PROXY_HEADERS=false
      - GOIABADA_AUTHSERVER_SET_COOKIE_SECURE=true
      - GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=true
      - GOIABADA_AUTHSERVER_LOG_SQL=false
      - GOIABADA_AUTHSERVER_AUDIT_LOGS_IN_CONSOLE=true
      - GOIABADA_AUTHSERVER_STATICDIR=
      - GOIABADA_AUTHSERVER_TEMPLATEDIR=

      # Database configuration
      - GOIABADA_DB_TYPE=mysql
      - GOIABADA_DB_USERNAME=root
      - GOIABADA_DB_PASSWORD=mySqlPass123
      - GOIABADA_DB_HOST=mysql-server
      - GOIABADA_DB_PORT=3306
      - GOIABADA_DB_NAME=goiabada

      # Admin console URLs
      - GOIABADA_ADMINCONSOLE_BASEURL=https://demo-adminconsole.example.com:8444
      - GOIABADA_ADMINCONSOLE_INTERNALBASEURL=http://goiabada-adminconsole:9091

  goiabada-adminconsole:
    image: leodip/goiabada:adminconsole-latest
    restart: unless-stopped
    depends_on: 
      goiabada-authserver:
        condition: service_healthy
    ports:
      - "8444:8444"
    volumes:
      - /etc/letsencrypt/live/demo-adminconsole.example.com/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/demo-adminconsole.example.com/privkey.pem:/certs/privkey.pem:ro
    networks: 
      - goiabada-network
    environment:
      - TZ=Europe/Lisbon     

      # External HTTPS access
      - GOIABADA_ADMINCONSOLE_BASEURL=https://demo-adminconsole.example.com:8444
      - GOIABADA_ADMINCONSOLE_INTERNALBASEURL=http://goiabada-adminconsole:9091
      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTPS=0.0.0.0
      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTPS=8444
      - GOIABADA_ADMINCONSOLE_CERTFILE=/certs/fullchain.pem
      - GOIABADA_ADMINCONSOLE_KEYFILE=/certs/privkey.pem
      
      # Internal HTTP access (restricted to container name)
      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTP=goiabada-adminconsole
      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTP=9091
      
      - GOIABADA_ADMINCONSOLE_TRUST_PROXY_HEADERS=false
      - GOIABADA_ADMINCONSOLE_SET_COOKIE_SECURE=true
      - GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=true
      - GOIABADA_ADMINCONSOLE_LOG_SQL=false
      - GOIABADA_ADMINCONSOLE_AUDIT_LOGS_IN_CONSOLE=true
      - GOIABADA_ADMINCONSOLE_STATICDIR=
      - GOIABADA_ADMINCONSOLE_TEMPLATEDIR=

      # Database configuration
      - GOIABADA_DB_TYPE=mysql
      - GOIABADA_DB_USERNAME=root
      - GOIABADA_DB_PASSWORD=mySqlPass123
      - GOIABADA_DB_HOST=mysql-server
      - GOIABADA_DB_PORT=3306
      - GOIABADA_DB_NAME=goiabada

      # Auth server URLs
      - GOIABADA_AUTHSERVER_BASEURL=https://demo-authserver.example.com:8443
      - GOIABADA_AUTHSERVER_INTERNALBASEURL=http://goiabada-authserver:9090

volumes:
  mysql-data:

networks:
  goiabada-network:
