version: '3.8'
services:

  mysql-server:
    image: mysql:latest
    restart: unless-stopped    
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySqlPass123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-pmySqlPass123",  "--protocol", "tcp"]
      interval: 1s
      timeout: 2s
      retries: 20
    networks: 
      - goiabada-network  


  goiabada-authserver:
    image: leodip/goiabada-authserver:latest
    restart: unless-stopped
    depends_on: 
      mysql-server:
        condition: service_healthy    
    ports:
      # host_port:container_port
      - 8080:8080 # authserver          
    networks: 
      - goiabada-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      # See all timezones:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Lisbon 

      # The email address of the admin user (the first user created)
      - GOIABADA_AUTHSERVER_ADMIN_EMAIL=admin@example.com

      # The password of the admin user (the first user created)
      - GOIABADA_AUTHSERVER_ADMIN_PASSWORD=changeme

      # The name of your application or organization
      - GOIABADA_AUTHSERVER_APPNAME=Goiabada

      # Without TLS (http) - do not use in production!
      - GOIABADA_AUTHSERVER_BASEURL=http://localhost:8080
      - GOIABADA_AUTHSERVER_HOST=0.0.0.0
      - GOIABADA_AUTHSERVER_PORT=8080
      - GOIABADA_AUTHSERVER_CERTFILE= # for testing purposes only (non-secure http)
      - GOIABADA_AUTHSERVER_KEYFILE= # for testing purposes only (non-secure http)
      - GOIABADA_AUTHSERVER_ISBEHINDAREVERSEPROXY=false
      - GOIABADA_AUTHSERVER_RATELIMITER_ENABLED=true
      - GOIABADA_AUTHSERVER_RATELIMITER_MAXREQUESTS=50
      - GOIABADA_AUTHSERVER_RATELIMITER_WINDOWSIZEINSECONDS=10
      - GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=true
      - GOIABADA_AUTHSERVER_LOG_SQL=false
      - GOIABADA_AUTHSERVER_AUDIT_LOGS_IN_CONSOLE=true
      - GOIABADA_AUTHSERVER_STATICDIR= #leave this empty to use embedded static files
      - GOIABADA_AUTHSERVER_TEMPLATEDIR= #leave this empty to use embedded templates      

      # Database (mysql) details
      - GOIABADA_DB_TYPE=mysql
      - GOIABADA_DB_USERNAME=root
      - GOIABADA_DB_PASSWORD=mySqlPass123
      - GOIABADA_DB_HOST=mysql-server
      - GOIABADA_DB_PORT=3306
      - GOIABADA_DB_NAME=goiabada

      # The auth server needs to know the base URL of the admin console
      - GOIABADA_ADMINCONSOLE_BASEURL=http://localhost:8081


  goiabada-adminconsole:
    image: leodip/goiabada-adminconsole:latest
    restart: unless-stopped
    depends_on: 
      goiabada-authserver:
        condition: service_healthy
    ports:
      # host_port:container_port
      - 8081:8081 # authserver          
    networks: 
      - goiabada-network
    environment:
      # See all timezones:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Lisbon     

      # Without TLS (http) - do not use in production!
      - GOIABADA_ADMINCONSOLE_BASEURL=http://localhost:8081
      - GOIABADA_ADMINCONSOLE_HOST=0.0.0.0
      - GOIABADA_ADMINCONSOLE_PORT=8081
      - GOIABADA_ADMINCONSOLE_CERTFILE= # for testing purposes only (non-secure http)
      - GOIABADA_ADMINCONSOLE_KEYFILE= # for testing purposes only (non-secure http)
      - GOIABADA_ADMINCONSOLE_ISBEHINDAREVERSEPROXY=false
      - GOIABADA_ADMINCONSOLE_RATELIMITER_ENABLED=true
      - GOIABADA_ADMINCONSOLE_RATELIMITER_MAXREQUESTS=50
      - GOIABADA_ADMINCONSOLE_RATELIMITER_WINDOWSIZEINSECONDS=10
      - GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=true
      - GOIABADA_ADMINCONSOLE_LOG_SQL=false
      - GOIABADA_ADMINCONSOLE_AUDIT_LOGS_IN_CONSOLE=true
      - GOIABADA_ADMINCONSOLE_STATICDIR= #leave this empty to use embedded static files
      - GOIABADA_ADMINCONSOLE_TEMPLATEDIR= #leave this empty to use embedded templates      

      # Database (mysql) details
      - GOIABADA_DB_TYPE=mysql
      - GOIABADA_DB_USERNAME=root
      - GOIABADA_DB_PASSWORD=mySqlPass123
      - GOIABADA_DB_HOST=mysql-server
      - GOIABADA_DB_PORT=3306
      - GOIABADA_DB_NAME=goiabada

      # The admin console needs to know the base URL of the auth server
      - GOIABADA_AUTHSERVER_BASEURL=http://localhost:8080

volumes:
  mysql-data:

networks:
  goiabada-network:
