package testutil

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/leodip/goiabada/core/errs"
)

// AssertGeneratedMocksArePinned holds three things to each other: the mockery version
// versions.yaml pins, the header src/mockery-header.txt carries, and the header every
// committed mock actually begins with. The middle one is inlined verbatim into each
// generated file through template-data.boilerplate-file in the two .mockery.yaml files,
// so a clone can read which generator wrote the tree instead of having to install one
// and run it to find out.
//
// The drift this exists for is not hypothetical. Sixteen committed mocks predated the
// mockery that versions.yaml pins, so generate-mocks.sh was not idempotent against its
// own tree: any change that regenerated mocks for its own reasons collected sixteen
// files of churn belonging to nobody, and the staleness was discovered by whoever
// happened to regenerate rather than by anything that checks. That is #338, and it went
// unnoticed through every bump of the pin because the generated files said nothing about
// the generator.
//
// Why this is worth a test when the Lint job in .github/workflows/check.yml already runs
// the generator and fails on a dirty tree: that step is the complete check and this one is
// not, but this one needs neither mockery nor git. It is three file reads and a walk, so
// every module's unit tier can run it, and the failure it catches -- the pin moved and the
// mocks did not follow -- is the one that actually happened. The alternative is the shape
// AssertGofmted's comment describes: a whole tier green, the work pushed, and CI the first
// thing to notice.
//
// The rule keys on mockery's own "Code generated by ... DO NOT EDIT" marker rather than on
// the *_mock.go filename, which is the chosen leniency and has a live instance either way.
// src/core/mocks/test_fs_mock.go is hand-written scaffolding carrying that name, and
// holding it to a generator's header would demand a lie; core/countries/data_generated.go
// and core/timezones/timezones.go come from generators of their own, which have nothing to
// do with this pin. Naming mockery inside the marker is what separates the two.
//
// Scope is the whole source root, as with every guard here, so the tier that runs first
// reports it. Each module's unit tier calls this.
func AssertGeneratedMocksArePinned(t *testing.T) {
	t.Helper()

	assertGeneratedMocksArePinned(t, SourceRoot(t))
}

// assertGeneratedMocksArePinned is the reporting half, taking the root as a parameter and
// failing through a Reporter so a rule test can drive it against a fixture tree. See
// Reporter in guard.go for why both halves exist.
func assertGeneratedMocksArePinned(r Reporter, root string) {
	r.Helper()

	pin, err := pinnedMockeryVersion(filepath.Join(root, mockeryPinFile))
	if err != nil {
		r.Fatalf("%v", err)
	}

	header, err := os.ReadFile(filepath.Join(root, mockeryHeaderFile))
	if err != nil {
		r.Fatalf("reading %s: %v", mockeryHeaderFile, err)
	}
	// Trailing newlines are trimmed on both sides of the comparison below, because
	// whether the committed file ends with one is not something the generated output
	// depends on.
	boilerplate := strings.TrimRight(string(header), " \t\r\n")
	if boilerplate == "" {
		r.Fatalf("%s is empty, so every mock would trivially carry it", mockeryHeaderFile)
	}

	stale, generated, err := findUnpinnedMocks(root, boilerplate)
	if err != nil {
		r.Fatalf("walking %s: %v", root, err)
	}
	// A root holding no generated mock satisfies the rule by having nothing to check,
	// which is the one way a guard like this fails silently in the direction that matters.
	if generated == 0 {
		r.Fatalf("walked no mockery-generated files under %s", root)
	}

	// Without this the two sides could agree on a header that names no version at all,
	// which is the state #338 found: mocks consistent with each other and silent about
	// the generator.
	if !strings.Contains(boilerplate, mockeryVersionPhrase(pin)) {
		r.Errorf("%s does not name the pinned generator: %s pins tools.mockery %s, so the header "+
			"must contain %q. Run ./version-manager.sh update in src/authserver, then "+
			"./generate-mocks.sh, and commit both (#338)",
			mockeryHeaderFile, mockeryPinFile, pin, mockeryVersionPhrase(pin))
	}

	if len(stale) > 0 {
		r.Errorf("%d of %d mockery-generated file(s) do not begin with the header committed in %s, "+
			"so they were written by a different generator or before the pin moved; run "+
			"src/authserver/generate-mocks.sh in the dev container and commit the result (#338):\n\t%s",
			len(stale), generated, mockeryHeaderFile, strings.Join(stale, "\n\t"))
	}
}

const (
	// mockeryHeaderFile is the boilerplate inlined into every generated mock, and
	// mockeryPinFile the pin it is written from. Both are relative to the source root.
	mockeryHeaderFile = "mockery-header.txt"
	mockeryPinFile    = "authserver/versions.yaml"
)

// mockeryVersionPhrase is the one spelling of the version that both the header and this
// guard agree on. The header is prose, and version-manager.sh rewrites it with a sed whose
// pattern is this same phrase, so a reworded header that drops it leaves that sed matching
// nothing -- silently, since a sed that replaces nothing still succeeds. Requiring the
// phrase here is what makes that loud.
func mockeryVersionPhrase(pin string) string {
	return "mockery v" + pin
}

// findUnpinnedMocks walks every Go file under root and returns the mockery-generated ones
// that do not begin with boilerplate, relative to root with forward slashes, along with the
// number of generated files it reached.
func findUnpinnedMocks(root, boilerplate string) ([]string, int, error) {
	var stale []string
	generated := 0
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		src, rErr := os.ReadFile(path)
		if rErr != nil {
			return rErr
		}
		text := string(src)
		if !isMockeryGenerated(text) {
			return nil
		}
		generated++
		// The newline is part of the prefix so that a longer first line cannot satisfy a
		// shorter one: without it a file headed "mockery v3.8.0.1" carries "mockery v3.8.0."
		// as a prefix and passes.
		if strings.HasPrefix(text, boilerplate+"\n") {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = path
		}
		stale = append(stale, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return nil, 0, errs.WithStack(err)
	}
	return stale, generated, nil
}

// mockeryGeneratedRe is the Go convention's generated-file marker, narrowed to mockery. The
// shape is the one mockery itself matches in internal/parse.go when it decides which files
// to skip while parsing a package, so this guard and the generator agree on what a generated
// file is; naming mockery inside it is what keeps the other generators in this tree out.
var mockeryGeneratedRe = regexp.MustCompile(`^// Code generated by .*mockery.* DO NOT EDIT\.?\s*$`)

// isMockeryGenerated reports whether src carries mockery's marker in the comments above its
// package clause. Stopping at the clause is what mockery's own detection does, and it means a
// test fixture or a doc comment that quotes the marker further down the file is not mistaken
// for generated output.
func isMockeryGenerated(src string) bool {
	for _, line := range strings.Split(src, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.HasPrefix(line, "package ") {
			return false
		}
		if mockeryGeneratedRe.MatchString(line) {
			return true
		}
	}
	return false
}

// pinnedMockeryVersion reads tools.mockery out of versions.yaml.
//
// It scans the text rather than unmarshalling it, which keeps yaml out of core's direct
// dependencies for the sake of one scalar, and is the choice AssertArchitecture made in
// parsing ARCHITECTURE.md's tables. The section matters and is not decoration: cdn: holds
// keys beside tools:, so a scan that took the first "mockery:" line anywhere would read
// whichever section happened to come first.
func pinnedMockeryVersion(versionsFile string) (string, error) {
	src, err := os.ReadFile(versionsFile)
	if err != nil {
		return "", errs.Wrapf(err, "reading %s", mockeryPinFile)
	}

	inTools := false
	for _, line := range strings.Split(string(src), "\n") {
		line = strings.TrimRight(line, " \t\r")
		if line == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		// A key at column zero opens a section and closes whichever one preceded it.
		if !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") {
			inTools = strings.HasPrefix(line, "tools:")
			continue
		}
		if !inTools {
			continue
		}
		key, value, found := strings.Cut(strings.TrimSpace(line), ":")
		if !found || key != "mockery" {
			continue
		}
		pin := strings.TrimSpace(value)
		// A trailing comment is part of the line, not of the value. Only one preceded by
		// whitespace, so a "#" inside the value itself survives.
		if hash := strings.Index(pin, " #"); hash >= 0 {
			pin = strings.TrimSpace(pin[:hash])
		}
		pin = strings.Trim(pin, `"'`)
		if pin == "" {
			return "", errs.Errorf("tools.mockery in %s has no value", mockeryPinFile)
		}
		return pin, nil
	}
	return "", errs.Errorf("no tools.mockery key under a tools: section in %s", mockeryPinFile)
}
