package testutil

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The two seams of AssertGeneratedMocksArePinned, over fixture trees. The real caller walks the
// repository, which is pinned by construction after #338 and passes, so nothing there observes
// either the rule refusing a file or the reporting half failing -- which is the shape guard.go
// exists to stop.

const (
	// The fixtures' own pin and header, deliberately shorter than the committed ones so the
	// trees below read at a glance. The only thing the guard requires of the header is that it
	// contain "mockery v" + the pin.
	fixturePin    = "3.8.0"
	fixtureHeader = "// Generated by mockery v3.8.0.\n"

	// mockery's own three header lines, verbatim, including the two the rule does not read.
	fixtureMarker = "// Code generated by mockery; DO NOT EDIT.\n" +
		"// github.com/vektra/mockery\n" +
		"// template: testify\n"
)

// generatedMock renders what mockery writes when boilerplate-file names a file holding header:
// the boilerplate, a blank line, mockery's marker, then the file.
func generatedMock(header string) string {
	return header + "\n" + fixtureMarker + "\n//go:build !production\n\npackage mocks_p\n"
}

// writeMockeryTree lays down the two files the reporting half reads before it walks anything.
func writeMockeryTree(t *testing.T, root, pin, header string) {
	t.Helper()
	writeFixture(t, root, "authserver/versions.yaml", "tools:\n  mockery: \""+pin+"\"\n")
	writeFixture(t, root, "mockery-header.txt", header)
}

// Seam 1: the rule. Every shape a file in this tree can have, and what the walk does with it.
//
// The rows that matter most are the ones the walk must NOT count. A guard that held every
// *_mock.go to a generator's header would demand a lie of the hand-written one, and a guard that
// held every generated file to mockery's pin would fail on the countries and timezones tables,
// which have their own generators and no connection to it.
func TestMockeryPin_TheRuleTable(t *testing.T) {
	root := t.TempDir()
	header := "// Generated by mockery v3.8.0."

	// ---- counted, and current ------------------------------------------------------------
	writeFixture(t, root, "core/a/mocks/current_mock.go", generatedMock(fixtureHeader))
	writeFixture(t, root, "core/a/mocks/nested/deeper/also_current_mock.go", generatedMock(fixtureHeader))

	// ---- counted, and stale --------------------------------------------------------------

	// Generated before the pin moved, which is exactly the sixteen files of #338.
	writeFixture(t, root, "core/b/mocks/old_pin_mock.go", generatedMock("// Generated by mockery v3.7.0.\n"))
	// Generated before the header existed at all: mockery's marker is the first line.
	writeFixture(t, root, "core/b/mocks/no_header_mock.go", fixtureMarker+"\npackage mocks_p\n")
	// A first line the committed header is a prefix of. Without the newline in the comparison
	// this one passes, because "mockery v3.8.0." is a prefix of "mockery v3.8.0.1".
	writeFixture(t, root, "core/b/mocks/longer_first_line_mock.go", generatedMock("// Generated by mockery v3.8.0.1 hand-edited.\n"))

	// ---- not counted ---------------------------------------------------------------------

	// Hand-written scaffolding carrying the _mock.go name, which is src/core/mocks/test_fs_mock.go.
	// The rule keys on the marker, so this is not a generated file and owes no header.
	writeFixture(t, root, "core/mocks/test_fs_mock.go", "package mocks\n\ntype TestFS struct{}\n")
	// Another generator's output: core/countries/data_generated.go and core/timezones/timezones.go.
	writeFixture(t, root, "core/countries/data_generated.go", "// Code generated by go generate; DO NOT EDIT.\n\npackage countries\n")
	// The marker below the package clause is not a header, which is where mockery stops looking too.
	writeFixture(t, root, "core/c/late_marker.go", "package c\n\n// Code generated by mockery; DO NOT EDIT.\nvar x = 1\n")
	// A doc comment that quotes the marker is what this file itself does, twice.
	writeFixture(t, root, "core/c/quotes_the_marker.go", "package c\n\n// mentions \"// Code generated by mockery; DO NOT EDIT.\" in prose\nvar y = 2\n")
	// Not Go.
	writeFixture(t, root, "core/c/notes.txt", generatedMock(fixtureHeader))

	stale, generated, err := findUnpinnedMocks(root, header)
	require.NoError(t, err)

	assert.Equal(t, 5, generated,
		"the two current mocks and the three stale ones, and neither the hand-written mock, the "+
			"other generator's file, the two files whose marker is not a header, nor the .txt")
	assert.Equal(t, []string{
		"core/b/mocks/longer_first_line_mock.go",
		"core/b/mocks/no_header_mock.go",
		"core/b/mocks/old_pin_mock.go",
	}, stale)
}

// TestMockeryPin_APinnedTreeReportsNothing is the other direction, and it is what keeps the case
// above from passing for the wrong reason.
func TestMockeryPin_APinnedTreeReportsNothing(t *testing.T) {
	root := t.TempDir()
	writeMockeryTree(t, root, fixturePin, fixtureHeader)
	writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(fixtureHeader))
	writeFixture(t, root, "core/b/mocks/two_mock.go", generatedMock(fixtureHeader))

	stale, generated, err := findUnpinnedMocks(root, "// Generated by mockery v3.8.0.")
	require.NoError(t, err)
	assert.Equal(t, 2, generated)
	assert.Empty(t, stale)

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })
	assert.False(t, report.Failed(), "a pinned tree failed the guard: %s", report.Text())
}

// Seam 2: the reporting half, which until now was reached only by three callers all walking the
// same clean tree.

// TestMockeryPin_AStaleMockFails drives the finding #338 is about, and holds the message to naming
// the file and the one command that fixes it.
func TestMockeryPin_AStaleMockFails(t *testing.T) {
	root := t.TempDir()
	writeMockeryTree(t, root, fixturePin, fixtureHeader)
	writeFixture(t, root, "core/a/mocks/current_mock.go", generatedMock(fixtureHeader))
	writeFixture(t, root, "core/b/mocks/stale_mock.go", generatedMock("// Generated by mockery v3.7.0.\n"))

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

	require.True(t, report.Failed(), "a mock from an older generator passed the guard")
	assert.False(t, report.Stopped, "a stale mock is an Errorf, not a Fatalf")
	require.Len(t, report.Errors, 1)
	assert.Contains(t, report.Text(), "core/b/mocks/stale_mock.go")
	assert.Contains(t, report.Text(), "1 of 2 mockery-generated file(s)")
	assert.Contains(t, report.Text(), "generate-mocks.sh")
	assert.NotContains(t, report.Text(), "core/a/mocks/current_mock.go")
}

// TestMockeryPin_AHeaderThatNamesNoVersionFails is the second finding, and it is the one that
// makes the header worth having. Mocks agreeing with a header that says nothing about the
// generator is the state #338 found: consistent, and silent about the only fact anyone needed.
func TestMockeryPin_AHeaderThatNamesNoVersionFails(t *testing.T) {
	root := t.TempDir()
	silent := "// Generated by mockery. Do not edit.\n"
	writeMockeryTree(t, root, fixturePin, silent)
	writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(silent))

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

	require.True(t, report.Failed(), "a header naming no version passed the guard")
	assert.False(t, report.Stopped)
	require.Len(t, report.Errors, 1, "the mocks match the header, so only the header is reported")
	assert.Contains(t, report.Text(), `"mockery v3.8.0"`)
	assert.Contains(t, report.Text(), "version-manager.sh update")
}

// TestMockeryPin_AHeaderNamingTheWrongVersionFails is the same finding reached the other way, and
// it is the drift the sed in version-manager.sh exists to prevent: the pin moved, the header did
// not follow, and the mocks are consistent with the header rather than with the pin.
func TestMockeryPin_AHeaderNamingTheWrongVersionFails(t *testing.T) {
	root := t.TempDir()
	behind := "// Generated by mockery v3.7.0.\n"
	writeMockeryTree(t, root, fixturePin, behind)
	writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(behind))

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

	require.True(t, report.Failed())
	assert.Contains(t, report.Text(), "does not name the pinned generator")
	assert.Contains(t, report.Text(), `"mockery v3.8.0"`)
}

// TestMockeryPin_AWalkThatReachesNoMockFails pins the seam. A tree with no generated file in it
// satisfies the rule by having nothing to check, and is otherwise indistinguishable from a tree
// whose mocks are all current.
func TestMockeryPin_AWalkThatReachesNoMockFails(t *testing.T) {
	root := t.TempDir()
	writeMockeryTree(t, root, fixturePin, fixtureHeader)
	writeFixture(t, root, "core/a/ordinary.go", "package a\n")

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

	require.True(t, report.Stopped, "an empty walk must be fatal rather than a pass")
	assert.Contains(t, report.Fatal, "walked no mockery-generated files under")
}

// TestMockeryPin_AnEmptyHeaderFileIsFatal is the same seam reached through the header rather than
// the walk: every file trivially begins with nothing, so an emptied header would pass every mock
// in the tree while recording no version at all.
func TestMockeryPin_AnEmptyHeaderFileIsFatal(t *testing.T) {
	root := t.TempDir()
	writeMockeryTree(t, root, fixturePin, "\n \n")
	writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(fixtureHeader))

	report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

	require.True(t, report.Stopped)
	assert.Contains(t, report.Fatal, "is empty, so every mock would trivially carry it")
}

// TestMockeryPin_MissingInputsAreFatal covers the two files the guard cannot proceed without. Both
// are Fatalf rather than Errorf because neither is a finding about the tree: they say the guard is
// looking in the wrong place, which is the failure a wrong root produces and the one that would
// otherwise read as a clean pass.
func TestMockeryPin_MissingInputsAreFatal(t *testing.T) {
	t.Run("no versions.yaml", func(t *testing.T) {
		root := t.TempDir()
		writeFixture(t, root, "mockery-header.txt", fixtureHeader)
		writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(fixtureHeader))

		report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

		require.True(t, report.Stopped)
		assert.Contains(t, report.Fatal, "authserver/versions.yaml")
	})

	t.Run("no mockery-header.txt", func(t *testing.T) {
		root := t.TempDir()
		writeFixture(t, root, "authserver/versions.yaml", "tools:\n  mockery: \"3.8.0\"\n")
		writeFixture(t, root, "core/a/mocks/one_mock.go", generatedMock(fixtureHeader))

		report := RunGuard(func(r Reporter) { assertGeneratedMocksArePinned(r, root) })

		require.True(t, report.Stopped)
		assert.Contains(t, report.Fatal, "reading mockery-header.txt")
	})
}

// TestMockeryPin_ReadingThePin covers the scan that stands in for a yaml unmarshal, which keeps
// that dependency out of core for the sake of one scalar. The section is the row worth having:
// versions.yaml has a cdn: block beside tools:, so a scan taking the first "mockery:" line
// anywhere reads whichever section came first, and would keep reading it after the pin moved.
func TestMockeryPin_ReadingThePin(t *testing.T) {
	cases := []struct {
		name string
		yaml string
		want string
		err  string
	}{
		{
			name: "quoted, which is how versions.yaml writes it",
			yaml: "tools:\n  go: \"1.27.1\"\n  mockery: \"3.8.0\"\n",
			want: "3.8.0",
		},
		{
			name: "unquoted",
			yaml: "tools:\n  mockery: 3.8.0\n",
			want: "3.8.0",
		},
		{
			name: "trailing comment is not part of the value",
			yaml: "tools:\n  mockery: \"3.8.0\" # bump with the devcontainer\n",
			want: "3.8.0",
		},
		{
			name: "the comment block versions.yaml carries above tools:",
			yaml: "# mockery: mock generator version (devcontainer)\n# mockery:  \"9.9.9\"\ntools:\n  mockery: \"3.8.0\"\n",
			want: "3.8.0",
		},
		{
			name: "a key of the same name in another section is not the pin",
			yaml: "cdn:\n  mockery: \"9.9.9\"\ntools:\n  mockery: \"3.8.0\"\n",
			want: "3.8.0",
		},
		{
			name: "only in another section, so there is no pin",
			yaml: "cdn:\n  mockery: \"9.9.9\"\n",
			err:  "no tools.mockery key under a tools: section",
		},
		{
			name: "no such key",
			yaml: "tools:\n  go: \"1.27.1\"\n",
			err:  "no tools.mockery key under a tools: section",
		},
		{
			name: "the key with nothing after it",
			yaml: "tools:\n  mockery:\n",
			err:  "tools.mockery in authserver/versions.yaml has no value",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "versions.yaml")
			require.NoError(t, os.WriteFile(path, []byte(tc.yaml), 0o644))

			pin, err := pinnedMockeryVersion(path)
			if tc.err != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tc.err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tc.want, pin)
		})
	}

	t.Run("a file that is not there", func(t *testing.T) {
		_, err := pinnedMockeryVersion(filepath.Join(t.TempDir(), "absent.yaml"))
		require.Error(t, err)
		assert.Contains(t, err.Error(), "reading authserver/versions.yaml")
	})
}

// TestMockeryPin_TheRealVersionsFileParses reads the file that actually decides, so a reformat of
// versions.yaml that this scan cannot follow is a failure here rather than a guard that quietly
// reports the wrong pin. The value is not asserted: it moves every time the pin does, and what
// this holds is that the scan still finds it.
func TestMockeryPin_TheRealVersionsFileParses(t *testing.T) {
	pin, err := pinnedMockeryVersion(filepath.Join(SourceRoot(t), mockeryPinFile))
	require.NoError(t, err)
	assert.Regexp(t, `^\d+\.\d+\.\d+`, pin, "tools.mockery reads as a version")
}
