//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_user

import (
	"github.com/leodip/goiabada/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewPermissionChecker creates a new instance of PermissionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionChecker {
	mock := &PermissionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PermissionChecker is an autogenerated mock type for the PermissionChecker type
type PermissionChecker struct {
	mock.Mock
}

type PermissionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionChecker) EXPECT() *PermissionChecker_Expecter {
	return &PermissionChecker_Expecter{mock: &_m.Mock}
}

// FilterOutScopesWhereUserIsNotAuthorized provides a mock function for the type PermissionChecker
func (_mock *PermissionChecker) FilterOutScopesWhereUserIsNotAuthorized(scope string, user *models.User) (string, error) {
	ret := _mock.Called(scope, user)

	if len(ret) == 0 {
		panic("no return value specified for FilterOutScopesWhereUserIsNotAuthorized")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *models.User) (string, error)); ok {
		return returnFunc(scope, user)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *models.User) string); ok {
		r0 = returnFunc(scope, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *models.User) error); ok {
		r1 = returnFunc(scope, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterOutScopesWhereUserIsNotAuthorized'
type PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call struct {
	*mock.Call
}

// FilterOutScopesWhereUserIsNotAuthorized is a helper method to define mock.On call
//   - scope string
//   - user *models.User
func (_e *PermissionChecker_Expecter) FilterOutScopesWhereUserIsNotAuthorized(scope interface{}, user interface{}) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	return &PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call{Call: _e.mock.On("FilterOutScopesWhereUserIsNotAuthorized", scope, user)}
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) Run(run func(scope string, user *models.User)) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) Return(s string, err error) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) RunAndReturn(run func(scope string, user *models.User) (string, error)) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Return(run)
	return _c
}

// UserHasScopePermission provides a mock function for the type PermissionChecker
func (_mock *PermissionChecker) UserHasScopePermission(userId int64, scope string) (bool, error) {
	ret := _mock.Called(userId, scope)

	if len(ret) == 0 {
		panic("no return value specified for UserHasScopePermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (bool, error)); ok {
		return returnFunc(userId, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) bool); ok {
		r0 = returnFunc(userId, scope)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(userId, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionChecker_UserHasScopePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHasScopePermission'
type PermissionChecker_UserHasScopePermission_Call struct {
	*mock.Call
}

// UserHasScopePermission is a helper method to define mock.On call
//   - userId int64
//   - scope string
func (_e *PermissionChecker_Expecter) UserHasScopePermission(userId interface{}, scope interface{}) *PermissionChecker_UserHasScopePermission_Call {
	return &PermissionChecker_UserHasScopePermission_Call{Call: _e.mock.On("UserHasScopePermission", userId, scope)}
}

func (_c *PermissionChecker_UserHasScopePermission_Call) Run(run func(userId int64, scope string)) *PermissionChecker_UserHasScopePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PermissionChecker_UserHasScopePermission_Call) Return(b bool, err error) *PermissionChecker_UserHasScopePermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *PermissionChecker_UserHasScopePermission_Call) RunAndReturn(run func(userId int64, scope string) (bool, error)) *PermissionChecker_UserHasScopePermission_Call {
	_c.Call.Return(run)
	return _c
}
