//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_user

import (
	"github.com/leodip/goiabada/core/models"
	"github.com/leodip/goiabada/core/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserCreator creates a new instance of UserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreator {
	mock := &UserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserCreator is an autogenerated mock type for the UserCreator type
type UserCreator struct {
	mock.Mock
}

type UserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCreator) EXPECT() *UserCreator_Expecter {
	return &UserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserCreator
func (_mock *UserCreator) CreateUser(input *user.CreateUserInput) (*models.User, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*user.CreateUserInput) (*models.User, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*user.CreateUserInput) *models.User); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*user.CreateUserInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - input *user.CreateUserInput
func (_e *UserCreator_Expecter) CreateUser(input interface{}) *UserCreator_CreateUser_Call {
	return &UserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", input)}
}

func (_c *UserCreator_CreateUser_Call) Run(run func(input *user.CreateUserInput)) *UserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.CreateUserInput
		if args[0] != nil {
			arg0 = args[0].(*user.CreateUserInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserCreator_CreateUser_Call) Return(user1 *models.User, err error) *UserCreator_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserCreator_CreateUser_Call) RunAndReturn(run func(input *user.CreateUserInput) (*models.User, error)) *UserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}
