//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_user

import (
	"context"
	"net/http"

	"github.com/leodip/goiabada/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUserSessionManager creates a new instance of UserSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSessionManager {
	mock := &UserSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSessionManager is an autogenerated mock type for the UserSessionManager type
type UserSessionManager struct {
	mock.Mock
}

type UserSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSessionManager) EXPECT() *UserSessionManager_Expecter {
	return &UserSessionManager_Expecter{mock: &_m.Mock}
}

// BumpUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) BumpUserSession(r *http.Request, sessionIdentifier string, clientId int64, authMethods string, acrLevel string) (*models.UserSession, error) {
	ret := _mock.Called(r, sessionIdentifier, clientId, authMethods, acrLevel)

	if len(ret) == 0 {
		panic("no return value specified for BumpUserSession")
	}

	var r0 *models.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, int64, string, string) (*models.UserSession, error)); ok {
		return returnFunc(r, sessionIdentifier, clientId, authMethods, acrLevel)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, int64, string, string) *models.UserSession); ok {
		r0 = returnFunc(r, sessionIdentifier, clientId, authMethods, acrLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string, int64, string, string) error); ok {
		r1 = returnFunc(r, sessionIdentifier, clientId, authMethods, acrLevel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserSessionManager_BumpUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpUserSession'
type UserSessionManager_BumpUserSession_Call struct {
	*mock.Call
}

// BumpUserSession is a helper method to define mock.On call
//   - r *http.Request
//   - sessionIdentifier string
//   - clientId int64
//   - authMethods string
//   - acrLevel string
func (_e *UserSessionManager_Expecter) BumpUserSession(r interface{}, sessionIdentifier interface{}, clientId interface{}, authMethods interface{}, acrLevel interface{}) *UserSessionManager_BumpUserSession_Call {
	return &UserSessionManager_BumpUserSession_Call{Call: _e.mock.On("BumpUserSession", r, sessionIdentifier, clientId, authMethods, acrLevel)}
}

func (_c *UserSessionManager_BumpUserSession_Call) Run(run func(r *http.Request, sessionIdentifier string, clientId int64, authMethods string, acrLevel string)) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserSessionManager_BumpUserSession_Call) Return(userSession *models.UserSession, err error) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *UserSessionManager_BumpUserSession_Call) RunAndReturn(run func(r *http.Request, sessionIdentifier string, clientId int64, authMethods string, acrLevel string) (*models.UserSession, error)) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// HasValidUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) HasValidUserSession(ctx context.Context, userSession *models.UserSession, requestedMaxAgeInSeconds *int) bool {
	ret := _mock.Called(ctx, userSession, requestedMaxAgeInSeconds)

	if len(ret) == 0 {
		panic("no return value specified for HasValidUserSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserSession, *int) bool); ok {
		r0 = returnFunc(ctx, userSession, requestedMaxAgeInSeconds)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// UserSessionManager_HasValidUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasValidUserSession'
type UserSessionManager_HasValidUserSession_Call struct {
	*mock.Call
}

// HasValidUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userSession *models.UserSession
//   - requestedMaxAgeInSeconds *int
func (_e *UserSessionManager_Expecter) HasValidUserSession(ctx interface{}, userSession interface{}, requestedMaxAgeInSeconds interface{}) *UserSessionManager_HasValidUserSession_Call {
	return &UserSessionManager_HasValidUserSession_Call{Call: _e.mock.On("HasValidUserSession", ctx, userSession, requestedMaxAgeInSeconds)}
}

func (_c *UserSessionManager_HasValidUserSession_Call) Run(run func(ctx context.Context, userSession *models.UserSession, requestedMaxAgeInSeconds *int)) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UserSession
		if args[1] != nil {
			arg1 = args[1].(*models.UserSession)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserSessionManager_HasValidUserSession_Call) Return(b bool) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *UserSessionManager_HasValidUserSession_Call) RunAndReturn(run func(ctx context.Context, userSession *models.UserSession, requestedMaxAgeInSeconds *int) bool) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartNewUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) StartNewUserSession(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel string) (*models.UserSession, error) {
	ret := _mock.Called(w, r, userId, clientId, authMethods, acrLevel)

	if len(ret) == 0 {
		panic("no return value specified for StartNewUserSession")
	}

	var r0 *models.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, int64, int64, string, string) (*models.UserSession, error)); ok {
		return returnFunc(w, r, userId, clientId, authMethods, acrLevel)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, int64, int64, string, string) *models.UserSession); ok {
		r0 = returnFunc(w, r, userId, clientId, authMethods, acrLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, int64, int64, string, string) error); ok {
		r1 = returnFunc(w, r, userId, clientId, authMethods, acrLevel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserSessionManager_StartNewUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNewUserSession'
type UserSessionManager_StartNewUserSession_Call struct {
	*mock.Call
}

// StartNewUserSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - userId int64
//   - clientId int64
//   - authMethods string
//   - acrLevel string
func (_e *UserSessionManager_Expecter) StartNewUserSession(w interface{}, r interface{}, userId interface{}, clientId interface{}, authMethods interface{}, acrLevel interface{}) *UserSessionManager_StartNewUserSession_Call {
	return &UserSessionManager_StartNewUserSession_Call{Call: _e.mock.On("StartNewUserSession", w, r, userId, clientId, authMethods, acrLevel)}
}

func (_c *UserSessionManager_StartNewUserSession_Call) Run(run func(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel string)) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *UserSessionManager_StartNewUserSession_Call) Return(userSession *models.UserSession, err error) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *UserSessionManager_StartNewUserSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel string) (*models.UserSession, error)) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Return(run)
	return _c
}
