//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_inputsanitizer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewInputSanitizer creates a new instance of InputSanitizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInputSanitizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *InputSanitizer {
	mock := &InputSanitizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InputSanitizer is an autogenerated mock type for the InputSanitizer type
type InputSanitizer struct {
	mock.Mock
}

type InputSanitizer_Expecter struct {
	mock *mock.Mock
}

func (_m *InputSanitizer) EXPECT() *InputSanitizer_Expecter {
	return &InputSanitizer_Expecter{mock: &_m.Mock}
}

// Sanitize provides a mock function for the type InputSanitizer
func (_mock *InputSanitizer) Sanitize(str string) string {
	ret := _mock.Called(str)

	if len(ret) == 0 {
		panic("no return value specified for Sanitize")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(str)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// InputSanitizer_Sanitize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sanitize'
type InputSanitizer_Sanitize_Call struct {
	*mock.Call
}

// Sanitize is a helper method to define mock.On call
//   - str string
func (_e *InputSanitizer_Expecter) Sanitize(str interface{}) *InputSanitizer_Sanitize_Call {
	return &InputSanitizer_Sanitize_Call{Call: _e.mock.On("Sanitize", str)}
}

func (_c *InputSanitizer_Sanitize_Call) Run(run func(str string)) *InputSanitizer_Sanitize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *InputSanitizer_Sanitize_Call) Return(s string) *InputSanitizer_Sanitize_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *InputSanitizer_Sanitize_Call) RunAndReturn(run func(str string) string) *InputSanitizer_Sanitize_Call {
	_c.Call.Return(run)
	return _c
}
