version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../..:/workspaces/goiabada
      - ~/.config/gh/hosts.yml:/root/.config/gh/hosts.yml
    ports:
      - 8090:8090
    command: sleep infinity
    networks: 
      - goiabada-network

networks:
  goiabada-network: