// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuditLogger is an autogenerated mock type for the AuditLogger type
type AuditLogger struct {
	mock.Mock
}

// Log provides a mock function with given fields: auditEvent, details
func (_m *AuditLogger) Log(auditEvent string, details map[string]interface{}) {
	_m.Called(auditEvent, details)
}

// NewAuditLogger creates a new instance of AuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogger {
	mock := &AuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
