// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_accountvalidation

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/accountvalidation"
	mock "github.com/stretchr/testify/mock"
)

// NewEmailValidator creates a new instance of EmailValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &EmailValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// EmailValidator is an autogenerated mock type for the EmailValidator type
type EmailValidator struct {
	mock.Mock
}

type EmailValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailValidator) EXPECT() *EmailValidator_Expecter {
	return &EmailValidator_Expecter{mock: &_m.Mock}
}

// ValidateEmailAddress provides a mock function for the type EmailValidator
func (_mock *EmailValidator) ValidateEmailAddress(emailAddress string) error {
	ret := _mock.Called(emailAddress)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmailAddress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(emailAddress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailValidator_ValidateEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEmailAddress'
type EmailValidator_ValidateEmailAddress_Call struct {
	*mock.Call
}

// ValidateEmailAddress is a helper method to define mock.On call
//   - emailAddress string
func (_e *EmailValidator_Expecter) ValidateEmailAddress(emailAddress any) *EmailValidator_ValidateEmailAddress_Call {
	return &EmailValidator_ValidateEmailAddress_Call{Call: _e.mock.On("ValidateEmailAddress", emailAddress)}
}

func (_c *EmailValidator_ValidateEmailAddress_Call) Run(run func(emailAddress string)) *EmailValidator_ValidateEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EmailValidator_ValidateEmailAddress_Call) Return(err error) *EmailValidator_ValidateEmailAddress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailValidator_ValidateEmailAddress_Call) RunAndReturn(run func(emailAddress string) error) *EmailValidator_ValidateEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEmailUpdate provides a mock function for the type EmailValidator
func (_mock *EmailValidator) ValidateEmailUpdate(ctx context.Context, input *accountvalidation.ValidateEmailInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmailUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *accountvalidation.ValidateEmailInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailValidator_ValidateEmailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEmailUpdate'
type EmailValidator_ValidateEmailUpdate_Call struct {
	*mock.Call
}

// ValidateEmailUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - input *accountvalidation.ValidateEmailInput
func (_e *EmailValidator_Expecter) ValidateEmailUpdate(ctx any, input any) *EmailValidator_ValidateEmailUpdate_Call {
	return &EmailValidator_ValidateEmailUpdate_Call{Call: _e.mock.On("ValidateEmailUpdate", ctx, input)}
}

func (_c *EmailValidator_ValidateEmailUpdate_Call) Run(run func(ctx context.Context, input *accountvalidation.ValidateEmailInput)) *EmailValidator_ValidateEmailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *accountvalidation.ValidateEmailInput
		if args[1] != nil {
			arg1 = args[1].(*accountvalidation.ValidateEmailInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmailValidator_ValidateEmailUpdate_Call) Return(err error) *EmailValidator_ValidateEmailUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailValidator_ValidateEmailUpdate_Call) RunAndReturn(run func(ctx context.Context, input *accountvalidation.ValidateEmailInput) error) *EmailValidator_ValidateEmailUpdate_Call {
	_c.Call.Return(run)
	return _c
}
