//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_handler_helpers

import (
	"net/http"

	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthHelper creates a new instance of AuthHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHelper {
	mock := &AuthHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthHelper is an autogenerated mock type for the AuthHelper type
type AuthHelper struct {
	mock.Mock
}

type AuthHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthHelper) EXPECT() *AuthHelper_Expecter {
	return &AuthHelper_Expecter{mock: &_m.Mock}
}

// ClearAuthContext provides a mock function for the type AuthHelper
func (_mock *AuthHelper) ClearAuthContext(w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for ClearAuthContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHelper_ClearAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAuthContext'
type AuthHelper_ClearAuthContext_Call struct {
	*mock.Call
}

// ClearAuthContext is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthHelper_Expecter) ClearAuthContext(w interface{}, r interface{}) *AuthHelper_ClearAuthContext_Call {
	return &AuthHelper_ClearAuthContext_Call{Call: _e.mock.On("ClearAuthContext", w, r)}
}

func (_c *AuthHelper_ClearAuthContext_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthHelper_ClearAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHelper_ClearAuthContext_Call) Return(err error) *AuthHelper_ClearAuthContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHelper_ClearAuthContext_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) error) *AuthHelper_ClearAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthContext provides a mock function for the type AuthHelper
func (_mock *AuthHelper) GetAuthContext(r *http.Request) (*oauth.AuthContext, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthContext")
	}

	var r0 *oauth.AuthContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*oauth.AuthContext, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *oauth.AuthContext); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.AuthContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHelper_GetAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthContext'
type AuthHelper_GetAuthContext_Call struct {
	*mock.Call
}

// GetAuthContext is a helper method to define mock.On call
//   - r *http.Request
func (_e *AuthHelper_Expecter) GetAuthContext(r interface{}) *AuthHelper_GetAuthContext_Call {
	return &AuthHelper_GetAuthContext_Call{Call: _e.mock.On("GetAuthContext", r)}
}

func (_c *AuthHelper_GetAuthContext_Call) Run(run func(r *http.Request)) *AuthHelper_GetAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHelper_GetAuthContext_Call) Return(authContext *oauth.AuthContext, err error) *AuthHelper_GetAuthContext_Call {
	_c.Call.Return(authContext, err)
	return _c
}

func (_c *AuthHelper_GetAuthContext_Call) RunAndReturn(run func(r *http.Request) (*oauth.AuthContext, error)) *AuthHelper_GetAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoggedInSubject provides a mock function for the type AuthHelper
func (_mock *AuthHelper) GetLoggedInSubject(r *http.Request) string {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetLoggedInSubject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// AuthHelper_GetLoggedInSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoggedInSubject'
type AuthHelper_GetLoggedInSubject_Call struct {
	*mock.Call
}

// GetLoggedInSubject is a helper method to define mock.On call
//   - r *http.Request
func (_e *AuthHelper_Expecter) GetLoggedInSubject(r interface{}) *AuthHelper_GetLoggedInSubject_Call {
	return &AuthHelper_GetLoggedInSubject_Call{Call: _e.mock.On("GetLoggedInSubject", r)}
}

func (_c *AuthHelper_GetLoggedInSubject_Call) Run(run func(r *http.Request)) *AuthHelper_GetLoggedInSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHelper_GetLoggedInSubject_Call) Return(s string) *AuthHelper_GetLoggedInSubject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *AuthHelper_GetLoggedInSubject_Call) RunAndReturn(run func(r *http.Request) string) *AuthHelper_GetLoggedInSubject_Call {
	_c.Call.Return(run)
	return _c
}

// IsAuthenticated provides a mock function for the type AuthHelper
func (_mock *AuthHelper) IsAuthenticated(jwtInfo oauth.JwtInfo) bool {
	ret := _mock.Called(jwtInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthenticated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(oauth.JwtInfo) bool); ok {
		r0 = returnFunc(jwtInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AuthHelper_IsAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAuthenticated'
type AuthHelper_IsAuthenticated_Call struct {
	*mock.Call
}

// IsAuthenticated is a helper method to define mock.On call
//   - jwtInfo oauth.JwtInfo
func (_e *AuthHelper_Expecter) IsAuthenticated(jwtInfo interface{}) *AuthHelper_IsAuthenticated_Call {
	return &AuthHelper_IsAuthenticated_Call{Call: _e.mock.On("IsAuthenticated", jwtInfo)}
}

func (_c *AuthHelper_IsAuthenticated_Call) Run(run func(jwtInfo oauth.JwtInfo)) *AuthHelper_IsAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 oauth.JwtInfo
		if args[0] != nil {
			arg0 = args[0].(oauth.JwtInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHelper_IsAuthenticated_Call) Return(b bool) *AuthHelper_IsAuthenticated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *AuthHelper_IsAuthenticated_Call) RunAndReturn(run func(jwtInfo oauth.JwtInfo) bool) *AuthHelper_IsAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// IsAuthorizedToAccessResource provides a mock function for the type AuthHelper
func (_mock *AuthHelper) IsAuthorizedToAccessResource(jwtInfo oauth.JwtInfo, scopesAnyOf []string) bool {
	ret := _mock.Called(jwtInfo, scopesAnyOf)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthorizedToAccessResource")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(oauth.JwtInfo, []string) bool); ok {
		r0 = returnFunc(jwtInfo, scopesAnyOf)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AuthHelper_IsAuthorizedToAccessResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAuthorizedToAccessResource'
type AuthHelper_IsAuthorizedToAccessResource_Call struct {
	*mock.Call
}

// IsAuthorizedToAccessResource is a helper method to define mock.On call
//   - jwtInfo oauth.JwtInfo
//   - scopesAnyOf []string
func (_e *AuthHelper_Expecter) IsAuthorizedToAccessResource(jwtInfo interface{}, scopesAnyOf interface{}) *AuthHelper_IsAuthorizedToAccessResource_Call {
	return &AuthHelper_IsAuthorizedToAccessResource_Call{Call: _e.mock.On("IsAuthorizedToAccessResource", jwtInfo, scopesAnyOf)}
}

func (_c *AuthHelper_IsAuthorizedToAccessResource_Call) Run(run func(jwtInfo oauth.JwtInfo, scopesAnyOf []string)) *AuthHelper_IsAuthorizedToAccessResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 oauth.JwtInfo
		if args[0] != nil {
			arg0 = args[0].(oauth.JwtInfo)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHelper_IsAuthorizedToAccessResource_Call) Return(b bool) *AuthHelper_IsAuthorizedToAccessResource_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *AuthHelper_IsAuthorizedToAccessResource_Call) RunAndReturn(run func(jwtInfo oauth.JwtInfo, scopesAnyOf []string) bool) *AuthHelper_IsAuthorizedToAccessResource_Call {
	_c.Call.Return(run)
	return _c
}

// RedirToAuthorize provides a mock function for the type AuthHelper
func (_mock *AuthHelper) RedirToAuthorize(w http.ResponseWriter, r *http.Request, clientIdentifier string, scope string, redirectBack string) error {
	ret := _mock.Called(w, r, clientIdentifier, scope, redirectBack)

	if len(ret) == 0 {
		panic("no return value specified for RedirToAuthorize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string, string, string) error); ok {
		r0 = returnFunc(w, r, clientIdentifier, scope, redirectBack)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHelper_RedirToAuthorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedirToAuthorize'
type AuthHelper_RedirToAuthorize_Call struct {
	*mock.Call
}

// RedirToAuthorize is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - clientIdentifier string
//   - scope string
//   - redirectBack string
func (_e *AuthHelper_Expecter) RedirToAuthorize(w interface{}, r interface{}, clientIdentifier interface{}, scope interface{}, redirectBack interface{}) *AuthHelper_RedirToAuthorize_Call {
	return &AuthHelper_RedirToAuthorize_Call{Call: _e.mock.On("RedirToAuthorize", w, r, clientIdentifier, scope, redirectBack)}
}

func (_c *AuthHelper_RedirToAuthorize_Call) Run(run func(w http.ResponseWriter, r *http.Request, clientIdentifier string, scope string, redirectBack string)) *AuthHelper_RedirToAuthorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthHelper_RedirToAuthorize_Call) Return(err error) *AuthHelper_RedirToAuthorize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHelper_RedirToAuthorize_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, clientIdentifier string, scope string, redirectBack string) error) *AuthHelper_RedirToAuthorize_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAuthContext provides a mock function for the type AuthHelper
func (_mock *AuthHelper) SaveAuthContext(w http.ResponseWriter, r *http.Request, authContext *oauth.AuthContext) error {
	ret := _mock.Called(w, r, authContext)

	if len(ret) == 0 {
		panic("no return value specified for SaveAuthContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, *oauth.AuthContext) error); ok {
		r0 = returnFunc(w, r, authContext)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHelper_SaveAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAuthContext'
type AuthHelper_SaveAuthContext_Call struct {
	*mock.Call
}

// SaveAuthContext is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - authContext *oauth.AuthContext
func (_e *AuthHelper_Expecter) SaveAuthContext(w interface{}, r interface{}, authContext interface{}) *AuthHelper_SaveAuthContext_Call {
	return &AuthHelper_SaveAuthContext_Call{Call: _e.mock.On("SaveAuthContext", w, r, authContext)}
}

func (_c *AuthHelper_SaveAuthContext_Call) Run(run func(w http.ResponseWriter, r *http.Request, authContext *oauth.AuthContext)) *AuthHelper_SaveAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 *oauth.AuthContext
		if args[2] != nil {
			arg2 = args[2].(*oauth.AuthContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthHelper_SaveAuthContext_Call) Return(err error) *AuthHelper_SaveAuthContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHelper_SaveAuthContext_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, authContext *oauth.AuthContext) error) *AuthHelper_SaveAuthContext_Call {
	_c.Call.Return(run)
	return _c
}
