//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_handler_helpers

import (
	"bytes"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHttpHelper creates a new instance of HttpHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpHelper {
	mock := &HttpHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HttpHelper is an autogenerated mock type for the HttpHelper type
type HttpHelper struct {
	mock.Mock
}

type HttpHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpHelper) EXPECT() *HttpHelper_Expecter {
	return &HttpHelper_Expecter{mock: &_m.Mock}
}

// EncodeJson provides a mock function for the type HttpHelper
func (_mock *HttpHelper) EncodeJson(w http.ResponseWriter, r *http.Request, data interface{}) {
	_mock.Called(w, r, data)
	return
}

// HttpHelper_EncodeJson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeJson'
type HttpHelper_EncodeJson_Call struct {
	*mock.Call
}

// EncodeJson is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - data interface{}
func (_e *HttpHelper_Expecter) EncodeJson(w interface{}, r interface{}, data interface{}) *HttpHelper_EncodeJson_Call {
	return &HttpHelper_EncodeJson_Call{Call: _e.mock.On("EncodeJson", w, r, data)}
}

func (_c *HttpHelper_EncodeJson_Call) Run(run func(w http.ResponseWriter, r *http.Request, data interface{})) *HttpHelper_EncodeJson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HttpHelper_EncodeJson_Call) Return() *HttpHelper_EncodeJson_Call {
	_c.Call.Return()
	return _c
}

func (_c *HttpHelper_EncodeJson_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, data interface{})) *HttpHelper_EncodeJson_Call {
	_c.Run(run)
	return _c
}

// GetFromUrlQueryOrFormPost provides a mock function for the type HttpHelper
func (_mock *HttpHelper) GetFromUrlQueryOrFormPost(r *http.Request, key string) string {
	ret := _mock.Called(r, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFromUrlQueryOrFormPost")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) string); ok {
		r0 = returnFunc(r, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HttpHelper_GetFromUrlQueryOrFormPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromUrlQueryOrFormPost'
type HttpHelper_GetFromUrlQueryOrFormPost_Call struct {
	*mock.Call
}

// GetFromUrlQueryOrFormPost is a helper method to define mock.On call
//   - r *http.Request
//   - key string
func (_e *HttpHelper_Expecter) GetFromUrlQueryOrFormPost(r interface{}, key interface{}) *HttpHelper_GetFromUrlQueryOrFormPost_Call {
	return &HttpHelper_GetFromUrlQueryOrFormPost_Call{Call: _e.mock.On("GetFromUrlQueryOrFormPost", r, key)}
}

func (_c *HttpHelper_GetFromUrlQueryOrFormPost_Call) Run(run func(r *http.Request, key string)) *HttpHelper_GetFromUrlQueryOrFormPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HttpHelper_GetFromUrlQueryOrFormPost_Call) Return(s string) *HttpHelper_GetFromUrlQueryOrFormPost_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HttpHelper_GetFromUrlQueryOrFormPost_Call) RunAndReturn(run func(r *http.Request, key string) string) *HttpHelper_GetFromUrlQueryOrFormPost_Call {
	_c.Call.Return(run)
	return _c
}

// InternalServerError provides a mock function for the type HttpHelper
func (_mock *HttpHelper) InternalServerError(w http.ResponseWriter, r *http.Request, err error) {
	_mock.Called(w, r, err)
	return
}

// HttpHelper_InternalServerError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalServerError'
type HttpHelper_InternalServerError_Call struct {
	*mock.Call
}

// InternalServerError is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *HttpHelper_Expecter) InternalServerError(w interface{}, r interface{}, err interface{}) *HttpHelper_InternalServerError_Call {
	return &HttpHelper_InternalServerError_Call{Call: _e.mock.On("InternalServerError", w, r, err)}
}

func (_c *HttpHelper_InternalServerError_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *HttpHelper_InternalServerError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HttpHelper_InternalServerError_Call) Return() *HttpHelper_InternalServerError_Call {
	_c.Call.Return()
	return _c
}

func (_c *HttpHelper_InternalServerError_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, err error)) *HttpHelper_InternalServerError_Call {
	_c.Run(run)
	return _c
}

// JsonError provides a mock function for the type HttpHelper
func (_mock *HttpHelper) JsonError(w http.ResponseWriter, r *http.Request, err error) {
	_mock.Called(w, r, err)
	return
}

// HttpHelper_JsonError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JsonError'
type HttpHelper_JsonError_Call struct {
	*mock.Call
}

// JsonError is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *HttpHelper_Expecter) JsonError(w interface{}, r interface{}, err interface{}) *HttpHelper_JsonError_Call {
	return &HttpHelper_JsonError_Call{Call: _e.mock.On("JsonError", w, r, err)}
}

func (_c *HttpHelper_JsonError_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *HttpHelper_JsonError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HttpHelper_JsonError_Call) Return() *HttpHelper_JsonError_Call {
	_c.Call.Return()
	return _c
}

func (_c *HttpHelper_JsonError_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, err error)) *HttpHelper_JsonError_Call {
	_c.Run(run)
	return _c
}

// RenderTemplate provides a mock function for the type HttpHelper
func (_mock *HttpHelper) RenderTemplate(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{}) error {
	ret := _mock.Called(w, r, layoutName, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for RenderTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string, string, map[string]interface{}) error); ok {
		r0 = returnFunc(w, r, layoutName, templateName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HttpHelper_RenderTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderTemplate'
type HttpHelper_RenderTemplate_Call struct {
	*mock.Call
}

// RenderTemplate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - layoutName string
//   - templateName string
//   - data map[string]interface{}
func (_e *HttpHelper_Expecter) RenderTemplate(w interface{}, r interface{}, layoutName interface{}, templateName interface{}, data interface{}) *HttpHelper_RenderTemplate_Call {
	return &HttpHelper_RenderTemplate_Call{Call: _e.mock.On("RenderTemplate", w, r, layoutName, templateName, data)}
}

func (_c *HttpHelper_RenderTemplate_Call) Run(run func(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{})) *HttpHelper_RenderTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *HttpHelper_RenderTemplate_Call) Return(err error) *HttpHelper_RenderTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HttpHelper_RenderTemplate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{}) error) *HttpHelper_RenderTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// RenderTemplateToBuffer provides a mock function for the type HttpHelper
func (_mock *HttpHelper) RenderTemplateToBuffer(r *http.Request, layoutName string, templateName string, data map[string]interface{}) (*bytes.Buffer, error) {
	ret := _mock.Called(r, layoutName, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for RenderTemplateToBuffer")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, string, map[string]interface{}) (*bytes.Buffer, error)); ok {
		return returnFunc(r, layoutName, templateName, data)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, string, map[string]interface{}) *bytes.Buffer); ok {
		r0 = returnFunc(r, layoutName, templateName, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string, string, map[string]interface{}) error); ok {
		r1 = returnFunc(r, layoutName, templateName, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HttpHelper_RenderTemplateToBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderTemplateToBuffer'
type HttpHelper_RenderTemplateToBuffer_Call struct {
	*mock.Call
}

// RenderTemplateToBuffer is a helper method to define mock.On call
//   - r *http.Request
//   - layoutName string
//   - templateName string
//   - data map[string]interface{}
func (_e *HttpHelper_Expecter) RenderTemplateToBuffer(r interface{}, layoutName interface{}, templateName interface{}, data interface{}) *HttpHelper_RenderTemplateToBuffer_Call {
	return &HttpHelper_RenderTemplateToBuffer_Call{Call: _e.mock.On("RenderTemplateToBuffer", r, layoutName, templateName, data)}
}

func (_c *HttpHelper_RenderTemplateToBuffer_Call) Run(run func(r *http.Request, layoutName string, templateName string, data map[string]interface{})) *HttpHelper_RenderTemplateToBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *HttpHelper_RenderTemplateToBuffer_Call) Return(buffer *bytes.Buffer, err error) *HttpHelper_RenderTemplateToBuffer_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *HttpHelper_RenderTemplateToBuffer_Call) RunAndReturn(run func(r *http.Request, layoutName string, templateName string, data map[string]interface{}) (*bytes.Buffer, error)) *HttpHelper_RenderTemplateToBuffer_Call {
	_c.Call.Return(run)
	return _c
}
