#!/bin/bash
VERSION="0.0.0"
BUILD_DATE=$(date +%Y-%m-%d)
GIT_COMMIT=$(git rev-parse --short HEAD)

echo "Version: $VERSION"
echo "Build date: $BUILD_DATE"
echo "Git commit: $GIT_COMMIT"

cd ../
docker build -f ./docker/Dockerfile -t leodip/goiabada:$VERSION --build-arg version=$VERSION --build-arg buildDate=$BUILD_DATE --build-arg gitCommit=$GIT_COMMIT --no-cache .
docker tag leodip/goiabada:$VERSION leodip/goiabada:latest
