FROM golang:1.21.6-bookworm AS buildStage

RUN apt-get update && apt-get install -y tzdata curl bash make

WORKDIR /app/src

# Tailwind CLI tool
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

COPY ./src/go.mod ./

RUN go mod download

COPY ./src ./

ENTRYPOINT ["/bin/bash", "-c" , "make $TEST_COMMAND"]