package constants

const (
	AdminConsoleClientIdentifier = "admin-console-client"

	AuthServerResourceIdentifier = "authserver"

	UserinfoPermissionIdentifier      = "userinfo"
	ManageAccountPermissionIdentifier = "manage-account"
	ManagePermissionIdentifier        = "manage"

	// Granular admin API scopes
	AdminReadPermissionIdentifier      = "admin-read"
	ManageUsersPermissionIdentifier    = "manage-users"
	ManageClientsPermissionIdentifier  = "manage-clients"
	ManageSettingsPermissionIdentifier = "manage-settings"

	// OIDC Authorization Error Codes (per OpenID Connect Core 1.0, Section 3.1.2.6)
	ErrorLoginRequired       = "login_required"
	ErrorConsentRequired     = "consent_required"
	ErrorInteractionRequired = "interaction_required"

	AuditAuthFailedPwd                        = "auth_failed_pwd"
	AuditAuthFailedOtp                        = "auth_failed_otp"
	AuditAuthSuccessPwd                       = "auth_success_pwd"
	AuditAuthSuccessOtp                       = "auth_success_otp"
	AuditUserDisabled                         = "user_disabled"
	AuditStartedNewUserSesson                 = "started_new_user_session"
	AuditBumpedUserSession                    = "bumped_user_session"
	AuditCreatedAuthCode                      = "created_auth_code"
	AuditSavedConsent                         = "saved_consent"
	AuditTokenIssuedAuthorizationCodeResponse = "token_issued_authorization_code_response"
	AuditTokenIssuedClientCredentialsResponse = "token_issued_client_credentials_response"
	AuditTokenIssuedRefreshTokenResponse      = "token_issued_refresh_token_response"
	// AuditTokenIssuedImplicitResponse is logged when tokens are issued via implicit flow.
	// SECURITY NOTE: Implicit flow is deprecated in OAuth 2.1.
	AuditTokenIssuedImplicitResponse = "token_issued_implicit_response"
	// AuditTokenIssuedROPCResponse is logged when tokens are issued via ROPC flow.
	// RFC 6749 Section 4.3
	// SECURITY NOTE: ROPC is deprecated in OAuth 2.1 due to credential exposure risks.
	AuditTokenIssuedROPCResponse = "token_issued_ropc_response"
	// AuditROPCAuthFailed is logged when ROPC authentication fails.
	// This includes invalid credentials, disabled users, and 2FA-blocked users.
	AuditROPCAuthFailed           = "ropc_auth_failed"
	AuditCreatedUser              = "created_user"
	AuditActivatedAccount         = "activated_account"
	AuditCreatedPreRegistration   = "created_pre_registration"
	AuditDeletedUserSessionClient = "deleted_user_session_client"
	AuditLogout                   = "logout"

	AuditRotatedKeys                    = "rotated_keys"
	AuditRevokedKey                     = "revoked_key"
	AuditDeletedUserSession             = "deleted_user_session"
	AuditUpdatedRedirectURIs            = "updated_redirect_uris"
	AuditUpdatedClientPermissions       = "updated_client_permissions"
	AuditDeletedClient                  = "deleted_client"
	AuditCreatedClient                  = "created_client"
	AuditDynamicClientRegistration      = "dynamic_client_registration"
	AuditUpdatedResourcePermissions     = "updated_resource_permissions"
	AuditDeletedResource                = "deleted_resource"
	AuditUpdatedResource                = "updated_resource"
	AuditCreatedResource                = "created_resource"
	AuditUserAddedToGroup               = "user_added_to_group"
	AuditUserRemovedFromGroup           = "user_removed_from_group"
	AuditCreatedGroup                   = "created_group"
	AuditUpdatedGroup                   = "updated_group"
	AuditDeletedGroup                   = "deleted_group"
	AuditDeleteGroupAttribute           = "deleted_group_attribute"
	AuditAddedGroupAttribute            = "added_group_attribute"
	AuditUpdatedGroupAttribute          = "updated_group_attribute"
	AuditAddedGroupPermission           = "added_group_permission"
	AuditDeletedGroupPermission         = "deleted_group_permission"
	AuditAddedUserPermission            = "added_user_permission"
	AuditDeletedUserPermission          = "deleted_user_permission"
	AuditDeleteUserAttribute            = "deleted_user_attribute"
	AuditAddedUserAttribute             = "added_user_attribute"
	AuditUpdatedUserAttribute           = "updated_user_attribute"
	AuditDeletedUser                    = "deleted_user"
	AuditUpdatedSMTPSettings            = "updated_smtp_settings"
	AuditUpdatedGeneralSettings         = "updated_general_settings"
	AuditUpdatedSessionsSettings        = "updated_sessions_settings"
	AuditUpdatedSMSSettings             = "updated_sms_settings"
	AuditUpdatedTokensSettings          = "updated_tokens_settings"
	AuditUpdatedUIThemeSettings         = "updated_ui_theme_settings"
	AuditUpdatedWebOrigins              = "updated_web_origins"
	AuditUpdatedClientSettings          = "updated_client_settings"
	AuditUpdatedClientTokens            = "updated_client_tokens"
	AuditUpdatedClientAuthentication    = "updated_client_authentication"
	AuditUpdatedClientOAuth2Flows       = "updated_client_oauth2_flows"
	AuditUpdatedUserDetails             = "updated_user_details"
	AuditUpdatedUserProfile             = "updated_user_profile"
	AuditUpdatedOwnProfile              = "updated_own_profile"
	AuditUpdatedOwnEmail                = "updated_own_email"
	AuditUpdatedOwnPhone                = "updated_own_phone"
	AuditUpdatedOwnAddress              = "updated_own_address"
	AuditUpdatedUserEmail               = "updated_user_email"
	AuditUpdatedUserPhone               = "updated_user_phone"
	AuditUpdatedUserAddress             = "updated_user_address"
	AuditUpdatedUserAuthentication      = "updated_user_authentication"
	AuditDeletedUserConsent             = "deleted_user_consent"
	AuditDeletedOwnUserConsent          = "deleted_own_user_consent"
	AuditVerifiedEmail                  = "verified_email"
	AuditSentEmailVerificationMessage   = "sent_email_verification_message"
	AuditFailedEmailVerificationCode    = "failed_email_verification_code"
	AuditVerifiedPhone                  = "verified_phone"
	AuditSentPhoneVerificationMessage   = "sent_phone_verification_message"
	AuditChangedPassword                = "changed_password"
	AuditEnabledOTP                     = "enabled_otp"
	AuditDisabledOTP                    = "disabled_otp"
	AuditAutoRefreshedToken             = "auto_refreshed_token"
	AuditSentTestEmail                  = "sent_test_email"
	AuditUpdatedUserProfilePicture      = "updated_user_profile_picture"
	AuditDeletedUserProfilePicture      = "deleted_user_profile_picture"
	AuditUpdatedOwnProfilePicture       = "updated_own_profile_picture"
	AuditDeletedOwnProfilePicture       = "deleted_own_profile_picture"
	AuditGeneratedEmailVerificationCode = "generated_email_verification_code"
)
