// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_middleware

import (
	"context"

	"github.com/leodip/goiabada/adminconsole/internal/oauthclient"
	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenParser creates a new instance of TokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TokenParser is an autogenerated mock type for the tokenParser type
type TokenParser struct {
	mock.Mock
}

type TokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenParser) EXPECT() *TokenParser_Expecter {
	return &TokenParser_Expecter{mock: &_m.Mock}
}

// DecodeAndValidateRefreshResponse provides a mock function for the type TokenParser
func (_mock *TokenParser) DecodeAndValidateRefreshResponse(ctx context.Context, tokenResponse *oauth.TokenResponse, previous *oauth.JwtToken) (*oauthclient.JwtInfo, error) {
	ret := _mock.Called(ctx, tokenResponse, previous)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateRefreshResponse")
	}

	var r0 *oauthclient.JwtInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth.TokenResponse, *oauth.JwtToken) (*oauthclient.JwtInfo, error)); ok {
		return returnFunc(ctx, tokenResponse, previous)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth.TokenResponse, *oauth.JwtToken) *oauthclient.JwtInfo); ok {
		r0 = returnFunc(ctx, tokenResponse, previous)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauthclient.JwtInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *oauth.TokenResponse, *oauth.JwtToken) error); ok {
		r1 = returnFunc(ctx, tokenResponse, previous)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenParser_DecodeAndValidateRefreshResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeAndValidateRefreshResponse'
type TokenParser_DecodeAndValidateRefreshResponse_Call struct {
	*mock.Call
}

// DecodeAndValidateRefreshResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenResponse *oauth.TokenResponse
//   - previous *oauth.JwtToken
func (_e *TokenParser_Expecter) DecodeAndValidateRefreshResponse(ctx any, tokenResponse any, previous any) *TokenParser_DecodeAndValidateRefreshResponse_Call {
	return &TokenParser_DecodeAndValidateRefreshResponse_Call{Call: _e.mock.On("DecodeAndValidateRefreshResponse", ctx, tokenResponse, previous)}
}

func (_c *TokenParser_DecodeAndValidateRefreshResponse_Call) Run(run func(ctx context.Context, tokenResponse *oauth.TokenResponse, previous *oauth.JwtToken)) *TokenParser_DecodeAndValidateRefreshResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *oauth.TokenResponse
		if args[1] != nil {
			arg1 = args[1].(*oauth.TokenResponse)
		}
		var arg2 *oauth.JwtToken
		if args[2] != nil {
			arg2 = args[2].(*oauth.JwtToken)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenParser_DecodeAndValidateRefreshResponse_Call) Return(jwtInfo *oauthclient.JwtInfo, err error) *TokenParser_DecodeAndValidateRefreshResponse_Call {
	_c.Call.Return(jwtInfo, err)
	return _c
}

func (_c *TokenParser_DecodeAndValidateRefreshResponse_Call) RunAndReturn(run func(ctx context.Context, tokenResponse *oauth.TokenResponse, previous *oauth.JwtToken) (*oauthclient.JwtInfo, error)) *TokenParser_DecodeAndValidateRefreshResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeAndValidateStoredIDToken provides a mock function for the type TokenParser
func (_mock *TokenParser) DecodeAndValidateStoredIDToken(ctx context.Context, raw string) (*oauth.JwtToken, error) {
	ret := _mock.Called(ctx, raw)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateStoredIDToken")
	}

	var r0 *oauth.JwtToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oauth.JwtToken, error)); ok {
		return returnFunc(ctx, raw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oauth.JwtToken); ok {
		r0 = returnFunc(ctx, raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenParser_DecodeAndValidateStoredIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeAndValidateStoredIDToken'
type TokenParser_DecodeAndValidateStoredIDToken_Call struct {
	*mock.Call
}

// DecodeAndValidateStoredIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - raw string
func (_e *TokenParser_Expecter) DecodeAndValidateStoredIDToken(ctx any, raw any) *TokenParser_DecodeAndValidateStoredIDToken_Call {
	return &TokenParser_DecodeAndValidateStoredIDToken_Call{Call: _e.mock.On("DecodeAndValidateStoredIDToken", ctx, raw)}
}

func (_c *TokenParser_DecodeAndValidateStoredIDToken_Call) Run(run func(ctx context.Context, raw string)) *TokenParser_DecodeAndValidateStoredIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenParser_DecodeAndValidateStoredIDToken_Call) Return(jwtToken *oauth.JwtToken, err error) *TokenParser_DecodeAndValidateStoredIDToken_Call {
	_c.Call.Return(jwtToken, err)
	return _c
}

func (_c *TokenParser_DecodeAndValidateStoredIDToken_Call) RunAndReturn(run func(ctx context.Context, raw string) (*oauth.JwtToken, error)) *TokenParser_DecodeAndValidateStoredIDToken_Call {
	_c.Call.Return(run)
	return _c
}
