// Package timezones is the vocabulary a user's time zone is picked from: the OIDC `zoneinfo` claim,
// which OIDC Core 1.0 section 5.1 defines as a name from the IANA Time Zone Database.
//
// The table in data_generated.go is generated by generate/main.go from tzdata's zone1970.tab and
// iso3166.tab at the release that file pins. One zone ID can serve several countries --
// Europe/Berlin is listed under Germany and under Sweden, among others -- so a row is a (country,
// zone) pair, and that pair is what the profile picker posts and a profile stores.
//
// Nothing here loads a location at startup, so a zone missing from a host's zoneinfo cannot stop
// a server (#49); a test checks that every row loads, with the embedded fallback both binaries
// import (#432).
package timezones

import "slices"

// Zone is one row of the picker: a zone as tzdata lists it under one country.
type Zone struct {
	// CountryCode is the upper-case ISO 3166-1 alpha-2 code, e.g. "BR".
	CountryCode string
	// Zone is the IANA zone ID stored on the user and emitted as the zoneinfo claim, e.g.
	// "America/Sao_Paulo".
	Zone string
	// CountryName is tzdata's English name for the country, from iso3166.tab, e.g. "Brazil". It is
	// stored beside the zone as the picker's row identity, so it must keep coming from
	// iso3166.tab: a name taken from anywhere else would stop matching the pairs profiles already
	// hold, and those profiles would reopen on the blank option (#432).
	CountryName string
	// Comments is zone1970.tab's English description of the region the zone covers within the
	// country, and empty for a country with one row, for which tzdata says it is not meant (#432).
	Comments string
}

// byZone indexes the table by zone ID, each entry the positions of that zone's rows in table order.
// It is built once at package initialization; Go orders package-level initialization by dependency,
// so `zones` is populated first.
var byZone = indexByZone(zones)

func indexByZone(list []Zone) map[string][]int {
	index := make(map[string][]int)
	for i, z := range list {
		index[z.Zone] = append(index[z.Zone], i)
	}
	return index
}

// All returns every row, sorted by country name and then zone ID, the order the picker renders
// them in. It returns a fresh slice on every call, so callers may sort or otherwise mutate it
// without affecting the package's data or other callers.
func All() []Zone {
	return slices.Clone(zones)
}

// ByZone returns every row listing the zone ID, in table order, as a fresh slice; nil when no row
// does. The match is exact: case is not normalized.
func ByZone(zone string) []Zone {
	positions := byZone[zone]
	if len(positions) == 0 {
		return nil
	}
	out := make([]Zone, len(positions))
	for i, p := range positions {
		out[i] = zones[p]
	}
	return out
}
