//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_otp

import (
	mock "github.com/stretchr/testify/mock"
)

// NewOtpSecretGenerator creates a new instance of OtpSecretGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOtpSecretGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *OtpSecretGenerator {
	mock := &OtpSecretGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OtpSecretGenerator is an autogenerated mock type for the OtpSecretGenerator type
type OtpSecretGenerator struct {
	mock.Mock
}

type OtpSecretGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *OtpSecretGenerator) EXPECT() *OtpSecretGenerator_Expecter {
	return &OtpSecretGenerator_Expecter{mock: &_m.Mock}
}

// GenerateOTPSecret provides a mock function for the type OtpSecretGenerator
func (_mock *OtpSecretGenerator) GenerateOTPSecret(email string, appName string) (string, string, error) {
	ret := _mock.Called(email, appName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTPSecret")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, string, error)); ok {
		return returnFunc(email, appName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(email, appName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = returnFunc(email, appName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(email, appName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OtpSecretGenerator_GenerateOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTPSecret'
type OtpSecretGenerator_GenerateOTPSecret_Call struct {
	*mock.Call
}

// GenerateOTPSecret is a helper method to define mock.On call
//   - email string
//   - appName string
func (_e *OtpSecretGenerator_Expecter) GenerateOTPSecret(email interface{}, appName interface{}) *OtpSecretGenerator_GenerateOTPSecret_Call {
	return &OtpSecretGenerator_GenerateOTPSecret_Call{Call: _e.mock.On("GenerateOTPSecret", email, appName)}
}

func (_c *OtpSecretGenerator_GenerateOTPSecret_Call) Run(run func(email string, appName string)) *OtpSecretGenerator_GenerateOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OtpSecretGenerator_GenerateOTPSecret_Call) Return(s string, s1 string, err error) *OtpSecretGenerator_GenerateOTPSecret_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *OtpSecretGenerator_GenerateOTPSecret_Call) RunAndReturn(run func(email string, appName string) (string, string, error)) *OtpSecretGenerator_GenerateOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
