// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_middleware

import (
	"context"

	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenParser creates a new instance of TokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TokenParser is an autogenerated mock type for the tokenParser type
type TokenParser struct {
	mock.Mock
}

type TokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenParser) EXPECT() *TokenParser_Expecter {
	return &TokenParser_Expecter{mock: &_m.Mock}
}

// DecodeAndValidateTokenString provides a mock function for the type TokenParser
func (_mock *TokenParser) DecodeAndValidateTokenString(ctx context.Context, token string, withExpirationCheck bool) (*oauth.JwtToken, error) {
	ret := _mock.Called(ctx, token, withExpirationCheck)

	if len(ret) == 0 {
		panic("no return value specified for DecodeAndValidateTokenString")
	}

	var r0 *oauth.JwtToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*oauth.JwtToken, error)); ok {
		return returnFunc(ctx, token, withExpirationCheck)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *oauth.JwtToken); ok {
		r0 = returnFunc(ctx, token, withExpirationCheck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.JwtToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, token, withExpirationCheck)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenParser_DecodeAndValidateTokenString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeAndValidateTokenString'
type TokenParser_DecodeAndValidateTokenString_Call struct {
	*mock.Call
}

// DecodeAndValidateTokenString is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - withExpirationCheck bool
func (_e *TokenParser_Expecter) DecodeAndValidateTokenString(ctx any, token any, withExpirationCheck any) *TokenParser_DecodeAndValidateTokenString_Call {
	return &TokenParser_DecodeAndValidateTokenString_Call{Call: _e.mock.On("DecodeAndValidateTokenString", ctx, token, withExpirationCheck)}
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) Run(run func(ctx context.Context, token string, withExpirationCheck bool)) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) Return(jwtToken *oauth.JwtToken, err error) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Return(jwtToken, err)
	return _c
}

func (_c *TokenParser_DecodeAndValidateTokenString_Call) RunAndReturn(run func(ctx context.Context, token string, withExpirationCheck bool) (*oauth.JwtToken, error)) *TokenParser_DecodeAndValidateTokenString_Call {
	_c.Call.Return(run)
	return _c
}
