//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_validator

import (
	"github.com/leodip/goiabada/core/validators"
	mock "github.com/stretchr/testify/mock"
)

// NewAddressValidator creates a new instance of AddressValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressValidator {
	mock := &AddressValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AddressValidator is an autogenerated mock type for the AddressValidator type
type AddressValidator struct {
	mock.Mock
}

type AddressValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *AddressValidator) EXPECT() *AddressValidator_Expecter {
	return &AddressValidator_Expecter{mock: &_m.Mock}
}

// ValidateAddress provides a mock function for the type AddressValidator
func (_mock *AddressValidator) ValidateAddress(input *validators.ValidateAddressInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAddress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*validators.ValidateAddressInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressValidator_ValidateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAddress'
type AddressValidator_ValidateAddress_Call struct {
	*mock.Call
}

// ValidateAddress is a helper method to define mock.On call
//   - input *validators.ValidateAddressInput
func (_e *AddressValidator_Expecter) ValidateAddress(input interface{}) *AddressValidator_ValidateAddress_Call {
	return &AddressValidator_ValidateAddress_Call{Call: _e.mock.On("ValidateAddress", input)}
}

func (_c *AddressValidator_ValidateAddress_Call) Run(run func(input *validators.ValidateAddressInput)) *AddressValidator_ValidateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *validators.ValidateAddressInput
		if args[0] != nil {
			arg0 = args[0].(*validators.ValidateAddressInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AddressValidator_ValidateAddress_Call) Return(err error) *AddressValidator_ValidateAddress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressValidator_ValidateAddress_Call) RunAndReturn(run func(input *validators.ValidateAddressInput) error) *AddressValidator_ValidateAddress_Call {
	_c.Call.Return(run)
	return _c
}
