//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_validator

import (
	"github.com/leodip/goiabada/core/validators"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizeValidator creates a new instance of AuthorizeValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeValidator {
	mock := &AuthorizeValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizeValidator is an autogenerated mock type for the AuthorizeValidator type
type AuthorizeValidator struct {
	mock.Mock
}

type AuthorizeValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizeValidator) EXPECT() *AuthorizeValidator_Expecter {
	return &AuthorizeValidator_Expecter{mock: &_m.Mock}
}

// ValidateClientAndRedirectURI provides a mock function for the type AuthorizeValidator
func (_mock *AuthorizeValidator) ValidateClientAndRedirectURI(input *validators.ValidateClientAndRedirectURIInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClientAndRedirectURI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*validators.ValidateClientAndRedirectURIInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizeValidator_ValidateClientAndRedirectURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClientAndRedirectURI'
type AuthorizeValidator_ValidateClientAndRedirectURI_Call struct {
	*mock.Call
}

// ValidateClientAndRedirectURI is a helper method to define mock.On call
//   - input *validators.ValidateClientAndRedirectURIInput
func (_e *AuthorizeValidator_Expecter) ValidateClientAndRedirectURI(input interface{}) *AuthorizeValidator_ValidateClientAndRedirectURI_Call {
	return &AuthorizeValidator_ValidateClientAndRedirectURI_Call{Call: _e.mock.On("ValidateClientAndRedirectURI", input)}
}

func (_c *AuthorizeValidator_ValidateClientAndRedirectURI_Call) Run(run func(input *validators.ValidateClientAndRedirectURIInput)) *AuthorizeValidator_ValidateClientAndRedirectURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *validators.ValidateClientAndRedirectURIInput
		if args[0] != nil {
			arg0 = args[0].(*validators.ValidateClientAndRedirectURIInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthorizeValidator_ValidateClientAndRedirectURI_Call) Return(err error) *AuthorizeValidator_ValidateClientAndRedirectURI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizeValidator_ValidateClientAndRedirectURI_Call) RunAndReturn(run func(input *validators.ValidateClientAndRedirectURIInput) error) *AuthorizeValidator_ValidateClientAndRedirectURI_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePrompt provides a mock function for the type AuthorizeValidator
func (_mock *AuthorizeValidator) ValidatePrompt(prompt string) (string, error) {
	ret := _mock.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizeValidator_ValidatePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePrompt'
type AuthorizeValidator_ValidatePrompt_Call struct {
	*mock.Call
}

// ValidatePrompt is a helper method to define mock.On call
//   - prompt string
func (_e *AuthorizeValidator_Expecter) ValidatePrompt(prompt interface{}) *AuthorizeValidator_ValidatePrompt_Call {
	return &AuthorizeValidator_ValidatePrompt_Call{Call: _e.mock.On("ValidatePrompt", prompt)}
}

func (_c *AuthorizeValidator_ValidatePrompt_Call) Run(run func(prompt string)) *AuthorizeValidator_ValidatePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthorizeValidator_ValidatePrompt_Call) Return(s string, err error) *AuthorizeValidator_ValidatePrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthorizeValidator_ValidatePrompt_Call) RunAndReturn(run func(prompt string) (string, error)) *AuthorizeValidator_ValidatePrompt_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRequest provides a mock function for the type AuthorizeValidator
func (_mock *AuthorizeValidator) ValidateRequest(input *validators.ValidateRequestInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*validators.ValidateRequestInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizeValidator_ValidateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRequest'
type AuthorizeValidator_ValidateRequest_Call struct {
	*mock.Call
}

// ValidateRequest is a helper method to define mock.On call
//   - input *validators.ValidateRequestInput
func (_e *AuthorizeValidator_Expecter) ValidateRequest(input interface{}) *AuthorizeValidator_ValidateRequest_Call {
	return &AuthorizeValidator_ValidateRequest_Call{Call: _e.mock.On("ValidateRequest", input)}
}

func (_c *AuthorizeValidator_ValidateRequest_Call) Run(run func(input *validators.ValidateRequestInput)) *AuthorizeValidator_ValidateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *validators.ValidateRequestInput
		if args[0] != nil {
			arg0 = args[0].(*validators.ValidateRequestInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthorizeValidator_ValidateRequest_Call) Return(err error) *AuthorizeValidator_ValidateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizeValidator_ValidateRequest_Call) RunAndReturn(run func(input *validators.ValidateRequestInput) error) *AuthorizeValidator_ValidateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateScopes provides a mock function for the type AuthorizeValidator
func (_mock *AuthorizeValidator) ValidateScopes(scope string) error {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for ValidateScopes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(scope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizeValidator_ValidateScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateScopes'
type AuthorizeValidator_ValidateScopes_Call struct {
	*mock.Call
}

// ValidateScopes is a helper method to define mock.On call
//   - scope string
func (_e *AuthorizeValidator_Expecter) ValidateScopes(scope interface{}) *AuthorizeValidator_ValidateScopes_Call {
	return &AuthorizeValidator_ValidateScopes_Call{Call: _e.mock.On("ValidateScopes", scope)}
}

func (_c *AuthorizeValidator_ValidateScopes_Call) Run(run func(scope string)) *AuthorizeValidator_ValidateScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthorizeValidator_ValidateScopes_Call) Return(err error) *AuthorizeValidator_ValidateScopes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizeValidator_ValidateScopes_Call) RunAndReturn(run func(scope string) error) *AuthorizeValidator_ValidateScopes_Call {
	_c.Call.Return(run)
	return _c
}
