//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_validator

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewPasswordValidator creates a new instance of PasswordValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordValidator {
	mock := &PasswordValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordValidator is an autogenerated mock type for the PasswordValidator type
type PasswordValidator struct {
	mock.Mock
}

type PasswordValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordValidator) EXPECT() *PasswordValidator_Expecter {
	return &PasswordValidator_Expecter{mock: &_m.Mock}
}

// ValidatePassword provides a mock function for the type PasswordValidator
func (_mock *PasswordValidator) ValidatePassword(ctx context.Context, password string) error {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordValidator_ValidatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePassword'
type PasswordValidator_ValidatePassword_Call struct {
	*mock.Call
}

// ValidatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *PasswordValidator_Expecter) ValidatePassword(ctx interface{}, password interface{}) *PasswordValidator_ValidatePassword_Call {
	return &PasswordValidator_ValidatePassword_Call{Call: _e.mock.On("ValidatePassword", ctx, password)}
}

func (_c *PasswordValidator_ValidatePassword_Call) Run(run func(ctx context.Context, password string)) *PasswordValidator_ValidatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordValidator_ValidatePassword_Call) Return(err error) *PasswordValidator_ValidatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordValidator_ValidatePassword_Call) RunAndReturn(run func(ctx context.Context, password string) error) *PasswordValidator_ValidatePassword_Call {
	_c.Call.Return(run)
	return _c
}
