//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_validator

import (
	"github.com/leodip/goiabada/core/validators"
	mock "github.com/stretchr/testify/mock"
)

// NewPhoneValidator creates a new instance of PhoneValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPhoneValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PhoneValidator {
	mock := &PhoneValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PhoneValidator is an autogenerated mock type for the PhoneValidator type
type PhoneValidator struct {
	mock.Mock
}

type PhoneValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *PhoneValidator) EXPECT() *PhoneValidator_Expecter {
	return &PhoneValidator_Expecter{mock: &_m.Mock}
}

// ValidatePhone provides a mock function for the type PhoneValidator
func (_mock *PhoneValidator) ValidatePhone(input *validators.ValidatePhoneInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePhone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*validators.ValidatePhoneInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PhoneValidator_ValidatePhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePhone'
type PhoneValidator_ValidatePhone_Call struct {
	*mock.Call
}

// ValidatePhone is a helper method to define mock.On call
//   - input *validators.ValidatePhoneInput
func (_e *PhoneValidator_Expecter) ValidatePhone(input interface{}) *PhoneValidator_ValidatePhone_Call {
	return &PhoneValidator_ValidatePhone_Call{Call: _e.mock.On("ValidatePhone", input)}
}

func (_c *PhoneValidator_ValidatePhone_Call) Run(run func(input *validators.ValidatePhoneInput)) *PhoneValidator_ValidatePhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *validators.ValidatePhoneInput
		if args[0] != nil {
			arg0 = args[0].(*validators.ValidatePhoneInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PhoneValidator_ValidatePhone_Call) Return(err error) *PhoneValidator_ValidatePhone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PhoneValidator_ValidatePhone_Call) RunAndReturn(run func(input *validators.ValidatePhoneInput) error) *PhoneValidator_ValidatePhone_Call {
	_c.Call.Return(run)
	return _c
}
