//go:build !production

// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks_validator

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	validators "github.com/leodip/goiabada/core/validators"
)

// ProfileValidator is an autogenerated mock type for the ProfileValidator type
type ProfileValidator struct {
	mock.Mock
}

// ValidateName provides a mock function with given fields: ctx, name, nameField
func (_m *ProfileValidator) ValidateName(ctx context.Context, name string, nameField string) error {
	ret := _m.Called(ctx, name, nameField)

	if len(ret) == 0 {
		panic("no return value specified for ValidateName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, nameField)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateProfile provides a mock function with given fields: ctx, input
func (_m *ProfileValidator) ValidateProfile(ctx context.Context, input *validators.ValidateProfileInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *validators.ValidateProfileInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProfileValidator creates a new instance of ProfileValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileValidator {
	mock := &ProfileValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
