//go:build !production

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_validator

import (
	"github.com/leodip/goiabada/core/validators"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileValidator creates a new instance of ProfileValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileValidator {
	mock := &ProfileValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileValidator is an autogenerated mock type for the ProfileValidator type
type ProfileValidator struct {
	mock.Mock
}

type ProfileValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileValidator) EXPECT() *ProfileValidator_Expecter {
	return &ProfileValidator_Expecter{mock: &_m.Mock}
}

// ValidateName provides a mock function for the type ProfileValidator
func (_mock *ProfileValidator) ValidateName(name string, nameField string) error {
	ret := _mock.Called(name, nameField)

	if len(ret) == 0 {
		panic("no return value specified for ValidateName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, nameField)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileValidator_ValidateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateName'
type ProfileValidator_ValidateName_Call struct {
	*mock.Call
}

// ValidateName is a helper method to define mock.On call
//   - name string
//   - nameField string
func (_e *ProfileValidator_Expecter) ValidateName(name interface{}, nameField interface{}) *ProfileValidator_ValidateName_Call {
	return &ProfileValidator_ValidateName_Call{Call: _e.mock.On("ValidateName", name, nameField)}
}

func (_c *ProfileValidator_ValidateName_Call) Run(run func(name string, nameField string)) *ProfileValidator_ValidateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileValidator_ValidateName_Call) Return(err error) *ProfileValidator_ValidateName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileValidator_ValidateName_Call) RunAndReturn(run func(name string, nameField string) error) *ProfileValidator_ValidateName_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateProfile provides a mock function for the type ProfileValidator
func (_mock *ProfileValidator) ValidateProfile(input *validators.ValidateProfileInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*validators.ValidateProfileInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileValidator_ValidateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateProfile'
type ProfileValidator_ValidateProfile_Call struct {
	*mock.Call
}

// ValidateProfile is a helper method to define mock.On call
//   - input *validators.ValidateProfileInput
func (_e *ProfileValidator_Expecter) ValidateProfile(input interface{}) *ProfileValidator_ValidateProfile_Call {
	return &ProfileValidator_ValidateProfile_Call{Call: _e.mock.On("ValidateProfile", input)}
}

func (_c *ProfileValidator_ValidateProfile_Call) Run(run func(input *validators.ValidateProfileInput)) *ProfileValidator_ValidateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *validators.ValidateProfileInput
		if args[0] != nil {
			arg0 = args[0].(*validators.ValidateProfileInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProfileValidator_ValidateProfile_Call) Return(err error) *ProfileValidator_ValidateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileValidator_ValidateProfile_Call) RunAndReturn(run func(input *validators.ValidateProfileInput) error) *ProfileValidator_ValidateProfile_Call {
	_c.Call.Return(run)
	return _c
}
