// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_handlers

import (
	"net/http"

	"github.com/leodip/goiabada/authserver/internal/ceremony"
	mock "github.com/stretchr/testify/mock"
)

// NewCeremonyStore creates a new instance of CeremonyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCeremonyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CeremonyStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CeremonyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CeremonyStore is an autogenerated mock type for the CeremonyStore type
type CeremonyStore struct {
	mock.Mock
}

type CeremonyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CeremonyStore) EXPECT() *CeremonyStore_Expecter {
	return &CeremonyStore_Expecter{mock: &_m.Mock}
}

// ClearAuthContext provides a mock function for the type CeremonyStore
func (_mock *CeremonyStore) ClearAuthContext(w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for ClearAuthContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CeremonyStore_ClearAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAuthContext'
type CeremonyStore_ClearAuthContext_Call struct {
	*mock.Call
}

// ClearAuthContext is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CeremonyStore_Expecter) ClearAuthContext(w any, r any) *CeremonyStore_ClearAuthContext_Call {
	return &CeremonyStore_ClearAuthContext_Call{Call: _e.mock.On("ClearAuthContext", w, r)}
}

func (_c *CeremonyStore_ClearAuthContext_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CeremonyStore_ClearAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CeremonyStore_ClearAuthContext_Call) Return(err error) *CeremonyStore_ClearAuthContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CeremonyStore_ClearAuthContext_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) error) *CeremonyStore_ClearAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthContext provides a mock function for the type CeremonyStore
func (_mock *CeremonyStore) GetAuthContext(r *http.Request) (*ceremony.AuthContext, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthContext")
	}

	var r0 *ceremony.AuthContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*ceremony.AuthContext, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *ceremony.AuthContext); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ceremony.AuthContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CeremonyStore_GetAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthContext'
type CeremonyStore_GetAuthContext_Call struct {
	*mock.Call
}

// GetAuthContext is a helper method to define mock.On call
//   - r *http.Request
func (_e *CeremonyStore_Expecter) GetAuthContext(r any) *CeremonyStore_GetAuthContext_Call {
	return &CeremonyStore_GetAuthContext_Call{Call: _e.mock.On("GetAuthContext", r)}
}

func (_c *CeremonyStore_GetAuthContext_Call) Run(run func(r *http.Request)) *CeremonyStore_GetAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CeremonyStore_GetAuthContext_Call) Return(authContext *ceremony.AuthContext, err error) *CeremonyStore_GetAuthContext_Call {
	_c.Call.Return(authContext, err)
	return _c
}

func (_c *CeremonyStore_GetAuthContext_Call) RunAndReturn(run func(r *http.Request) (*ceremony.AuthContext, error)) *CeremonyStore_GetAuthContext_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateSession provides a mock function for the type CeremonyStore
func (_mock *CeremonyStore) RegenerateSession(w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CeremonyStore_RegenerateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateSession'
type CeremonyStore_RegenerateSession_Call struct {
	*mock.Call
}

// RegenerateSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CeremonyStore_Expecter) RegenerateSession(w any, r any) *CeremonyStore_RegenerateSession_Call {
	return &CeremonyStore_RegenerateSession_Call{Call: _e.mock.On("RegenerateSession", w, r)}
}

func (_c *CeremonyStore_RegenerateSession_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CeremonyStore_RegenerateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CeremonyStore_RegenerateSession_Call) Return(err error) *CeremonyStore_RegenerateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CeremonyStore_RegenerateSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) error) *CeremonyStore_RegenerateSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAuthContext provides a mock function for the type CeremonyStore
func (_mock *CeremonyStore) SaveAuthContext(w http.ResponseWriter, r *http.Request, authContext *ceremony.AuthContext) error {
	ret := _mock.Called(w, r, authContext)

	if len(ret) == 0 {
		panic("no return value specified for SaveAuthContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, *ceremony.AuthContext) error); ok {
		r0 = returnFunc(w, r, authContext)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CeremonyStore_SaveAuthContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAuthContext'
type CeremonyStore_SaveAuthContext_Call struct {
	*mock.Call
}

// SaveAuthContext is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - authContext *ceremony.AuthContext
func (_e *CeremonyStore_Expecter) SaveAuthContext(w any, r any, authContext any) *CeremonyStore_SaveAuthContext_Call {
	return &CeremonyStore_SaveAuthContext_Call{Call: _e.mock.On("SaveAuthContext", w, r, authContext)}
}

func (_c *CeremonyStore_SaveAuthContext_Call) Run(run func(w http.ResponseWriter, r *http.Request, authContext *ceremony.AuthContext)) *CeremonyStore_SaveAuthContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 *ceremony.AuthContext
		if args[2] != nil {
			arg2 = args[2].(*ceremony.AuthContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CeremonyStore_SaveAuthContext_Call) Return(err error) *CeremonyStore_SaveAuthContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CeremonyStore_SaveAuthContext_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, authContext *ceremony.AuthContext) error) *CeremonyStore_SaveAuthContext_Call {
	_c.Call.Return(run)
	return _c
}
