// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package handlersmocks

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/issuance"
	"github.com/leodip/goiabada/authserver/internal/record"
	mock "github.com/stretchr/testify/mock"
)

// NewCodeIssuer creates a new instance of CodeIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeIssuer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CodeIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CodeIssuer is an autogenerated mock type for the CodeIssuer type
type CodeIssuer struct {
	mock.Mock
}

type CodeIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeIssuer) EXPECT() *CodeIssuer_Expecter {
	return &CodeIssuer_Expecter{mock: &_m.Mock}
}

// IssueAuthCodeTx provides a mock function for the type CodeIssuer
func (_mock *CodeIssuer) IssueAuthCodeTx(ctx context.Context, input *issuance.CreateCodeInput) (*record.Code, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for IssueAuthCodeTx")
	}

	var r0 *record.Code
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *issuance.CreateCodeInput) (*record.Code, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *issuance.CreateCodeInput) *record.Code); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.Code)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *issuance.CreateCodeInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CodeIssuer_IssueAuthCodeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAuthCodeTx'
type CodeIssuer_IssueAuthCodeTx_Call struct {
	*mock.Call
}

// IssueAuthCodeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - input *issuance.CreateCodeInput
func (_e *CodeIssuer_Expecter) IssueAuthCodeTx(ctx any, input any) *CodeIssuer_IssueAuthCodeTx_Call {
	return &CodeIssuer_IssueAuthCodeTx_Call{Call: _e.mock.On("IssueAuthCodeTx", ctx, input)}
}

func (_c *CodeIssuer_IssueAuthCodeTx_Call) Run(run func(ctx context.Context, input *issuance.CreateCodeInput)) *CodeIssuer_IssueAuthCodeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *issuance.CreateCodeInput
		if args[1] != nil {
			arg1 = args[1].(*issuance.CreateCodeInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeIssuer_IssueAuthCodeTx_Call) Return(code *record.Code, err error) *CodeIssuer_IssueAuthCodeTx_Call {
	_c.Call.Return(code, err)
	return _c
}

func (_c *CodeIssuer_IssueAuthCodeTx_Call) RunAndReturn(run func(ctx context.Context, input *issuance.CreateCodeInput) (*record.Code, error)) *CodeIssuer_IssueAuthCodeTx_Call {
	_c.Call.Return(run)
	return _c
}
