// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package handlersmocks

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/issuance"
	"github.com/leodip/goiabada/authserver/internal/record"
	mock "github.com/stretchr/testify/mock"
)

// NewImplicitTokenIssuer creates a new instance of ImplicitTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImplicitTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImplicitTokenIssuer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ImplicitTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ImplicitTokenIssuer is an autogenerated mock type for the ImplicitTokenIssuer type
type ImplicitTokenIssuer struct {
	mock.Mock
}

type ImplicitTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *ImplicitTokenIssuer) EXPECT() *ImplicitTokenIssuer_Expecter {
	return &ImplicitTokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueImplicitTx provides a mock function for the type ImplicitTokenIssuer
func (_mock *ImplicitTokenIssuer) IssueImplicitTx(ctx context.Context, settings *record.Settings, input *issuance.ImplicitGrantInput, issueAccessToken bool, issueIdToken bool) (*issuance.ImplicitGrantResponse, error) {
	ret := _mock.Called(ctx, settings, input, issueAccessToken, issueIdToken)

	if len(ret) == 0 {
		panic("no return value specified for IssueImplicitTx")
	}

	var r0 *issuance.ImplicitGrantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *record.Settings, *issuance.ImplicitGrantInput, bool, bool) (*issuance.ImplicitGrantResponse, error)); ok {
		return returnFunc(ctx, settings, input, issueAccessToken, issueIdToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *record.Settings, *issuance.ImplicitGrantInput, bool, bool) *issuance.ImplicitGrantResponse); ok {
		r0 = returnFunc(ctx, settings, input, issueAccessToken, issueIdToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*issuance.ImplicitGrantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *record.Settings, *issuance.ImplicitGrantInput, bool, bool) error); ok {
		r1 = returnFunc(ctx, settings, input, issueAccessToken, issueIdToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImplicitTokenIssuer_IssueImplicitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueImplicitTx'
type ImplicitTokenIssuer_IssueImplicitTx_Call struct {
	*mock.Call
}

// IssueImplicitTx is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *record.Settings
//   - input *issuance.ImplicitGrantInput
//   - issueAccessToken bool
//   - issueIdToken bool
func (_e *ImplicitTokenIssuer_Expecter) IssueImplicitTx(ctx any, settings any, input any, issueAccessToken any, issueIdToken any) *ImplicitTokenIssuer_IssueImplicitTx_Call {
	return &ImplicitTokenIssuer_IssueImplicitTx_Call{Call: _e.mock.On("IssueImplicitTx", ctx, settings, input, issueAccessToken, issueIdToken)}
}

func (_c *ImplicitTokenIssuer_IssueImplicitTx_Call) Run(run func(ctx context.Context, settings *record.Settings, input *issuance.ImplicitGrantInput, issueAccessToken bool, issueIdToken bool)) *ImplicitTokenIssuer_IssueImplicitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *record.Settings
		if args[1] != nil {
			arg1 = args[1].(*record.Settings)
		}
		var arg2 *issuance.ImplicitGrantInput
		if args[2] != nil {
			arg2 = args[2].(*issuance.ImplicitGrantInput)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ImplicitTokenIssuer_IssueImplicitTx_Call) Return(implicitGrantResponse *issuance.ImplicitGrantResponse, err error) *ImplicitTokenIssuer_IssueImplicitTx_Call {
	_c.Call.Return(implicitGrantResponse, err)
	return _c
}

func (_c *ImplicitTokenIssuer_IssueImplicitTx_Call) RunAndReturn(run func(ctx context.Context, settings *record.Settings, input *issuance.ImplicitGrantInput, issueAccessToken bool, issueIdToken bool) (*issuance.ImplicitGrantResponse, error)) *ImplicitTokenIssuer_IssueImplicitTx_Call {
	_c.Call.Return(run)
	return _c
}
