// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_handlers

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewJSONWriter creates a new instance of JSONWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJSONWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *JSONWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &JSONWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// JSONWriter is an autogenerated mock type for the JSONWriter type
type JSONWriter struct {
	mock.Mock
}

type JSONWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *JSONWriter) EXPECT() *JSONWriter_Expecter {
	return &JSONWriter_Expecter{mock: &_m.Mock}
}

// EncodeJson provides a mock function for the type JSONWriter
func (_mock *JSONWriter) EncodeJson(w http.ResponseWriter, r *http.Request, data interface{}) {
	_mock.Called(w, r, data)
	return
}

// JSONWriter_EncodeJson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeJson'
type JSONWriter_EncodeJson_Call struct {
	*mock.Call
}

// EncodeJson is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - data interface{}
func (_e *JSONWriter_Expecter) EncodeJson(w any, r any, data any) *JSONWriter_EncodeJson_Call {
	return &JSONWriter_EncodeJson_Call{Call: _e.mock.On("EncodeJson", w, r, data)}
}

func (_c *JSONWriter_EncodeJson_Call) Run(run func(w http.ResponseWriter, r *http.Request, data interface{})) *JSONWriter_EncodeJson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JSONWriter_EncodeJson_Call) Return() *JSONWriter_EncodeJson_Call {
	_c.Call.Return()
	return _c
}

func (_c *JSONWriter_EncodeJson_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, data interface{})) *JSONWriter_EncodeJson_Call {
	_c.Run(run)
	return _c
}

// JsonError provides a mock function for the type JSONWriter
func (_mock *JSONWriter) JsonError(w http.ResponseWriter, r *http.Request, err error) {
	_mock.Called(w, r, err)
	return
}

// JSONWriter_JsonError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JsonError'
type JSONWriter_JsonError_Call struct {
	*mock.Call
}

// JsonError is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *JSONWriter_Expecter) JsonError(w any, r any, err any) *JSONWriter_JsonError_Call {
	return &JSONWriter_JsonError_Call{Call: _e.mock.On("JsonError", w, r, err)}
}

func (_c *JSONWriter_JsonError_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *JSONWriter_JsonError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JSONWriter_JsonError_Call) Return() *JSONWriter_JsonError_Call {
	_c.Call.Return()
	return _c
}

func (_c *JSONWriter_JsonError_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, err error)) *JSONWriter_JsonError_Call {
	_c.Run(run)
	return _c
}
