// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_handlers

import (
	"bytes"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewPageRenderer creates a new instance of PageRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPageRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PageRenderer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PageRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PageRenderer is an autogenerated mock type for the PageRenderer type
type PageRenderer struct {
	mock.Mock
}

type PageRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *PageRenderer) EXPECT() *PageRenderer_Expecter {
	return &PageRenderer_Expecter{mock: &_m.Mock}
}

// InternalServerError provides a mock function for the type PageRenderer
func (_mock *PageRenderer) InternalServerError(w http.ResponseWriter, r *http.Request, err error) {
	_mock.Called(w, r, err)
	return
}

// PageRenderer_InternalServerError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalServerError'
type PageRenderer_InternalServerError_Call struct {
	*mock.Call
}

// InternalServerError is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *PageRenderer_Expecter) InternalServerError(w any, r any, err any) *PageRenderer_InternalServerError_Call {
	return &PageRenderer_InternalServerError_Call{Call: _e.mock.On("InternalServerError", w, r, err)}
}

func (_c *PageRenderer_InternalServerError_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *PageRenderer_InternalServerError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PageRenderer_InternalServerError_Call) Return() *PageRenderer_InternalServerError_Call {
	_c.Call.Return()
	return _c
}

func (_c *PageRenderer_InternalServerError_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, err error)) *PageRenderer_InternalServerError_Call {
	_c.Run(run)
	return _c
}

// NotFound provides a mock function for the type PageRenderer
func (_mock *PageRenderer) NotFound(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// PageRenderer_NotFound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotFound'
type PageRenderer_NotFound_Call struct {
	*mock.Call
}

// NotFound is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *PageRenderer_Expecter) NotFound(w any, r any) *PageRenderer_NotFound_Call {
	return &PageRenderer_NotFound_Call{Call: _e.mock.On("NotFound", w, r)}
}

func (_c *PageRenderer_NotFound_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *PageRenderer_NotFound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PageRenderer_NotFound_Call) Return() *PageRenderer_NotFound_Call {
	_c.Call.Return()
	return _c
}

func (_c *PageRenderer_NotFound_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *PageRenderer_NotFound_Call {
	_c.Run(run)
	return _c
}

// RenderTemplate provides a mock function for the type PageRenderer
func (_mock *PageRenderer) RenderTemplate(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{}) error {
	ret := _mock.Called(w, r, layoutName, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for RenderTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string, string, map[string]interface{}) error); ok {
		r0 = returnFunc(w, r, layoutName, templateName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PageRenderer_RenderTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderTemplate'
type PageRenderer_RenderTemplate_Call struct {
	*mock.Call
}

// RenderTemplate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - layoutName string
//   - templateName string
//   - data map[string]interface{}
func (_e *PageRenderer_Expecter) RenderTemplate(w any, r any, layoutName any, templateName any, data any) *PageRenderer_RenderTemplate_Call {
	return &PageRenderer_RenderTemplate_Call{Call: _e.mock.On("RenderTemplate", w, r, layoutName, templateName, data)}
}

func (_c *PageRenderer_RenderTemplate_Call) Run(run func(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{})) *PageRenderer_RenderTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *PageRenderer_RenderTemplate_Call) Return(err error) *PageRenderer_RenderTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PageRenderer_RenderTemplate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, layoutName string, templateName string, data map[string]interface{}) error) *PageRenderer_RenderTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// RenderTemplateToBuffer provides a mock function for the type PageRenderer
func (_mock *PageRenderer) RenderTemplateToBuffer(r *http.Request, layoutName string, templateName string, data map[string]interface{}) (*bytes.Buffer, error) {
	ret := _mock.Called(r, layoutName, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for RenderTemplateToBuffer")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, string, map[string]interface{}) (*bytes.Buffer, error)); ok {
		return returnFunc(r, layoutName, templateName, data)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string, string, map[string]interface{}) *bytes.Buffer); ok {
		r0 = returnFunc(r, layoutName, templateName, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string, string, map[string]interface{}) error); ok {
		r1 = returnFunc(r, layoutName, templateName, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PageRenderer_RenderTemplateToBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderTemplateToBuffer'
type PageRenderer_RenderTemplateToBuffer_Call struct {
	*mock.Call
}

// RenderTemplateToBuffer is a helper method to define mock.On call
//   - r *http.Request
//   - layoutName string
//   - templateName string
//   - data map[string]interface{}
func (_e *PageRenderer_Expecter) RenderTemplateToBuffer(r any, layoutName any, templateName any, data any) *PageRenderer_RenderTemplateToBuffer_Call {
	return &PageRenderer_RenderTemplateToBuffer_Call{Call: _e.mock.On("RenderTemplateToBuffer", r, layoutName, templateName, data)}
}

func (_c *PageRenderer_RenderTemplateToBuffer_Call) Run(run func(r *http.Request, layoutName string, templateName string, data map[string]interface{})) *PageRenderer_RenderTemplateToBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PageRenderer_RenderTemplateToBuffer_Call) Return(buffer *bytes.Buffer, err error) *PageRenderer_RenderTemplateToBuffer_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *PageRenderer_RenderTemplateToBuffer_Call) RunAndReturn(run func(r *http.Request, layoutName string, templateName string, data map[string]interface{}) (*bytes.Buffer, error)) *PageRenderer_RenderTemplateToBuffer_Call {
	_c.Call.Return(run)
	return _c
}
