// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package handlersmocks

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/record"
	mock "github.com/stretchr/testify/mock"
)

// NewPermissionChecker creates a new instance of PermissionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionChecker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PermissionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PermissionChecker is an autogenerated mock type for the PermissionChecker type
type PermissionChecker struct {
	mock.Mock
}

type PermissionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionChecker) EXPECT() *PermissionChecker_Expecter {
	return &PermissionChecker_Expecter{mock: &_m.Mock}
}

// FilterOutScopesWhereUserIsNotAuthorized provides a mock function for the type PermissionChecker
func (_mock *PermissionChecker) FilterOutScopesWhereUserIsNotAuthorized(ctx context.Context, scope string, user *record.User) (string, error) {
	ret := _mock.Called(ctx, scope, user)

	if len(ret) == 0 {
		panic("no return value specified for FilterOutScopesWhereUserIsNotAuthorized")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *record.User) (string, error)); ok {
		return returnFunc(ctx, scope, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *record.User) string); ok {
		r0 = returnFunc(ctx, scope, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *record.User) error); ok {
		r1 = returnFunc(ctx, scope, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterOutScopesWhereUserIsNotAuthorized'
type PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call struct {
	*mock.Call
}

// FilterOutScopesWhereUserIsNotAuthorized is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - user *record.User
func (_e *PermissionChecker_Expecter) FilterOutScopesWhereUserIsNotAuthorized(ctx any, scope any, user any) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	return &PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call{Call: _e.mock.On("FilterOutScopesWhereUserIsNotAuthorized", ctx, scope, user)}
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) Run(run func(ctx context.Context, scope string, user *record.User)) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *record.User
		if args[2] != nil {
			arg2 = args[2].(*record.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) Return(s string, err error) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call) RunAndReturn(run func(ctx context.Context, scope string, user *record.User) (string, error)) *PermissionChecker_FilterOutScopesWhereUserIsNotAuthorized_Call {
	_c.Call.Return(run)
	return _c
}
