// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_handlers

import (
	"context"

	"github.com/leodip/goiabada/authserver/internal/issuance"
	"github.com/leodip/goiabada/authserver/internal/models"
	"github.com/leodip/goiabada/core/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// GenerateTokenResponseForAuthCode provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateTokenResponseForAuthCode(ctx context.Context, settings *models.Settings, code *models.Code) (*oauth.TokenResponse, error) {
	ret := _mock.Called(ctx, settings, code)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenResponseForAuthCode")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *models.Code) (*oauth.TokenResponse, error)); ok {
		return returnFunc(ctx, settings, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *models.Code) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, settings, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Settings, *models.Code) error); ok {
		r1 = returnFunc(ctx, settings, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateTokenResponseForAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenResponseForAuthCode'
type TokenIssuer_GenerateTokenResponseForAuthCode_Call struct {
	*mock.Call
}

// GenerateTokenResponseForAuthCode is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.Settings
//   - code *models.Code
func (_e *TokenIssuer_Expecter) GenerateTokenResponseForAuthCode(ctx any, settings any, code any) *TokenIssuer_GenerateTokenResponseForAuthCode_Call {
	return &TokenIssuer_GenerateTokenResponseForAuthCode_Call{Call: _e.mock.On("GenerateTokenResponseForAuthCode", ctx, settings, code)}
}

func (_c *TokenIssuer_GenerateTokenResponseForAuthCode_Call) Run(run func(ctx context.Context, settings *models.Settings, code *models.Code)) *TokenIssuer_GenerateTokenResponseForAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Settings
		if args[1] != nil {
			arg1 = args[1].(*models.Settings)
		}
		var arg2 *models.Code
		if args[2] != nil {
			arg2 = args[2].(*models.Code)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForAuthCode_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenIssuer_GenerateTokenResponseForAuthCode_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForAuthCode_Call) RunAndReturn(run func(ctx context.Context, settings *models.Settings, code *models.Code) (*oauth.TokenResponse, error)) *TokenIssuer_GenerateTokenResponseForAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenResponseForClientCred provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateTokenResponseForClientCred(ctx context.Context, settings *models.Settings, client *models.Client, scope string) (*oauth.TokenResponse, error) {
	ret := _mock.Called(ctx, settings, client, scope)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenResponseForClientCred")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *models.Client, string) (*oauth.TokenResponse, error)); ok {
		return returnFunc(ctx, settings, client, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *models.Client, string) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, settings, client, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Settings, *models.Client, string) error); ok {
		r1 = returnFunc(ctx, settings, client, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateTokenResponseForClientCred_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenResponseForClientCred'
type TokenIssuer_GenerateTokenResponseForClientCred_Call struct {
	*mock.Call
}

// GenerateTokenResponseForClientCred is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.Settings
//   - client *models.Client
//   - scope string
func (_e *TokenIssuer_Expecter) GenerateTokenResponseForClientCred(ctx any, settings any, client any, scope any) *TokenIssuer_GenerateTokenResponseForClientCred_Call {
	return &TokenIssuer_GenerateTokenResponseForClientCred_Call{Call: _e.mock.On("GenerateTokenResponseForClientCred", ctx, settings, client, scope)}
}

func (_c *TokenIssuer_GenerateTokenResponseForClientCred_Call) Run(run func(ctx context.Context, settings *models.Settings, client *models.Client, scope string)) *TokenIssuer_GenerateTokenResponseForClientCred_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Settings
		if args[1] != nil {
			arg1 = args[1].(*models.Settings)
		}
		var arg2 *models.Client
		if args[2] != nil {
			arg2 = args[2].(*models.Client)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForClientCred_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenIssuer_GenerateTokenResponseForClientCred_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForClientCred_Call) RunAndReturn(run func(ctx context.Context, settings *models.Settings, client *models.Client, scope string) (*oauth.TokenResponse, error)) *TokenIssuer_GenerateTokenResponseForClientCred_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenResponseForROPC provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateTokenResponseForROPC(ctx context.Context, settings *models.Settings, input *issuance.ROPCGrantInput) (*oauth.TokenResponse, error) {
	ret := _mock.Called(ctx, settings, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenResponseForROPC")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.ROPCGrantInput) (*oauth.TokenResponse, error)); ok {
		return returnFunc(ctx, settings, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.ROPCGrantInput) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, settings, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Settings, *issuance.ROPCGrantInput) error); ok {
		r1 = returnFunc(ctx, settings, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateTokenResponseForROPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenResponseForROPC'
type TokenIssuer_GenerateTokenResponseForROPC_Call struct {
	*mock.Call
}

// GenerateTokenResponseForROPC is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.Settings
//   - input *issuance.ROPCGrantInput
func (_e *TokenIssuer_Expecter) GenerateTokenResponseForROPC(ctx any, settings any, input any) *TokenIssuer_GenerateTokenResponseForROPC_Call {
	return &TokenIssuer_GenerateTokenResponseForROPC_Call{Call: _e.mock.On("GenerateTokenResponseForROPC", ctx, settings, input)}
}

func (_c *TokenIssuer_GenerateTokenResponseForROPC_Call) Run(run func(ctx context.Context, settings *models.Settings, input *issuance.ROPCGrantInput)) *TokenIssuer_GenerateTokenResponseForROPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Settings
		if args[1] != nil {
			arg1 = args[1].(*models.Settings)
		}
		var arg2 *issuance.ROPCGrantInput
		if args[2] != nil {
			arg2 = args[2].(*issuance.ROPCGrantInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForROPC_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenIssuer_GenerateTokenResponseForROPC_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForROPC_Call) RunAndReturn(run func(ctx context.Context, settings *models.Settings, input *issuance.ROPCGrantInput) (*oauth.TokenResponse, error)) *TokenIssuer_GenerateTokenResponseForROPC_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenResponseForRefresh provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateTokenResponseForRefresh(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshInput) (*oauth.TokenResponse, error) {
	ret := _mock.Called(ctx, settings, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenResponseForRefresh")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshInput) (*oauth.TokenResponse, error)); ok {
		return returnFunc(ctx, settings, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshInput) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, settings, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshInput) error); ok {
		r1 = returnFunc(ctx, settings, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateTokenResponseForRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenResponseForRefresh'
type TokenIssuer_GenerateTokenResponseForRefresh_Call struct {
	*mock.Call
}

// GenerateTokenResponseForRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.Settings
//   - input *issuance.GenerateTokenForRefreshInput
func (_e *TokenIssuer_Expecter) GenerateTokenResponseForRefresh(ctx any, settings any, input any) *TokenIssuer_GenerateTokenResponseForRefresh_Call {
	return &TokenIssuer_GenerateTokenResponseForRefresh_Call{Call: _e.mock.On("GenerateTokenResponseForRefresh", ctx, settings, input)}
}

func (_c *TokenIssuer_GenerateTokenResponseForRefresh_Call) Run(run func(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshInput)) *TokenIssuer_GenerateTokenResponseForRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Settings
		if args[1] != nil {
			arg1 = args[1].(*models.Settings)
		}
		var arg2 *issuance.GenerateTokenForRefreshInput
		if args[2] != nil {
			arg2 = args[2].(*issuance.GenerateTokenForRefreshInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForRefresh_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenIssuer_GenerateTokenResponseForRefresh_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForRefresh_Call) RunAndReturn(run func(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshInput) (*oauth.TokenResponse, error)) *TokenIssuer_GenerateTokenResponseForRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenResponseForRefreshROPC provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateTokenResponseForRefreshROPC(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshROPCInput) (*oauth.TokenResponse, error) {
	ret := _mock.Called(ctx, settings, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenResponseForRefreshROPC")
	}

	var r0 *oauth.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshROPCInput) (*oauth.TokenResponse, error)); ok {
		return returnFunc(ctx, settings, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshROPCInput) *oauth.TokenResponse); ok {
		r0 = returnFunc(ctx, settings, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Settings, *issuance.GenerateTokenForRefreshROPCInput) error); ok {
		r1 = returnFunc(ctx, settings, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateTokenResponseForRefreshROPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenResponseForRefreshROPC'
type TokenIssuer_GenerateTokenResponseForRefreshROPC_Call struct {
	*mock.Call
}

// GenerateTokenResponseForRefreshROPC is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.Settings
//   - input *issuance.GenerateTokenForRefreshROPCInput
func (_e *TokenIssuer_Expecter) GenerateTokenResponseForRefreshROPC(ctx any, settings any, input any) *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call {
	return &TokenIssuer_GenerateTokenResponseForRefreshROPC_Call{Call: _e.mock.On("GenerateTokenResponseForRefreshROPC", ctx, settings, input)}
}

func (_c *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call) Run(run func(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshROPCInput)) *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Settings
		if args[1] != nil {
			arg1 = args[1].(*models.Settings)
		}
		var arg2 *issuance.GenerateTokenForRefreshROPCInput
		if args[2] != nil {
			arg2 = args[2].(*issuance.GenerateTokenForRefreshROPCInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call) Return(tokenResponse *oauth.TokenResponse, err error) *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call) RunAndReturn(run func(ctx context.Context, settings *models.Settings, input *issuance.GenerateTokenForRefreshROPCInput) (*oauth.TokenResponse, error)) *TokenIssuer_GenerateTokenResponseForRefreshROPC_Call {
	_c.Call.Return(run)
	return _c
}
