// Generated by mockery v3.8.0, pinned as tools.mockery in src/authserver/versions.yaml.
// Regenerate with src/authserver/generate-mocks.sh, which refuses any other version.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !production

package mocks_handlers

import (
	"context"
	"net/http"
	"time"

	"github.com/leodip/goiabada/authserver/internal/record"
	mock "github.com/stretchr/testify/mock"
)

// NewUserSessionManager creates a new instance of UserSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSessionManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &UserSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// UserSessionManager is an autogenerated mock type for the UserSessionManager type
type UserSessionManager struct {
	mock.Mock
}

type UserSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSessionManager) EXPECT() *UserSessionManager_Expecter {
	return &UserSessionManager_Expecter{mock: &_m.Mock}
}

// BumpUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) BumpUserSession(ctx context.Context, sessionIdentifier string, clientId int64, authMethods string, acrLevel record.AcrLevel, ipAddress string) (*record.UserSession, error) {
	ret := _mock.Called(ctx, sessionIdentifier, clientId, authMethods, acrLevel, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for BumpUserSession")
	}

	var r0 *record.UserSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, record.AcrLevel, string) (*record.UserSession, error)); ok {
		return returnFunc(ctx, sessionIdentifier, clientId, authMethods, acrLevel, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, record.AcrLevel, string) *record.UserSession); ok {
		r0 = returnFunc(ctx, sessionIdentifier, clientId, authMethods, acrLevel, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string, record.AcrLevel, string) error); ok {
		r1 = returnFunc(ctx, sessionIdentifier, clientId, authMethods, acrLevel, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserSessionManager_BumpUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BumpUserSession'
type UserSessionManager_BumpUserSession_Call struct {
	*mock.Call
}

// BumpUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIdentifier string
//   - clientId int64
//   - authMethods string
//   - acrLevel record.AcrLevel
//   - ipAddress string
func (_e *UserSessionManager_Expecter) BumpUserSession(ctx any, sessionIdentifier any, clientId any, authMethods any, acrLevel any, ipAddress any) *UserSessionManager_BumpUserSession_Call {
	return &UserSessionManager_BumpUserSession_Call{Call: _e.mock.On("BumpUserSession", ctx, sessionIdentifier, clientId, authMethods, acrLevel, ipAddress)}
}

func (_c *UserSessionManager_BumpUserSession_Call) Run(run func(ctx context.Context, sessionIdentifier string, clientId int64, authMethods string, acrLevel record.AcrLevel, ipAddress string)) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 record.AcrLevel
		if args[4] != nil {
			arg4 = args[4].(record.AcrLevel)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *UserSessionManager_BumpUserSession_Call) Return(userSession *record.UserSession, err error) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Return(userSession, err)
	return _c
}

func (_c *UserSessionManager_BumpUserSession_Call) RunAndReturn(run func(ctx context.Context, sessionIdentifier string, clientId int64, authMethods string, acrLevel record.AcrLevel, ipAddress string) (*record.UserSession, error)) *UserSessionManager_BumpUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// HasValidUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) HasValidUserSession(userSession *record.UserSession, idleTimeoutInSeconds int, maxLifetimeInSeconds int, requestedMaxAgeInSeconds *int64) bool {
	ret := _mock.Called(userSession, idleTimeoutInSeconds, maxLifetimeInSeconds, requestedMaxAgeInSeconds)

	if len(ret) == 0 {
		panic("no return value specified for HasValidUserSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*record.UserSession, int, int, *int64) bool); ok {
		r0 = returnFunc(userSession, idleTimeoutInSeconds, maxLifetimeInSeconds, requestedMaxAgeInSeconds)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// UserSessionManager_HasValidUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasValidUserSession'
type UserSessionManager_HasValidUserSession_Call struct {
	*mock.Call
}

// HasValidUserSession is a helper method to define mock.On call
//   - userSession *record.UserSession
//   - idleTimeoutInSeconds int
//   - maxLifetimeInSeconds int
//   - requestedMaxAgeInSeconds *int64
func (_e *UserSessionManager_Expecter) HasValidUserSession(userSession any, idleTimeoutInSeconds any, maxLifetimeInSeconds any, requestedMaxAgeInSeconds any) *UserSessionManager_HasValidUserSession_Call {
	return &UserSessionManager_HasValidUserSession_Call{Call: _e.mock.On("HasValidUserSession", userSession, idleTimeoutInSeconds, maxLifetimeInSeconds, requestedMaxAgeInSeconds)}
}

func (_c *UserSessionManager_HasValidUserSession_Call) Run(run func(userSession *record.UserSession, idleTimeoutInSeconds int, maxLifetimeInSeconds int, requestedMaxAgeInSeconds *int64)) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *record.UserSession
		if args[0] != nil {
			arg0 = args[0].(*record.UserSession)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserSessionManager_HasValidUserSession_Call) Return(b bool) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *UserSessionManager_HasValidUserSession_Call) RunAndReturn(run func(userSession *record.UserSession, idleTimeoutInSeconds int, maxLifetimeInSeconds int, requestedMaxAgeInSeconds *int64) bool) *UserSessionManager_HasValidUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartNewUserSession provides a mock function for the type UserSessionManager
func (_mock *UserSessionManager) StartNewUserSession(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel record.AcrLevel, authStateGeneration int64, otpConfigGeneration *int64, authenticatedAt *time.Time, ipAddress string, replacing *record.UserSession) (*record.UserSession, []record.UserSession, error) {
	ret := _mock.Called(w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)

	if len(ret) == 0 {
		panic("no return value specified for StartNewUserSession")
	}

	var r0 *record.UserSession
	var r1 []record.UserSession
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, int64, int64, string, record.AcrLevel, int64, *int64, *time.Time, string, *record.UserSession) (*record.UserSession, []record.UserSession, error)); ok {
		return returnFunc(w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, int64, int64, string, record.AcrLevel, int64, *int64, *time.Time, string, *record.UserSession) *record.UserSession); ok {
		r0 = returnFunc(w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, int64, int64, string, record.AcrLevel, int64, *int64, *time.Time, string, *record.UserSession) []record.UserSession); ok {
		r1 = returnFunc(w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]record.UserSession)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(http.ResponseWriter, *http.Request, int64, int64, string, record.AcrLevel, int64, *int64, *time.Time, string, *record.UserSession) error); ok {
		r2 = returnFunc(w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserSessionManager_StartNewUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNewUserSession'
type UserSessionManager_StartNewUserSession_Call struct {
	*mock.Call
}

// StartNewUserSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - userId int64
//   - clientId int64
//   - authMethods string
//   - acrLevel record.AcrLevel
//   - authStateGeneration int64
//   - otpConfigGeneration *int64
//   - authenticatedAt *time.Time
//   - ipAddress string
//   - replacing *record.UserSession
func (_e *UserSessionManager_Expecter) StartNewUserSession(w any, r any, userId any, clientId any, authMethods any, acrLevel any, authStateGeneration any, otpConfigGeneration any, authenticatedAt any, ipAddress any, replacing any) *UserSessionManager_StartNewUserSession_Call {
	return &UserSessionManager_StartNewUserSession_Call{Call: _e.mock.On("StartNewUserSession", w, r, userId, clientId, authMethods, acrLevel, authStateGeneration, otpConfigGeneration, authenticatedAt, ipAddress, replacing)}
}

func (_c *UserSessionManager_StartNewUserSession_Call) Run(run func(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel record.AcrLevel, authStateGeneration int64, otpConfigGeneration *int64, authenticatedAt *time.Time, ipAddress string, replacing *record.UserSession)) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 record.AcrLevel
		if args[5] != nil {
			arg5 = args[5].(record.AcrLevel)
		}
		var arg6 int64
		if args[6] != nil {
			arg6 = args[6].(int64)
		}
		var arg7 *int64
		if args[7] != nil {
			arg7 = args[7].(*int64)
		}
		var arg8 *time.Time
		if args[8] != nil {
			arg8 = args[8].(*time.Time)
		}
		var arg9 string
		if args[9] != nil {
			arg9 = args[9].(string)
		}
		var arg10 *record.UserSession
		if args[10] != nil {
			arg10 = args[10].(*record.UserSession)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
		)
	})
	return _c
}

func (_c *UserSessionManager_StartNewUserSession_Call) Return(userSession *record.UserSession, userSessions []record.UserSession, err error) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Return(userSession, userSessions, err)
	return _c
}

func (_c *UserSessionManager_StartNewUserSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, userId int64, clientId int64, authMethods string, acrLevel record.AcrLevel, authStateGeneration int64, otpConfigGeneration *int64, authenticatedAt *time.Time, ipAddress string, replacing *record.UserSession) (*record.UserSession, []record.UserSession, error)) *UserSessionManager_StartNewUserSession_Call {
	_c.Call.Return(run)
	return _c
}
