package lib

import (
	"os"
	"sort"
	"sync"
	"time"

	"log/slog"

	"github.com/pkg/errors"
)

type Zone struct {
	*time.Location

	CountryCode string
	Zone        string
	Abbr        []string
	CountryName string
	Comments    string
}

var loadLocationOnce sync.Once

func GetTimeZones() []*Zone {

	loadLocationOnce.Do(func() {
		for _, tz := range zones {
			var err error
			tz.Location, err = time.LoadLocation(tz.Zone)
			if err != nil {
				slog.Error(errors.Wrap(err, "unable to load time zone location from the OS").Error())
				os.Exit(1)
			}
		}

		sort.Slice(zones, func(i, j int) bool {
			return zones[i].CountryName < zones[j].CountryName
		})
	})
	return zones
}

func GetTimeZoneByZoneInfo(zoneInfo string) *Zone {
	zones := GetTimeZones()

	for _, tz := range zones {
		if tz.Zone == zoneInfo {
			return tz
		}
	}

	return nil
}

var zones = []*Zone{
	{CountryCode: "AF", Zone: "Asia/Kabul", Abbr: []string(nil), CountryName: "Afghanistan", Comments: ""},
	{CountryCode: "AX", Zone: "Europe/Helsinki", Abbr: []string{"EEST", "EET"}, CountryName: "Åland Islands", Comments: ""},
	{CountryCode: "AL", Zone: "Europe/Tirane", Abbr: []string{"CEST", "CET"}, CountryName: "Albania", Comments: ""},
	{CountryCode: "DZ", Zone: "Africa/Algiers", Abbr: []string{"CET"}, CountryName: "Algeria", Comments: ""},
	{CountryCode: "AD", Zone: "Europe/Andorra", Abbr: []string{"CEST", "CET"}, CountryName: "Andorra", Comments: ""},
	{CountryCode: "AO", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Angola", Comments: "West Africa Time"},
	{CountryCode: "AI", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Anguilla", Comments: ""},
	{CountryCode: "AQ", Zone: "Antarctica/Palmer", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Palmer"},
	{CountryCode: "AQ", Zone: "Antarctica/Davis", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Davis"},
	{CountryCode: "AQ", Zone: "Antarctica/DumontDUrville", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Dumont-d'Urville"},
	{CountryCode: "AQ", Zone: "Antarctica/Mawson", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Mawson"},
	{CountryCode: "AQ", Zone: "Antarctica/Casey", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Casey"},
	{CountryCode: "AQ", Zone: "Antarctica/Rothera", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Rothera"},
	{CountryCode: "AQ", Zone: "Antarctica/Syowa", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Syowa"},
	{CountryCode: "AQ", Zone: "Pacific/Auckland", Abbr: []string{"NZDT", "NZST"}, CountryName: "Antarctica", Comments: "New Zealand time"},
	{CountryCode: "AQ", Zone: "Antarctica/Vostok", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Vostok"},
	{CountryCode: "AQ", Zone: "Antarctica/Troll", Abbr: []string(nil), CountryName: "Antarctica", Comments: "Troll"},
	{CountryCode: "AG", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Antigua & Barbuda", Comments: ""},
	{CountryCode: "AR", Zone: "America/Argentina/Cordoba", Abbr: []string(nil), CountryName: "Argentina", Comments: "Argentina (most areas: CB, CC, CN, ER, FM, MN, SE, SF)"},
	{CountryCode: "AR", Zone: "America/Argentina/Salta", Abbr: []string(nil), CountryName: "Argentina", Comments: "Salta (SA, LP, NQ, RN)"},
	{CountryCode: "AR", Zone: "America/Argentina/Tucuman", Abbr: []string(nil), CountryName: "Argentina", Comments: "Tucumán (TM)"},
	{CountryCode: "AR", Zone: "America/Argentina/Catamarca", Abbr: []string(nil), CountryName: "Argentina", Comments: "Catamarca (CT); Chubut (CH)"},
	{CountryCode: "AR", Zone: "America/Argentina/Buenos_Aires", Abbr: []string(nil), CountryName: "Argentina", Comments: "Buenos Aires (BA, CF)"},
	{CountryCode: "AR", Zone: "America/Argentina/San_Juan", Abbr: []string(nil), CountryName: "Argentina", Comments: "San Juan (SJ)"},
	{CountryCode: "AR", Zone: "America/Argentina/Mendoza", Abbr: []string(nil), CountryName: "Argentina", Comments: "Mendoza (MZ)"},
	{CountryCode: "AR", Zone: "America/Argentina/San_Luis", Abbr: []string(nil), CountryName: "Argentina", Comments: "San Luis (SL)"},
	{CountryCode: "AR", Zone: "America/Argentina/Rio_Gallegos", Abbr: []string(nil), CountryName: "Argentina", Comments: "Santa Cruz (SC)"},
	{CountryCode: "AR", Zone: "America/Argentina/Ushuaia", Abbr: []string(nil), CountryName: "Argentina", Comments: "Tierra del Fuego (TF)"},
	{CountryCode: "AR", Zone: "America/Argentina/La_Rioja", Abbr: []string(nil), CountryName: "Argentina", Comments: "La Rioja (LR)"},
	{CountryCode: "AR", Zone: "America/Argentina/Jujuy", Abbr: []string(nil), CountryName: "Argentina", Comments: "Jujuy (JY)"},
	{CountryCode: "AM", Zone: "Asia/Yerevan", Abbr: []string(nil), CountryName: "Armenia", Comments: ""},
	{CountryCode: "AW", Zone: "America/Curacao", Abbr: []string{"AST"}, CountryName: "Aruba", Comments: ""},
	{CountryCode: "AU", Zone: "Australia/Sydney", Abbr: []string{"AEDT", "AEST"}, CountryName: "Australia", Comments: "New South Wales (most areas)"},
	{CountryCode: "AU", Zone: "Australia/Hobart", Abbr: []string{"AEDT", "AEST"}, CountryName: "Australia", Comments: "Tasmania (most areas)"},
	{CountryCode: "AU", Zone: "Australia/Currie", Abbr: []string{"AEDT", "AEST"}, CountryName: "Australia", Comments: "Tasmania (King Island)"},
	{CountryCode: "AU", Zone: "Australia/Melbourne", Abbr: []string{"AEDT", "AEST"}, CountryName: "Australia", Comments: "Victoria"},
	{CountryCode: "AU", Zone: "Antarctica/Macquarie", Abbr: []string{"AEDT", "AEST"}, CountryName: "Australia", Comments: "Macquarie Island"},
	{CountryCode: "AU", Zone: "Australia/Broken_Hill", Abbr: []string{"ACDT", "ACST"}, CountryName: "Australia", Comments: "New South Wales (Yancowinna)"},
	{CountryCode: "AU", Zone: "Australia/Lord_Howe", Abbr: []string(nil), CountryName: "Australia", Comments: "Lord Howe Island"},
	{CountryCode: "AU", Zone: "Australia/Lindeman", Abbr: []string{"AEST"}, CountryName: "Australia", Comments: "Queensland (Whitsunday Islands)"},
	{CountryCode: "AU", Zone: "Australia/Adelaide", Abbr: []string{"ACDT", "ACST"}, CountryName: "Australia", Comments: "South Australia"},
	{CountryCode: "AU", Zone: "Australia/Darwin", Abbr: []string{"ACST"}, CountryName: "Australia", Comments: "Northern Territory"},
	{CountryCode: "AU", Zone: "Australia/Perth", Abbr: []string{"AWST"}, CountryName: "Australia", Comments: "Western Australia (most areas)"},
	{CountryCode: "AU", Zone: "Australia/Eucla", Abbr: []string(nil), CountryName: "Australia", Comments: "Western Australia (Eucla)"},
	{CountryCode: "AU", Zone: "Australia/Brisbane", Abbr: []string{"AEST"}, CountryName: "Australia", Comments: "Queensland (most areas)"},
	{CountryCode: "AT", Zone: "Europe/Vienna", Abbr: []string{"CEST", "CET"}, CountryName: "Austria", Comments: ""},
	{CountryCode: "AZ", Zone: "Asia/Baku", Abbr: []string(nil), CountryName: "Azerbaijan", Comments: ""},
	{CountryCode: "BS", Zone: "America/Nassau", Abbr: []string{"EDT", "EST"}, CountryName: "Bahamas", Comments: ""},
	{CountryCode: "BH", Zone: "Asia/Qatar", Abbr: []string(nil), CountryName: "Bahrain", Comments: ""},
	{CountryCode: "BD", Zone: "Asia/Dhaka", Abbr: []string(nil), CountryName: "Bangladesh", Comments: ""},
	{CountryCode: "BB", Zone: "America/Barbados", Abbr: []string{"AST"}, CountryName: "Barbados", Comments: ""},
	{CountryCode: "BY", Zone: "Europe/Minsk", Abbr: []string(nil), CountryName: "Belarus", Comments: ""},
	{CountryCode: "BE", Zone: "Europe/Brussels", Abbr: []string{"CEST", "CET"}, CountryName: "Belgium", Comments: ""},
	{CountryCode: "BZ", Zone: "America/Belize", Abbr: []string{"CST"}, CountryName: "Belize", Comments: ""},
	{CountryCode: "BJ", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Benin", Comments: "West Africa Time"},
	{CountryCode: "BM", Zone: "Atlantic/Bermuda", Abbr: []string{"ADT", "AST"}, CountryName: "Bermuda", Comments: ""},
	{CountryCode: "BT", Zone: "Asia/Thimphu", Abbr: []string(nil), CountryName: "Bhutan", Comments: ""},
	{CountryCode: "BO", Zone: "America/La_Paz", Abbr: []string(nil), CountryName: "Bolivia", Comments: ""},
	{CountryCode: "BA", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "Bosnia & Herzegovina", Comments: ""},
	{CountryCode: "BW", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Botswana", Comments: "Central Africa Time"},
	{CountryCode: "BR", Zone: "America/Porto_Velho", Abbr: []string(nil), CountryName: "Brazil", Comments: "Rondônia"},
	{CountryCode: "BR", Zone: "America/Cuiaba", Abbr: []string(nil), CountryName: "Brazil", Comments: "Mato Grosso"},
	{CountryCode: "BR", Zone: "America/Santarem", Abbr: []string(nil), CountryName: "Brazil", Comments: "Pará (west)"},
	{CountryCode: "BR", Zone: "America/Sao_Paulo", Abbr: []string(nil), CountryName: "Brazil", Comments: "Brazil (southeast: GO, DF, MG, ES, RJ, SP, PR, SC, RS)"},
	{CountryCode: "BR", Zone: "America/Boa_Vista", Abbr: []string(nil), CountryName: "Brazil", Comments: "Roraima"},
	{CountryCode: "BR", Zone: "America/Bahia", Abbr: []string(nil), CountryName: "Brazil", Comments: "Bahia"},
	{CountryCode: "BR", Zone: "America/Eirunepe", Abbr: []string(nil), CountryName: "Brazil", Comments: "Amazonas (west)"},
	{CountryCode: "BR", Zone: "America/Rio_Branco", Abbr: []string(nil), CountryName: "Brazil", Comments: "Acre"},
	{CountryCode: "BR", Zone: "America/Maceio", Abbr: []string(nil), CountryName: "Brazil", Comments: "Alagoas, Sergipe"},
	{CountryCode: "BR", Zone: "America/Manaus", Abbr: []string(nil), CountryName: "Brazil", Comments: "Amazonas (east)"},
	{CountryCode: "BR", Zone: "America/Recife", Abbr: []string(nil), CountryName: "Brazil", Comments: "Pernambuco"},
	{CountryCode: "BR", Zone: "America/Belem", Abbr: []string(nil), CountryName: "Brazil", Comments: "Pará (east); Amapá"},
	{CountryCode: "BR", Zone: "America/Fortaleza", Abbr: []string(nil), CountryName: "Brazil", Comments: "Brazil (northeast: MA, PI, CE, RN, PB)"},
	{CountryCode: "BR", Zone: "America/Noronha", Abbr: []string(nil), CountryName: "Brazil", Comments: "Atlantic islands"},
	{CountryCode: "BR", Zone: "America/Campo_Grande", Abbr: []string(nil), CountryName: "Brazil", Comments: "Mato Grosso do Sul"},
	{CountryCode: "BR", Zone: "America/Araguaina", Abbr: []string(nil), CountryName: "Brazil", Comments: "Tocantins"},
	{CountryCode: "GB", Zone: "Europe/London", Abbr: []string{"BST", "GMT"}, CountryName: "Britain (UK)", Comments: ""},
	{CountryCode: "IO", Zone: "Indian/Chagos", Abbr: []string(nil), CountryName: "British Indian Ocean Territory", Comments: ""},
	{CountryCode: "BN", Zone: "Asia/Brunei", Abbr: []string(nil), CountryName: "Brunei", Comments: ""},
	{CountryCode: "BG", Zone: "Europe/Sofia", Abbr: []string{"EEST", "EET"}, CountryName: "Bulgaria", Comments: ""},
	{CountryCode: "BF", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Burkina Faso", Comments: ""},
	{CountryCode: "BI", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Burundi", Comments: "Central Africa Time"},
	{CountryCode: "KH", Zone: "Asia/Bangkok", Abbr: []string(nil), CountryName: "Cambodia", Comments: "Indochina (most areas)"},
	{CountryCode: "CM", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Cameroon", Comments: "West Africa Time"},
	{CountryCode: "CA", Zone: "America/Goose_Bay", Abbr: []string{"ADT", "AST"}, CountryName: "Canada", Comments: "Atlantic - Labrador (most areas)"},
	{CountryCode: "CA", Zone: "America/Rainy_River", Abbr: []string{"CDT", "CST"}, CountryName: "Canada", Comments: "Central - ON (Rainy R, Ft Frances)"},
	{CountryCode: "CA", Zone: "America/Resolute", Abbr: []string{"CDT", "CST"}, CountryName: "Canada", Comments: "Central - NU (Resolute)"},
	{CountryCode: "CA", Zone: "America/Moncton", Abbr: []string{"ADT", "AST"}, CountryName: "Canada", Comments: "Atlantic - New Brunswick"},
	{CountryCode: "CA", Zone: "America/Regina", Abbr: []string{"CST"}, CountryName: "Canada", Comments: "CST - SK (most areas)"},
	{CountryCode: "CA", Zone: "America/Swift_Current", Abbr: []string{"CST"}, CountryName: "Canada", Comments: "CST - SK (midwest)"},
	{CountryCode: "CA", Zone: "America/Edmonton", Abbr: []string{"MDT", "MST"}, CountryName: "Canada", Comments: "Mountain - AB; BC (E); SK (W)"},
	{CountryCode: "CA", Zone: "America/Cambridge_Bay", Abbr: []string{"MDT", "MST"}, CountryName: "Canada", Comments: "Mountain - NU (west)"},
	{CountryCode: "CA", Zone: "America/Yellowknife", Abbr: []string{"MDT", "MST"}, CountryName: "Canada", Comments: "Mountain - NT (central)"},
	{CountryCode: "CA", Zone: "America/Inuvik", Abbr: []string{"MDT", "MST"}, CountryName: "Canada", Comments: "Mountain - NT (west)"},
	{CountryCode: "CA", Zone: "America/Creston", Abbr: []string{"MST"}, CountryName: "Canada", Comments: "MST - BC (Creston)"},
	{CountryCode: "CA", Zone: "America/Dawson_Creek", Abbr: []string{"MST"}, CountryName: "Canada", Comments: "MST - BC (Dawson Cr, Ft St John)"},
	{CountryCode: "CA", Zone: "America/Fort_Nelson", Abbr: []string{"MST"}, CountryName: "Canada", Comments: "MST - BC (Ft Nelson)"},
	{CountryCode: "CA", Zone: "America/Glace_Bay", Abbr: []string{"ADT", "AST"}, CountryName: "Canada", Comments: "Atlantic - NS (Cape Breton)"},
	{CountryCode: "CA", Zone: "America/Whitehorse", Abbr: []string{"MST", "PDT", "PST"}, CountryName: "Canada", Comments: "Pacific - Yukon (east)"},
	{CountryCode: "CA", Zone: "America/Dawson", Abbr: []string{"MST", "PDT", "PST"}, CountryName: "Canada", Comments: "Pacific - Yukon (west)"},
	{CountryCode: "CA", Zone: "America/Halifax", Abbr: []string{"ADT", "AST"}, CountryName: "Canada", Comments: "Atlantic - NS (most areas); PE"},
	{CountryCode: "CA", Zone: "America/Winnipeg", Abbr: []string{"CDT", "CST"}, CountryName: "Canada", Comments: "Central - ON (west); Manitoba"},
	{CountryCode: "CA", Zone: "America/St_Johns", Abbr: []string{"NDT", "NST"}, CountryName: "Canada", Comments: "Newfoundland; Labrador (southeast)"},
	{CountryCode: "CA", Zone: "America/Atikokan", Abbr: []string{"EST"}, CountryName: "Canada", Comments: "EST - ON (Atikokan); NU (Coral H)"},
	{CountryCode: "CA", Zone: "America/Pangnirtung", Abbr: []string{"EDT", "EST"}, CountryName: "Canada", Comments: "Eastern - NU (Pangnirtung)"},
	{CountryCode: "CA", Zone: "America/Iqaluit", Abbr: []string{"EDT", "EST"}, CountryName: "Canada", Comments: "Eastern - NU (most east areas)"},
	{CountryCode: "CA", Zone: "America/Thunder_Bay", Abbr: []string{"EDT", "EST"}, CountryName: "Canada", Comments: "Eastern - ON (Thunder Bay)"},
	{CountryCode: "CA", Zone: "America/Nipigon", Abbr: []string{"EDT", "EST"}, CountryName: "Canada", Comments: "Eastern - ON, QC (no DST 1967-73)"},
	{CountryCode: "CA", Zone: "America/Toronto", Abbr: []string{"EDT", "EST"}, CountryName: "Canada", Comments: "Eastern - ON, QC (most areas)"},
	{CountryCode: "CA", Zone: "America/Blanc-Sablon", Abbr: []string{"AST"}, CountryName: "Canada", Comments: "AST - QC (Lower North Shore)"},
	{CountryCode: "CA", Zone: "America/Vancouver", Abbr: []string{"PDT", "PST"}, CountryName: "Canada", Comments: "Pacific - BC (most areas)"},
	{CountryCode: "CA", Zone: "America/Rankin_Inlet", Abbr: []string{"CDT", "CST"}, CountryName: "Canada", Comments: "Central - NU (central)"},
	{CountryCode: "CV", Zone: "Atlantic/Cape_Verde", Abbr: []string(nil), CountryName: "Cape Verde", Comments: ""},
	{CountryCode: "BQ", Zone: "America/Curacao", Abbr: []string{"AST"}, CountryName: "Caribbean NL", Comments: ""},
	{CountryCode: "KY", Zone: "America/Panama", Abbr: []string{"EST"}, CountryName: "Cayman Islands", Comments: ""},
	{CountryCode: "CF", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Central African Rep.", Comments: "West Africa Time"},
	{CountryCode: "TD", Zone: "Africa/Ndjamena", Abbr: []string{"WAT"}, CountryName: "Chad", Comments: ""},
	{CountryCode: "CL", Zone: "America/Santiago", Abbr: []string(nil), CountryName: "Chile", Comments: "Chile (most areas)"},
	{CountryCode: "CL", Zone: "America/Punta_Arenas", Abbr: []string(nil), CountryName: "Chile", Comments: "Region of Magallanes"},
	{CountryCode: "CL", Zone: "Pacific/Easter", Abbr: []string(nil), CountryName: "Chile", Comments: "Easter Island"},
	{CountryCode: "CN", Zone: "Asia/Shanghai", Abbr: []string{"CST"}, CountryName: "China", Comments: "Beijing Time"},
	{CountryCode: "CN", Zone: "Asia/Urumqi", Abbr: []string(nil), CountryName: "China", Comments: "Xinjiang Time"},
	{CountryCode: "CX", Zone: "Indian/Christmas", Abbr: []string(nil), CountryName: "Christmas Island", Comments: ""},
	{CountryCode: "CC", Zone: "Indian/Cocos", Abbr: []string(nil), CountryName: "Cocos (Keeling) Islands", Comments: ""},
	{CountryCode: "CO", Zone: "America/Bogota", Abbr: []string(nil), CountryName: "Colombia", Comments: ""},
	{CountryCode: "KM", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Comoros", Comments: ""},
	{CountryCode: "CD", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Congo (Dem. Rep.)", Comments: "Central Africa Time"},
	{CountryCode: "CD", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Congo (Dem. Rep.)", Comments: "West Africa Time"},
	{CountryCode: "CG", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Congo (Rep.)", Comments: "West Africa Time"},
	{CountryCode: "CK", Zone: "Pacific/Rarotonga", Abbr: []string(nil), CountryName: "Cook Islands", Comments: ""},
	{CountryCode: "CR", Zone: "America/Costa_Rica", Abbr: []string{"CST"}, CountryName: "Costa Rica", Comments: ""},
	{CountryCode: "HR", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "Croatia", Comments: ""},
	{CountryCode: "CU", Zone: "America/Havana", Abbr: []string{"CDT", "CST"}, CountryName: "Cuba", Comments: ""},
	{CountryCode: "CW", Zone: "America/Curacao", Abbr: []string{"AST"}, CountryName: "Curaçao", Comments: ""},
	{CountryCode: "CY", Zone: "Asia/Famagusta", Abbr: []string{"EEST", "EET"}, CountryName: "Cyprus", Comments: "Northern Cyprus"},
	{CountryCode: "CY", Zone: "Asia/Nicosia", Abbr: []string{"EEST", "EET"}, CountryName: "Cyprus", Comments: "Cyprus (most areas)"},
	{CountryCode: "CZ", Zone: "Europe/Prague", Abbr: []string{"CEST", "CET"}, CountryName: "Czech Republic", Comments: ""},
	{CountryCode: "CI", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Côte d'Ivoire", Comments: ""},
	{CountryCode: "DK", Zone: "Europe/Copenhagen", Abbr: []string{"CEST", "CET"}, CountryName: "Denmark", Comments: ""},
	{CountryCode: "DJ", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Djibouti", Comments: ""},
	{CountryCode: "DM", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Dominica", Comments: ""},
	{CountryCode: "DO", Zone: "America/Santo_Domingo", Abbr: []string{"AST"}, CountryName: "Dominican Republic", Comments: ""},
	{CountryCode: "TL", Zone: "Asia/Dili", Abbr: []string(nil), CountryName: "East Timor", Comments: ""},
	{CountryCode: "EC", Zone: "Pacific/Galapagos", Abbr: []string(nil), CountryName: "Ecuador", Comments: "Galápagos Islands"},
	{CountryCode: "EC", Zone: "America/Guayaquil", Abbr: []string(nil), CountryName: "Ecuador", Comments: "Ecuador (mainland)"},
	{CountryCode: "EG", Zone: "Africa/Cairo", Abbr: []string{"EET"}, CountryName: "Egypt", Comments: ""},
	{CountryCode: "SV", Zone: "America/El_Salvador", Abbr: []string{"CST"}, CountryName: "El Salvador", Comments: ""},
	{CountryCode: "GQ", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Equatorial Guinea", Comments: "West Africa Time"},
	{CountryCode: "ER", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Eritrea", Comments: ""},
	{CountryCode: "EE", Zone: "Europe/Tallinn", Abbr: []string{"EEST", "EET"}, CountryName: "Estonia", Comments: ""},
	{CountryCode: "SZ", Zone: "Africa/Johannesburg", Abbr: []string{"SAST"}, CountryName: "Eswatini (Swaziland)", Comments: ""},
	{CountryCode: "ET", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Ethiopia", Comments: ""},
	{CountryCode: "FK", Zone: "Atlantic/Stanley", Abbr: []string(nil), CountryName: "Falkland Islands", Comments: ""},
	{CountryCode: "FO", Zone: "Atlantic/Faroe", Abbr: []string{"WEST", "WET"}, CountryName: "Faroe Islands", Comments: ""},
	{CountryCode: "FJ", Zone: "Pacific/Fiji", Abbr: []string(nil), CountryName: "Fiji", Comments: ""},
	{CountryCode: "FI", Zone: "Europe/Helsinki", Abbr: []string{"EEST", "EET"}, CountryName: "Finland", Comments: ""},
	{CountryCode: "FR", Zone: "Europe/Paris", Abbr: []string{"CEST", "CET"}, CountryName: "France", Comments: ""},
	{CountryCode: "GF", Zone: "America/Cayenne", Abbr: []string(nil), CountryName: "French Guiana", Comments: ""},
	{CountryCode: "PF", Zone: "Pacific/Tahiti", Abbr: []string(nil), CountryName: "French Polynesia", Comments: "Society Islands"},
	{CountryCode: "PF", Zone: "Pacific/Gambier", Abbr: []string(nil), CountryName: "French Polynesia", Comments: "Gambier Islands"},
	{CountryCode: "PF", Zone: "Pacific/Marquesas", Abbr: []string(nil), CountryName: "French Polynesia", Comments: "Marquesas Islands"},
	{CountryCode: "TF", Zone: "Indian/Reunion", Abbr: []string(nil), CountryName: "French Southern & Antarctic Lands", Comments: "Réunion, Crozet, Scattered Islands"},
	{CountryCode: "TF", Zone: "Indian/Kerguelen", Abbr: []string(nil), CountryName: "French Southern & Antarctic Lands", Comments: "Kerguelen, St Paul Island, Amsterdam Island"},
	{CountryCode: "GA", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Gabon", Comments: "West Africa Time"},
	{CountryCode: "GM", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Gambia", Comments: ""},
	{CountryCode: "GE", Zone: "Asia/Tbilisi", Abbr: []string(nil), CountryName: "Georgia", Comments: ""},
	{CountryCode: "DE", Zone: "Europe/Berlin", Abbr: []string{"CEST", "CET"}, CountryName: "Germany", Comments: "Germany (most areas)"},
	{CountryCode: "DE", Zone: "Europe/Zurich", Abbr: []string{"CEST", "CET"}, CountryName: "Germany", Comments: "Swiss time"},
	{CountryCode: "GH", Zone: "Africa/Accra", Abbr: []string{"GMT"}, CountryName: "Ghana", Comments: ""},
	{CountryCode: "GI", Zone: "Europe/Gibraltar", Abbr: []string{"CEST", "CET"}, CountryName: "Gibraltar", Comments: ""},
	{CountryCode: "GR", Zone: "Europe/Athens", Abbr: []string{"EEST", "EET"}, CountryName: "Greece", Comments: ""},
	{CountryCode: "GL", Zone: "America/Scoresbysund", Abbr: []string(nil), CountryName: "Greenland", Comments: "Scoresbysund/Ittoqqortoormiit"},
	{CountryCode: "GL", Zone: "America/Thule", Abbr: []string{"ADT", "AST"}, CountryName: "Greenland", Comments: "Thule/Pituffik"},
	{CountryCode: "GL", Zone: "America/Danmarkshavn", Abbr: []string{"GMT"}, CountryName: "Greenland", Comments: "National Park (east coast)"},
	{CountryCode: "GL", Zone: "America/Nuuk", Abbr: []string(nil), CountryName: "Greenland", Comments: "Greenland (most areas)"},
	{CountryCode: "GD", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Grenada", Comments: ""},
	{CountryCode: "GP", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Guadeloupe", Comments: ""},
	{CountryCode: "GU", Zone: "Pacific/Guam", Abbr: []string{"ChST"}, CountryName: "Guam", Comments: ""},
	{CountryCode: "GT", Zone: "America/Guatemala", Abbr: []string{"CST"}, CountryName: "Guatemala", Comments: ""},
	{CountryCode: "GG", Zone: "Europe/London", Abbr: []string{"BST", "GMT"}, CountryName: "Guernsey", Comments: ""},
	{CountryCode: "GN", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Guinea", Comments: ""},
	{CountryCode: "GW", Zone: "Africa/Bissau", Abbr: []string{"GMT"}, CountryName: "Guinea-Bissau", Comments: ""},
	{CountryCode: "GY", Zone: "America/Guyana", Abbr: []string(nil), CountryName: "Guyana", Comments: ""},
	{CountryCode: "HT", Zone: "America/Port-au-Prince", Abbr: []string{"EDT", "EST"}, CountryName: "Haiti", Comments: ""},
	{CountryCode: "HN", Zone: "America/Tegucigalpa", Abbr: []string{"CST"}, CountryName: "Honduras", Comments: ""},
	{CountryCode: "HK", Zone: "Asia/Hong_Kong", Abbr: []string{"HKT"}, CountryName: "Hong Kong", Comments: ""},
	{CountryCode: "HU", Zone: "Europe/Budapest", Abbr: []string{"CEST", "CET"}, CountryName: "Hungary", Comments: ""},
	{CountryCode: "IS", Zone: "Atlantic/Reykjavik", Abbr: []string{"GMT"}, CountryName: "Iceland", Comments: ""},
	{CountryCode: "IN", Zone: "Asia/Kolkata", Abbr: []string{"IST"}, CountryName: "India", Comments: ""},
	{CountryCode: "ID", Zone: "Asia/Jayapura", Abbr: []string{"WIT"}, CountryName: "Indonesia", Comments: "New Guinea (West Papua / Irian Jaya); Malukus/Moluccas"},
	{CountryCode: "ID", Zone: "Asia/Makassar", Abbr: []string{"WITA"}, CountryName: "Indonesia", Comments: "Borneo (east, south); Sulawesi/Celebes, Bali, Nusa Tengarra; Timor (west)"},
	{CountryCode: "ID", Zone: "Asia/Pontianak", Abbr: []string{"WIB"}, CountryName: "Indonesia", Comments: "Borneo (west, central)"},
	{CountryCode: "ID", Zone: "Asia/Jakarta", Abbr: []string{"WIB"}, CountryName: "Indonesia", Comments: "Java, Sumatra"},
	{CountryCode: "IR", Zone: "Asia/Tehran", Abbr: []string(nil), CountryName: "Iran", Comments: ""},
	{CountryCode: "IQ", Zone: "Asia/Baghdad", Abbr: []string(nil), CountryName: "Iraq", Comments: ""},
	{CountryCode: "IE", Zone: "Europe/Dublin", Abbr: []string{"GMT", "IST"}, CountryName: "Ireland", Comments: ""},
	{CountryCode: "IM", Zone: "Europe/London", Abbr: []string{"BST", "GMT"}, CountryName: "Isle of Man", Comments: ""},
	{CountryCode: "IL", Zone: "Asia/Jerusalem", Abbr: []string{"IDT", "IST"}, CountryName: "Israel", Comments: ""},
	{CountryCode: "IT", Zone: "Europe/Rome", Abbr: []string{"CEST", "CET"}, CountryName: "Italy", Comments: ""},
	{CountryCode: "JM", Zone: "America/Jamaica", Abbr: []string{"EST"}, CountryName: "Jamaica", Comments: ""},
	{CountryCode: "JP", Zone: "Asia/Tokyo", Abbr: []string{"JST"}, CountryName: "Japan", Comments: ""},
	{CountryCode: "JE", Zone: "Europe/London", Abbr: []string{"BST", "GMT"}, CountryName: "Jersey", Comments: ""},
	{CountryCode: "JO", Zone: "Asia/Amman", Abbr: []string{"EEST", "EET"}, CountryName: "Jordan", Comments: ""},
	{CountryCode: "KZ", Zone: "Asia/Atyrau", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Atyraū/Atirau/Gur'yev"},
	{CountryCode: "KZ", Zone: "Asia/Aqtobe", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Aqtöbe/Aktobe"},
	{CountryCode: "KZ", Zone: "Asia/Aqtau", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Mangghystaū/Mankistau"},
	{CountryCode: "KZ", Zone: "Asia/Oral", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "West Kazakhstan"},
	{CountryCode: "KZ", Zone: "Asia/Qostanay", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Qostanay/Kostanay/Kustanay"},
	{CountryCode: "KZ", Zone: "Asia/Almaty", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Kazakhstan (most areas)"},
	{CountryCode: "KZ", Zone: "Asia/Qyzylorda", Abbr: []string(nil), CountryName: "Kazakhstan", Comments: "Qyzylorda/Kyzylorda/Kzyl-Orda"},
	{CountryCode: "KE", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Kenya", Comments: ""},
	{CountryCode: "KI", Zone: "Pacific/Kiritimati", Abbr: []string(nil), CountryName: "Kiribati", Comments: "Line Islands"},
	{CountryCode: "KI", Zone: "Pacific/Tarawa", Abbr: []string(nil), CountryName: "Kiribati", Comments: "Gilbert Islands"},
	{CountryCode: "KI", Zone: "Pacific/Enderbury", Abbr: []string(nil), CountryName: "Kiribati", Comments: "Phoenix Islands"},
	{CountryCode: "KP", Zone: "Asia/Pyongyang", Abbr: []string{"KST"}, CountryName: "Korea (North)", Comments: ""},
	{CountryCode: "KR", Zone: "Asia/Seoul", Abbr: []string{"KST"}, CountryName: "Korea (South)", Comments: ""},
	{CountryCode: "KW", Zone: "Asia/Riyadh", Abbr: []string(nil), CountryName: "Kuwait", Comments: ""},
	{CountryCode: "KG", Zone: "Asia/Bishkek", Abbr: []string(nil), CountryName: "Kyrgyzstan", Comments: ""},
	{CountryCode: "LA", Zone: "Asia/Bangkok", Abbr: []string(nil), CountryName: "Laos", Comments: "Indochina (most areas)"},
	{CountryCode: "LV", Zone: "Europe/Riga", Abbr: []string{"EEST", "EET"}, CountryName: "Latvia", Comments: ""},
	{CountryCode: "LB", Zone: "Asia/Beirut", Abbr: []string{"EEST", "EET"}, CountryName: "Lebanon", Comments: ""},
	{CountryCode: "LS", Zone: "Africa/Johannesburg", Abbr: []string{"SAST"}, CountryName: "Lesotho", Comments: ""},
	{CountryCode: "LR", Zone: "Africa/Monrovia", Abbr: []string{"GMT"}, CountryName: "Liberia", Comments: ""},
	{CountryCode: "LY", Zone: "Africa/Tripoli", Abbr: []string{"EET"}, CountryName: "Libya", Comments: ""},
	{CountryCode: "LI", Zone: "Europe/Zurich", Abbr: []string{"CEST", "CET"}, CountryName: "Liechtenstein", Comments: "Swiss time"},
	{CountryCode: "LT", Zone: "Europe/Vilnius", Abbr: []string{"EEST", "EET"}, CountryName: "Lithuania", Comments: ""},
	{CountryCode: "LU", Zone: "Europe/Luxembourg", Abbr: []string{"CEST", "CET"}, CountryName: "Luxembourg", Comments: ""},
	{CountryCode: "MO", Zone: "Asia/Macau", Abbr: []string{"CST"}, CountryName: "Macau", Comments: ""},
	{CountryCode: "MG", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Madagascar", Comments: ""},
	{CountryCode: "MW", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Malawi", Comments: "Central Africa Time"},
	{CountryCode: "MY", Zone: "Asia/Kuala_Lumpur", Abbr: []string(nil), CountryName: "Malaysia", Comments: "Malaysia (peninsula)"},
	{CountryCode: "MY", Zone: "Asia/Kuching", Abbr: []string(nil), CountryName: "Malaysia", Comments: "Sabah, Sarawak"},
	{CountryCode: "MV", Zone: "Indian/Maldives", Abbr: []string(nil), CountryName: "Maldives", Comments: ""},
	{CountryCode: "ML", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Mali", Comments: ""},
	{CountryCode: "MT", Zone: "Europe/Malta", Abbr: []string{"CEST", "CET"}, CountryName: "Malta", Comments: ""},
	{CountryCode: "MH", Zone: "Pacific/Kwajalein", Abbr: []string(nil), CountryName: "Marshall Islands", Comments: "Kwajalein"},
	{CountryCode: "MH", Zone: "Pacific/Majuro", Abbr: []string(nil), CountryName: "Marshall Islands", Comments: "Marshall Islands (most areas)"},
	{CountryCode: "MQ", Zone: "America/Martinique", Abbr: []string{"AST"}, CountryName: "Martinique", Comments: ""},
	{CountryCode: "MR", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Mauritania", Comments: ""},
	{CountryCode: "MU", Zone: "Indian/Mauritius", Abbr: []string(nil), CountryName: "Mauritius", Comments: ""},
	{CountryCode: "YT", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Mayotte", Comments: ""},
	{CountryCode: "MX", Zone: "America/Mexico_City", Abbr: []string{"CDT", "CST"}, CountryName: "Mexico", Comments: "Central Time"},
	{CountryCode: "MX", Zone: "America/Matamoros", Abbr: []string{"CDT", "CST"}, CountryName: "Mexico", Comments: "Central Time US - Coahuila, Nuevo León, Tamaulipas (US border)"},
	{CountryCode: "MX", Zone: "America/Mazatlan", Abbr: []string{"MDT", "MST"}, CountryName: "Mexico", Comments: "Mountain Time - Baja California Sur, Nayarit, Sinaloa"},
	{CountryCode: "MX", Zone: "America/Chihuahua", Abbr: []string{"MDT", "MST"}, CountryName: "Mexico", Comments: "Mountain Time - Chihuahua (most areas)"},
	{CountryCode: "MX", Zone: "America/Merida", Abbr: []string{"CDT", "CST"}, CountryName: "Mexico", Comments: "Central Time - Campeche, Yucatán"},
	{CountryCode: "MX", Zone: "America/Hermosillo", Abbr: []string{"MST"}, CountryName: "Mexico", Comments: "Mountain Standard Time - Sonora"},
	{CountryCode: "MX", Zone: "America/Tijuana", Abbr: []string{"PDT", "PST"}, CountryName: "Mexico", Comments: "Pacific Time US - Baja California"},
	{CountryCode: "MX", Zone: "America/Bahia_Banderas", Abbr: []string{"CDT", "CST"}, CountryName: "Mexico", Comments: "Central Time - Bahía de Banderas"},
	{CountryCode: "MX", Zone: "America/Cancun", Abbr: []string{"EST"}, CountryName: "Mexico", Comments: "Eastern Standard Time - Quintana Roo"},
	{CountryCode: "MX", Zone: "America/Monterrey", Abbr: []string{"CDT", "CST"}, CountryName: "Mexico", Comments: "Central Time - Durango; Coahuila, Nuevo León, Tamaulipas (most areas)"},
	{CountryCode: "MX", Zone: "America/Ojinaga", Abbr: []string{"MDT", "MST"}, CountryName: "Mexico", Comments: "Mountain Time US - Chihuahua (US border)"},
	{CountryCode: "FM", Zone: "Pacific/Chuuk", Abbr: []string(nil), CountryName: "Micronesia", Comments: "Chuuk/Truk, Yap"},
	{CountryCode: "FM", Zone: "Pacific/Kosrae", Abbr: []string(nil), CountryName: "Micronesia", Comments: "Kosrae"},
	{CountryCode: "FM", Zone: "Pacific/Pohnpei", Abbr: []string(nil), CountryName: "Micronesia", Comments: "Pohnpei/Ponape"},
	{CountryCode: "MD", Zone: "Europe/Chisinau", Abbr: []string{"EEST", "EET"}, CountryName: "Moldova", Comments: ""},
	{CountryCode: "MC", Zone: "Europe/Monaco", Abbr: []string{"CEST", "CET"}, CountryName: "Monaco", Comments: ""},
	{CountryCode: "MN", Zone: "Asia/Hovd", Abbr: []string(nil), CountryName: "Mongolia", Comments: "Bayan-Ölgii, Govi-Altai, Hovd, Uvs, Zavkhan"},
	{CountryCode: "MN", Zone: "Asia/Choibalsan", Abbr: []string(nil), CountryName: "Mongolia", Comments: "Dornod, Sükhbaatar"},
	{CountryCode: "MN", Zone: "Asia/Ulaanbaatar", Abbr: []string(nil), CountryName: "Mongolia", Comments: "Mongolia (most areas)"},
	{CountryCode: "ME", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "Montenegro", Comments: ""},
	{CountryCode: "MS", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Montserrat", Comments: ""},
	{CountryCode: "MA", Zone: "Africa/Casablanca", Abbr: []string(nil), CountryName: "Morocco", Comments: ""},
	{CountryCode: "MZ", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Mozambique", Comments: "Central Africa Time"},
	{CountryCode: "MM", Zone: "Asia/Yangon", Abbr: []string(nil), CountryName: "Myanmar (Burma)", Comments: ""},
	{CountryCode: "NA", Zone: "Africa/Windhoek", Abbr: []string{"CAT"}, CountryName: "Namibia", Comments: ""},
	{CountryCode: "NR", Zone: "Pacific/Nauru", Abbr: []string(nil), CountryName: "Nauru", Comments: ""},
	{CountryCode: "NP", Zone: "Asia/Kathmandu", Abbr: []string(nil), CountryName: "Nepal", Comments: ""},
	{CountryCode: "NL", Zone: "Europe/Amsterdam", Abbr: []string{"CEST", "CET"}, CountryName: "Netherlands", Comments: ""},
	{CountryCode: "NC", Zone: "Pacific/Noumea", Abbr: []string(nil), CountryName: "New Caledonia", Comments: ""},
	{CountryCode: "NZ", Zone: "Pacific/Chatham", Abbr: []string(nil), CountryName: "New Zealand", Comments: "Chatham Islands"},
	{CountryCode: "NZ", Zone: "Pacific/Auckland", Abbr: []string{"NZDT", "NZST"}, CountryName: "New Zealand", Comments: "New Zealand time"},
	{CountryCode: "NI", Zone: "America/Managua", Abbr: []string{"CST"}, CountryName: "Nicaragua", Comments: ""},
	{CountryCode: "NE", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Niger", Comments: "West Africa Time"},
	{CountryCode: "NG", Zone: "Africa/Lagos", Abbr: []string{"WAT"}, CountryName: "Nigeria", Comments: "West Africa Time"},
	{CountryCode: "NU", Zone: "Pacific/Niue", Abbr: []string(nil), CountryName: "Niue", Comments: ""},
	{CountryCode: "NF", Zone: "Pacific/Norfolk", Abbr: []string(nil), CountryName: "Norfolk Island", Comments: ""},
	{CountryCode: "MK", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "North Macedonia", Comments: ""},
	{CountryCode: "MP", Zone: "Pacific/Guam", Abbr: []string{"ChST"}, CountryName: "Northern Mariana Islands", Comments: ""},
	{CountryCode: "NO", Zone: "Europe/Oslo", Abbr: []string{"CEST", "CET"}, CountryName: "Norway", Comments: ""},
	{CountryCode: "OM", Zone: "Asia/Dubai", Abbr: []string(nil), CountryName: "Oman", Comments: ""},
	{CountryCode: "PK", Zone: "Asia/Karachi", Abbr: []string{"PKT"}, CountryName: "Pakistan", Comments: ""},
	{CountryCode: "PW", Zone: "Pacific/Palau", Abbr: []string(nil), CountryName: "Palau", Comments: ""},
	{CountryCode: "PS", Zone: "Asia/Gaza", Abbr: []string{"EEST", "EET"}, CountryName: "Palestine", Comments: "Gaza Strip"},
	{CountryCode: "PS", Zone: "Asia/Hebron", Abbr: []string{"EEST", "EET"}, CountryName: "Palestine", Comments: "West Bank"},
	{CountryCode: "PA", Zone: "America/Panama", Abbr: []string{"EST"}, CountryName: "Panama", Comments: ""},
	{CountryCode: "PG", Zone: "Pacific/Port_Moresby", Abbr: []string(nil), CountryName: "Papua New Guinea", Comments: "Papua New Guinea (most areas)"},
	{CountryCode: "PG", Zone: "Pacific/Bougainville", Abbr: []string(nil), CountryName: "Papua New Guinea", Comments: "Bougainville"},
	{CountryCode: "PY", Zone: "America/Asuncion", Abbr: []string(nil), CountryName: "Paraguay", Comments: ""},
	{CountryCode: "PE", Zone: "America/Lima", Abbr: []string(nil), CountryName: "Peru", Comments: ""},
	{CountryCode: "PH", Zone: "Asia/Manila", Abbr: []string{"PST"}, CountryName: "Philippines", Comments: ""},
	{CountryCode: "PN", Zone: "Pacific/Pitcairn", Abbr: []string(nil), CountryName: "Pitcairn", Comments: ""},
	{CountryCode: "PL", Zone: "Europe/Warsaw", Abbr: []string{"CEST", "CET"}, CountryName: "Poland", Comments: ""},
	{CountryCode: "PT", Zone: "Atlantic/Madeira", Abbr: []string{"WEST", "WET"}, CountryName: "Portugal", Comments: "Madeira Islands"},
	{CountryCode: "PT", Zone: "Atlantic/Azores", Abbr: []string(nil), CountryName: "Portugal", Comments: "Azores"},
	{CountryCode: "PT", Zone: "Europe/Lisbon", Abbr: []string{"WEST", "WET"}, CountryName: "Portugal", Comments: "Portugal (mainland)"},
	{CountryCode: "PR", Zone: "America/Puerto_Rico", Abbr: []string{"AST"}, CountryName: "Puerto Rico", Comments: ""},
	{CountryCode: "QA", Zone: "Asia/Qatar", Abbr: []string(nil), CountryName: "Qatar", Comments: ""},
	{CountryCode: "RO", Zone: "Europe/Bucharest", Abbr: []string{"EEST", "EET"}, CountryName: "Romania", Comments: ""},
	{CountryCode: "RU", Zone: "Asia/Tomsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+04 - Tomsk"},
	{CountryCode: "RU", Zone: "Asia/Ust-Nera", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+07 - Oymyakonsky"},
	{CountryCode: "RU", Zone: "Asia/Anadyr", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+09 - Bering Sea"},
	{CountryCode: "RU", Zone: "Asia/Kamchatka", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+09 - Kamchatka"},
	{CountryCode: "RU", Zone: "Asia/Srednekolymsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+08 - Sakha (E); North Kuril Is"},
	{CountryCode: "RU", Zone: "Asia/Sakhalin", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+08 - Sakhalin Island"},
	{CountryCode: "RU", Zone: "Asia/Omsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+03 - Omsk"},
	{CountryCode: "RU", Zone: "Asia/Magadan", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+08 - Magadan"},
	{CountryCode: "RU", Zone: "Asia/Novosibirsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+04 - Novosibirsk"},
	{CountryCode: "RU", Zone: "Asia/Vladivostok", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+07 - Amur River"},
	{CountryCode: "RU", Zone: "Asia/Khandyga", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+06 - Tomponsky, Ust-Maysky"},
	{CountryCode: "RU", Zone: "Asia/Yakutsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+06 - Lena River"},
	{CountryCode: "RU", Zone: "Europe/Samara", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+01 - Samara, Udmurtia"},
	{CountryCode: "RU", Zone: "Asia/Chita", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+06 - Zabaykalsky"},
	{CountryCode: "RU", Zone: "Europe/Volgograd", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+01 - Volgograd"},
	{CountryCode: "RU", Zone: "Europe/Kaliningrad", Abbr: []string{"EET"}, CountryName: "Russia", Comments: "MSK-01 - Kaliningrad"},
	{CountryCode: "RU", Zone: "Europe/Moscow", Abbr: []string{"MSK"}, CountryName: "Russia", Comments: "MSK+00 - Moscow area"},
	{CountryCode: "RU", Zone: "Europe/Simferopol", Abbr: []string{"MSK"}, CountryName: "Russia", Comments: "Crimea"},
	{CountryCode: "RU", Zone: "Asia/Irkutsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+05 - Irkutsk, Buryatia"},
	{CountryCode: "RU", Zone: "Europe/Kirov", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+00 - Kirov"},
	{CountryCode: "RU", Zone: "Europe/Astrakhan", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+01 - Astrakhan"},
	{CountryCode: "RU", Zone: "Asia/Barnaul", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+04 - Altai"},
	{CountryCode: "RU", Zone: "Europe/Saratov", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+01 - Saratov"},
	{CountryCode: "RU", Zone: "Europe/Ulyanovsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+01 - Ulyanovsk"},
	{CountryCode: "RU", Zone: "Asia/Krasnoyarsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+04 - Krasnoyarsk area"},
	{CountryCode: "RU", Zone: "Asia/Yekaterinburg", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+02 - Urals"},
	{CountryCode: "RU", Zone: "Asia/Novokuznetsk", Abbr: []string(nil), CountryName: "Russia", Comments: "MSK+04 - Kemerovo"},
	{CountryCode: "RW", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Rwanda", Comments: "Central Africa Time"},
	{CountryCode: "RE", Zone: "Indian/Reunion", Abbr: []string(nil), CountryName: "Réunion", Comments: "Réunion, Crozet, Scattered Islands"},
	{CountryCode: "AS", Zone: "Pacific/Pago_Pago", Abbr: []string{"SST"}, CountryName: "Samoa (American)", Comments: "Samoa, Midway"},
	{CountryCode: "WS", Zone: "Pacific/Apia", Abbr: []string(nil), CountryName: "Samoa (western)", Comments: ""},
	{CountryCode: "SM", Zone: "Europe/Rome", Abbr: []string{"CEST", "CET"}, CountryName: "San Marino", Comments: ""},
	{CountryCode: "ST", Zone: "Africa/Sao_Tome", Abbr: []string{"GMT"}, CountryName: "Sao Tome & Principe", Comments: ""},
	{CountryCode: "SA", Zone: "Asia/Riyadh", Abbr: []string(nil), CountryName: "Saudi Arabia", Comments: ""},
	{CountryCode: "SN", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Senegal", Comments: ""},
	{CountryCode: "RS", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "Serbia", Comments: ""},
	{CountryCode: "SC", Zone: "Indian/Mahe", Abbr: []string(nil), CountryName: "Seychelles", Comments: ""},
	{CountryCode: "SL", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Sierra Leone", Comments: ""},
	{CountryCode: "SG", Zone: "Asia/Singapore", Abbr: []string(nil), CountryName: "Singapore", Comments: ""},
	{CountryCode: "SK", Zone: "Europe/Prague", Abbr: []string{"CEST", "CET"}, CountryName: "Slovakia", Comments: ""},
	{CountryCode: "SI", Zone: "Europe/Belgrade", Abbr: []string{"CEST", "CET"}, CountryName: "Slovenia", Comments: ""},
	{CountryCode: "SB", Zone: "Pacific/Guadalcanal", Abbr: []string(nil), CountryName: "Solomon Islands", Comments: ""},
	{CountryCode: "SO", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Somalia", Comments: ""},
	{CountryCode: "ZA", Zone: "Africa/Johannesburg", Abbr: []string{"SAST"}, CountryName: "South Africa", Comments: ""},
	{CountryCode: "GS", Zone: "Atlantic/South_Georgia", Abbr: []string(nil), CountryName: "South Georgia & the South Sandwich Islands", Comments: ""},
	{CountryCode: "SS", Zone: "Africa/Juba", Abbr: []string{"EAT"}, CountryName: "South Sudan", Comments: ""},
	{CountryCode: "ES", Zone: "Europe/Madrid", Abbr: []string{"CEST", "CET"}, CountryName: "Spain", Comments: "Spain (mainland)"},
	{CountryCode: "ES", Zone: "Africa/Ceuta", Abbr: []string{"CEST", "CET"}, CountryName: "Spain", Comments: "Ceuta, Melilla"},
	{CountryCode: "ES", Zone: "Atlantic/Canary", Abbr: []string{"WEST", "WET"}, CountryName: "Spain", Comments: "Canary Islands"},
	{CountryCode: "LK", Zone: "Asia/Colombo", Abbr: []string(nil), CountryName: "Sri Lanka", Comments: ""},
	{CountryCode: "BL", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "St Barthelemy", Comments: ""},
	{CountryCode: "SH", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "St Helena", Comments: ""},
	{CountryCode: "KN", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "St Kitts & Nevis", Comments: ""},
	{CountryCode: "LC", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "St Lucia", Comments: ""},
	{CountryCode: "SX", Zone: "America/Curacao", Abbr: []string{"AST"}, CountryName: "St Maarten (Dutch)", Comments: ""},
	{CountryCode: "MF", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "St Martin (French)", Comments: ""},
	{CountryCode: "PM", Zone: "America/Miquelon", Abbr: []string(nil), CountryName: "St Pierre & Miquelon", Comments: ""},
	{CountryCode: "VC", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "St Vincent", Comments: ""},
	{CountryCode: "SD", Zone: "Africa/Khartoum", Abbr: []string{"CAT"}, CountryName: "Sudan", Comments: ""},
	{CountryCode: "SR", Zone: "America/Paramaribo", Abbr: []string(nil), CountryName: "Suriname", Comments: ""},
	{CountryCode: "SJ", Zone: "Europe/Oslo", Abbr: []string{"CEST", "CET"}, CountryName: "Svalbard & Jan Mayen", Comments: ""},
	{CountryCode: "SE", Zone: "Europe/Stockholm", Abbr: []string{"CEST", "CET"}, CountryName: "Sweden", Comments: ""},
	{CountryCode: "CH", Zone: "Europe/Zurich", Abbr: []string{"CEST", "CET"}, CountryName: "Switzerland", Comments: "Swiss time"},
	{CountryCode: "SY", Zone: "Asia/Damascus", Abbr: []string{"EEST", "EET"}, CountryName: "Syria", Comments: ""},
	{CountryCode: "TW", Zone: "Asia/Taipei", Abbr: []string{"CST"}, CountryName: "Taiwan", Comments: ""},
	{CountryCode: "TJ", Zone: "Asia/Dushanbe", Abbr: []string(nil), CountryName: "Tajikistan", Comments: ""},
	{CountryCode: "TZ", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Tanzania", Comments: ""},
	{CountryCode: "TH", Zone: "Asia/Bangkok", Abbr: []string(nil), CountryName: "Thailand", Comments: "Indochina (most areas)"},
	{CountryCode: "TG", Zone: "Africa/Abidjan", Abbr: []string{"GMT"}, CountryName: "Togo", Comments: ""},
	{CountryCode: "TK", Zone: "Pacific/Fakaofo", Abbr: []string(nil), CountryName: "Tokelau", Comments: ""},
	{CountryCode: "TO", Zone: "Pacific/Tongatapu", Abbr: []string(nil), CountryName: "Tonga", Comments: ""},
	{CountryCode: "TT", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Trinidad & Tobago", Comments: ""},
	{CountryCode: "TN", Zone: "Africa/Tunis", Abbr: []string{"CET"}, CountryName: "Tunisia", Comments: ""},
	{CountryCode: "TR", Zone: "Europe/Istanbul", Abbr: []string(nil), CountryName: "Turkey", Comments: ""},
	{CountryCode: "TM", Zone: "Asia/Ashgabat", Abbr: []string(nil), CountryName: "Turkmenistan", Comments: ""},
	{CountryCode: "TC", Zone: "America/Grand_Turk", Abbr: []string{"EDT", "EST"}, CountryName: "Turks & Caicos Is", Comments: ""},
	{CountryCode: "TV", Zone: "Pacific/Funafuti", Abbr: []string(nil), CountryName: "Tuvalu", Comments: ""},
	{CountryCode: "UM", Zone: "Pacific/Pago_Pago", Abbr: []string{"SST"}, CountryName: "US minor outlying islands", Comments: "Samoa, Midway"},
	{CountryCode: "UM", Zone: "Pacific/Wake", Abbr: []string(nil), CountryName: "US minor outlying islands", Comments: "Wake Island"},
	{CountryCode: "UM", Zone: "Pacific/Honolulu", Abbr: []string{"HST"}, CountryName: "US minor outlying islands", Comments: "Hawaii"},
	{CountryCode: "UG", Zone: "Africa/Nairobi", Abbr: []string{"EAT"}, CountryName: "Uganda", Comments: ""},
	{CountryCode: "UA", Zone: "Europe/Simferopol", Abbr: []string{"MSK"}, CountryName: "Ukraine", Comments: "Crimea"},
	{CountryCode: "UA", Zone: "Europe/Zaporozhye", Abbr: []string{"EEST", "EET"}, CountryName: "Ukraine", Comments: "Zaporozhye and east Lugansk"},
	{CountryCode: "UA", Zone: "Europe/Uzhgorod", Abbr: []string{"EEST", "EET"}, CountryName: "Ukraine", Comments: "Transcarpathia"},
	{CountryCode: "UA", Zone: "Europe/Kiev", Abbr: []string{"EEST", "EET"}, CountryName: "Ukraine", Comments: "Ukraine (most areas)"},
	{CountryCode: "AE", Zone: "Asia/Dubai", Abbr: []string(nil), CountryName: "United Arab Emirates", Comments: ""},
	{CountryCode: "US", Zone: "America/Kentucky/Louisville", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - KY (Louisville area)"},
	{CountryCode: "US", Zone: "America/Nome", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska (west)"},
	{CountryCode: "US", Zone: "America/Adak", Abbr: []string{"HDT", "HST"}, CountryName: "United States", Comments: "Aleutian Islands"},
	{CountryCode: "US", Zone: "Pacific/Honolulu", Abbr: []string{"HST"}, CountryName: "United States", Comments: "Hawaii"},
	{CountryCode: "US", Zone: "America/New_York", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern (most areas)"},
	{CountryCode: "US", Zone: "America/Detroit", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - MI (most areas)"},
	{CountryCode: "US", Zone: "America/Indiana/Vevay", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (Switzerland)"},
	{CountryCode: "US", Zone: "America/Kentucky/Monticello", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - KY (Wayne)"},
	{CountryCode: "US", Zone: "America/Indiana/Indianapolis", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (most areas)"},
	{CountryCode: "US", Zone: "America/Indiana/Vincennes", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (Da, Du, K, Mn)"},
	{CountryCode: "US", Zone: "America/Indiana/Winamac", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (Pulaski)"},
	{CountryCode: "US", Zone: "America/Indiana/Marengo", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (Crawford)"},
	{CountryCode: "US", Zone: "America/Indiana/Petersburg", Abbr: []string{"EDT", "EST"}, CountryName: "United States", Comments: "Eastern - IN (Pike)"},
	{CountryCode: "US", Zone: "America/Sitka", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska - Sitka area"},
	{CountryCode: "US", Zone: "America/Chicago", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central (most areas)"},
	{CountryCode: "US", Zone: "America/Yakutat", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska - Yakutat"},
	{CountryCode: "US", Zone: "America/Indiana/Knox", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - IN (Starke)"},
	{CountryCode: "US", Zone: "America/Menominee", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - MI (Wisconsin border)"},
	{CountryCode: "US", Zone: "America/North_Dakota/Center", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - ND (Oliver)"},
	{CountryCode: "US", Zone: "America/North_Dakota/New_Salem", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - ND (Morton rural)"},
	{CountryCode: "US", Zone: "America/North_Dakota/Beulah", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - ND (Mercer)"},
	{CountryCode: "US", Zone: "America/Denver", Abbr: []string{"MDT", "MST"}, CountryName: "United States", Comments: "Mountain (most areas)"},
	{CountryCode: "US", Zone: "America/Boise", Abbr: []string{"MDT", "MST"}, CountryName: "United States", Comments: "Mountain - ID (south); OR (east)"},
	{CountryCode: "US", Zone: "America/Phoenix", Abbr: []string{"MST"}, CountryName: "United States", Comments: "MST - Arizona (except Navajo)"},
	{CountryCode: "US", Zone: "America/Los_Angeles", Abbr: []string{"PDT", "PST"}, CountryName: "United States", Comments: "Pacific"},
	{CountryCode: "US", Zone: "America/Anchorage", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska (most areas)"},
	{CountryCode: "US", Zone: "America/Metlakatla", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska - Annette Island"},
	{CountryCode: "US", Zone: "America/Indiana/Tell_City", Abbr: []string{"CDT", "CST"}, CountryName: "United States", Comments: "Central - IN (Perry)"},
	{CountryCode: "US", Zone: "America/Juneau", Abbr: []string{"AKDT", "AKST"}, CountryName: "United States", Comments: "Alaska - Juneau area"},
	{CountryCode: "UY", Zone: "America/Montevideo", Abbr: []string(nil), CountryName: "Uruguay", Comments: ""},
	{CountryCode: "UZ", Zone: "Asia/Samarkand", Abbr: []string(nil), CountryName: "Uzbekistan", Comments: "Uzbekistan (west)"},
	{CountryCode: "UZ", Zone: "Asia/Tashkent", Abbr: []string(nil), CountryName: "Uzbekistan", Comments: "Uzbekistan (east)"},
	{CountryCode: "VU", Zone: "Pacific/Efate", Abbr: []string(nil), CountryName: "Vanuatu", Comments: ""},
	{CountryCode: "VA", Zone: "Europe/Rome", Abbr: []string{"CEST", "CET"}, CountryName: "Vatican City", Comments: ""},
	{CountryCode: "VE", Zone: "America/Caracas", Abbr: []string(nil), CountryName: "Venezuela", Comments: ""},
	{CountryCode: "VN", Zone: "Asia/Bangkok", Abbr: []string(nil), CountryName: "Vietnam", Comments: "Indochina (most areas)"},
	{CountryCode: "VN", Zone: "Asia/Ho_Chi_Minh", Abbr: []string(nil), CountryName: "Vietnam", Comments: "Vietnam (south)"},
	{CountryCode: "VG", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Virgin Islands (UK)", Comments: ""},
	{CountryCode: "VI", Zone: "America/Port_of_Spain", Abbr: []string{"AST"}, CountryName: "Virgin Islands (US)", Comments: ""},
	{CountryCode: "WF", Zone: "Pacific/Wallis", Abbr: []string(nil), CountryName: "Wallis & Futuna", Comments: ""},
	{CountryCode: "EH", Zone: "Africa/El_Aaiun", Abbr: []string(nil), CountryName: "Western Sahara", Comments: ""},
	{CountryCode: "YE", Zone: "Asia/Riyadh", Abbr: []string(nil), CountryName: "Yemen", Comments: ""},
	{CountryCode: "ZM", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Zambia", Comments: "Central Africa Time"},
	{CountryCode: "ZW", Zone: "Africa/Maputo", Abbr: []string{"CAT"}, CountryName: "Zimbabwe", Comments: "Central Africa Time"},
}
