package main

import (
	"fmt"
	"strings"
)

// composeStopGracePeriod is the auth server's longest clean stop (15s to drain its listeners, 15s
// for the work handed off after responses, 20s for the cleanup worker) plus 10s of headroom, given
// to both services, since it is a ceiling and the admin console exits once its 15s drain is done.
// Compose's default is 10s. It restates the auth server's budget, which a test in that server's
// unit tier holds the goldens to (#390 decisions 3 and 4).
const composeStopGracePeriod = "60s"

// composeAuthServerStartPeriod is how long the auth server's healthcheck failures do not count while
// it opens, migrates and seeds the database, the same five minutes as the Kubernetes startup probe.
// The admin console waits for that healthcheck, so a shorter window left it never started (#390
// decision 5).
const composeAuthServerStartPeriod = "300s"

func generateDockerCompose(config *Config) string {
	var sb strings.Builder

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Run: docker compose up -d\n\n")
	sb.WriteString("services:\n\n")

	if config.Engine.hasServer {
		sb.WriteString(generateDBService(config))
	}

	sb.WriteString(generateAuthServerService(config))
	sb.WriteString(generateAdminConsoleService(config))

	sb.WriteString("\nvolumes:\n")
	fmt.Fprintf(&sb, "  %s:\n", config.Engine.volume)

	sb.WriteString("\nnetworks:\n")
	sb.WriteString("  goiabada-network:\n")

	return sb.String()
}

func generateDBService(config *Config) string {
	var sb strings.Builder
	e := config.Engine

	fmt.Fprintf(&sb, "  %s:\n", e.composeService)
	for _, line := range e.imageComment {
		fmt.Fprintf(&sb, "    # %s\n", line)
	}
	fmt.Fprintf(&sb, "    image: %s\n", e.image)
	sb.WriteString("    restart: unless-stopped\n")
	sb.WriteString("    volumes:\n")
	fmt.Fprintf(&sb, "      - %s:%s\n", e.volume, e.mount)
	sb.WriteString("    environment:\n")
	for _, line := range e.composeEnvironment(config.DBPassword) {
		fmt.Fprintf(&sb, "      %s\n", line)
	}
	sb.WriteString("    healthcheck:\n")
	fmt.Fprintf(&sb, "      test: [\"CMD-SHELL\", %s]\n", composeQuote(e.healthcheck))
	fmt.Fprintf(&sb, "      interval: %s\n", e.healthInterval)
	fmt.Fprintf(&sb, "      timeout: %s\n", e.healthTimeout)
	sb.WriteString("      retries: 20\n")
	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n\n")

	return sb.String()
}

func generateAuthServerService(config *Config) string {
	var sb strings.Builder

	behindProxy := config.Deployment.behindProxy

	authInternalURL := "http://goiabada-authserver:9090"

	sb.WriteString("  goiabada-authserver:\n")
	fmt.Fprintf(&sb, "    image: leodip/goiabada:authserver-%s\n", imageTag)
	sb.WriteString("    restart: unless-stopped\n")
	writeStopGracePeriod(&sb,
		"Up to 50s to stop cleanly (15s to drain requests, 15s for work handed off after",
		"responses, 20s for the cleanup worker) plus 10s of headroom; Compose's default is 10s.")
	writeHardening(&sb,
		"/tmp is a tmpfs, where SQLite writes the temporary files of large sorts and VACUUM, and",
		"where Go spills an upload larger than it keeps in memory.")

	if config.Engine.hasServer {
		sb.WriteString("    depends_on:\n")
		fmt.Fprintf(&sb, "      %s:\n", config.Engine.composeService)
		sb.WriteString("        condition: service_healthy\n")
	}

	// Always expose ports - for local testing expose to all interfaces,
	// for production bind to localhost only (nginx access)
	sb.WriteString("    ports:\n")
	if behindProxy {
		sb.WriteString("      - 127.0.0.1:9090:9090\n")
	} else {
		sb.WriteString("      - 9090:9090\n")
	}

	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n")
	sb.WriteString("    healthcheck:\n")
	sb.WriteString("      test: [\"CMD\", \"wget\", \"--spider\", \"http://localhost:9090/health\"]\n")
	sb.WriteString("      interval: 10s\n")
	sb.WriteString("      timeout: 5s\n")
	sb.WriteString("      retries: 3\n")
	sb.WriteString("      # Up to 5 minutes for a first start to seed the database, or an upgrade to migrate it;\n")
	sb.WriteString("      # failures in that window do not count, and the first success ends it.\n")
	fmt.Fprintf(&sb, "      start_period: %s\n", composeAuthServerStartPeriod)

	if !config.Engine.hasServer {
		sb.WriteString("    volumes:\n")
		fmt.Fprintf(&sb, "      - %s:%s\n", config.Engine.volume, config.Engine.mount)
	}

	sb.WriteString("    environment:\n")
	sb.WriteString("      - TZ=UTC\n")
	writeComposeVariable(&sb, "GOIABADA_ADMIN_EMAIL", config.AdminEmail)
	writeComposeVariable(&sb, "GOIABADA_ADMIN_PASSWORD", config.AdminPassword)
	sb.WriteString("      - GOIABADA_APPNAME=Goiabada\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", authInternalURL)
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTP=0.0.0.0\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTP=9090\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTPS=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTPS=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_CERTFILE=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_KEYFILE=\n")
	writeComposeTrust(&sb, behindProxy, "AUTHSERVER")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=true\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_LEVEL=info\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_FORMAT=text\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_SQL=false\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_STATICDIR=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_TEMPLATEDIR=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_DEBUG_API_REQUESTS=false\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY", config.AuthSessionAuthKey)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY", config.AuthSessionEncKey)
	writeComposeVariable(&sb, "GOIABADA_AES_ENCRYPTION_KEY", config.AESEncryptionKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeComposeVariable(&sb, "GOIABADA_DB_TYPE", config.Engine.name)

	if config.Engine.hasServer {
		writeComposeVariable(&sb, "GOIABADA_DB_USERNAME", config.Engine.defaultUser)
		writeComposeVariable(&sb, "GOIABADA_DB_PASSWORD", config.DBPassword)
		writeComposeVariable(&sb, "GOIABADA_DB_HOST", config.Engine.composeService)
		writeComposeVariable(&sb, "GOIABADA_DB_PORT", config.Engine.defaultPort)
		sb.WriteString("      - GOIABADA_DB_NAME=goiabada\n")
	} else {
		writeComposeVariable(&sb, "GOIABADA_DB_DSN", config.Engine.mount+"/goiabada.db")
	}

	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	sb.WriteString("\n")

	return sb.String()
}

func generateAdminConsoleService(config *Config) string {
	var sb strings.Builder

	behindProxy := config.Deployment.behindProxy

	authInternalURL := "http://goiabada-authserver:9090"

	sb.WriteString("  goiabada-adminconsole:\n")
	fmt.Fprintf(&sb, "    image: leodip/goiabada:adminconsole-%s\n", imageTag)
	sb.WriteString("    restart: unless-stopped\n")
	writeStopGracePeriod(&sb,
		"The auth server's value: this service stops within its 15s drain, and a grace",
		"period is a ceiling, not a wait. Compose's default is 10s.")
	writeHardening(&sb, "/tmp is a tmpfs, where Go spills an upload larger than it keeps in memory.")
	sb.WriteString("    depends_on:\n")
	sb.WriteString("      goiabada-authserver:\n")
	sb.WriteString("        condition: service_healthy\n")

	// Always expose ports - for local testing expose to all interfaces,
	// for production bind to localhost only (nginx access)
	sb.WriteString("    ports:\n")
	if behindProxy {
		sb.WriteString("      - 127.0.0.1:9091:9091\n")
	} else {
		sb.WriteString("      - 9091:9091\n")
	}

	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n")
	sb.WriteString("    environment:\n")
	sb.WriteString("      - TZ=UTC\n")
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY", config.AdminSessionAuthKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY", config.AdminSessionEncKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTP=0.0.0.0\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTP=9091\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTPS=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTPS=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_CERTFILE=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_KEYFILE=\n")
	writeComposeTrust(&sb, behindProxy, "ADMINCONSOLE")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=true\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_LEVEL=info\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_FORMAT=text\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_STATICDIR=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_TEMPLATEDIR=\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", authInternalURL)
	sb.WriteString("\n")

	return sb.String()
}

// writeComposeTrust writes one service's proxy trust. Behind the reverse proxy on the host it
// trusts one hop with an explicit empty list, under the comment saying why that is sound: nginx on
// the host and a Cloudflare Tunnel each append the address they received the connection from. A
// list naming 127.0.0.1 would not do, since a Compose service's peer is the Compose network's
// gateway, so the headers would be ignored and every request resolved to it (#396 decision 6).
// server is the variables' infix, AUTHSERVER or ADMINCONSOLE.
func writeComposeTrust(sb *strings.Builder, behindProxy bool, server string) {
	prefix := "GOIABADA_" + server + "_"
	if !behindProxy {
		writeComposeVariable(sb, prefix+"TRUST_PROXY_HEADERS", "false")
		return
	}
	sb.WriteString("      # The reverse proxy on this host, nginx or a Cloudflare Tunnel, appends the address it\n")
	sb.WriteString("      # received each connection from to X-Forwarded-For, so trusting one hop, the rightmost\n")
	sb.WriteString("      # entry, resolves the client with no list. Set the list only for a second proxy hop in\n")
	sb.WriteString("      # front of that one, naming every hop, this service's peer included: the Compose\n")
	sb.WriteString("      # network's gateway, not 127.0.0.1. For Cloudflare's proxy in front of nginx, have nginx\n")
	sb.WriteString("      # resolve Cloudflare instead: https://goiabada.dev/production-deployment/cloudflare-nginx/\n")
	writeComposeVariable(sb, prefix+"TRUST_PROXY_HEADERS", "true")
	writeComposeVariable(sb, prefix+"TRUSTED_PROXIES", "")
}

// writeStopGracePeriod writes a service's stop_grace_period under the comment lines saying what it
// covers for that service.
func writeStopGracePeriod(sb *strings.Builder, comment ...string) {
	for _, line := range comment {
		fmt.Fprintf(sb, "    # %s\n", line)
	}
	fmt.Fprintf(sb, "    stop_grace_period: %s\n", composeStopGracePeriod)
}

// writeHardening writes a service's posture, the Compose counterpart of the manifest's restricted
// securityContext: the images' own uid and gid, no capabilities, no privileges gained through a
// setuid binary, and a read-only root with a tmpfs at /tmp, under the comment lines saying what
// writes there in that service. Docker applies its default seccomp profile without being asked
// (#396 decisions 1 and 2).
func writeHardening(sb *strings.Builder, tmpComment ...string) {
	sb.WriteString("    # Runs as the image's own uid and gid, 10001, with every capability dropped, no privilege\n")
	sb.WriteString("    # gained through a setuid binary, and a read-only root.\n")
	for _, line := range tmpComment {
		fmt.Fprintf(sb, "    # %s\n", line)
	}
	sb.WriteString("    user: \"10001:10001\"\n")
	sb.WriteString("    cap_drop:\n")
	sb.WriteString("      - ALL\n")
	sb.WriteString("    security_opt:\n")
	sb.WriteString("      - no-new-privileges:true\n")
	sb.WriteString("    read_only: true\n")
	sb.WriteString("    tmpfs:\n")
	sb.WriteString("      - /tmp\n")
}

// writeComposeVariable writes one entry of a service's list-form environment, quoted whole, so
// the `=` is inside the scalar and the value is read back as it is (compose-spec, services.
// environment; composeQuote).
func writeComposeVariable(sb *strings.Builder, name, value string) {
	fmt.Fprintf(sb, "      - %s\n", composeQuote(name+"="+value))
}
