package main

import (
	"fmt"
	"strings"
)

func generateDockerCompose(config *Config) string {
	var sb strings.Builder

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Run: docker compose up -d\n\n")
	sb.WriteString("services:\n\n")

	if config.Engine.hasServer {
		sb.WriteString(generateDBService(config))
	}

	sb.WriteString(generateAuthServerService(config))
	sb.WriteString(generateAdminConsoleService(config))

	sb.WriteString("\nvolumes:\n")
	fmt.Fprintf(&sb, "  %s:\n", config.Engine.volume)

	sb.WriteString("\nnetworks:\n")
	sb.WriteString("  goiabada-network:\n")

	return sb.String()
}

func generateDBService(config *Config) string {
	var sb strings.Builder
	e := config.Engine

	fmt.Fprintf(&sb, "  %s:\n", e.composeService)
	fmt.Fprintf(&sb, "    image: %s\n", e.image)
	sb.WriteString("    restart: unless-stopped\n")
	sb.WriteString("    volumes:\n")
	fmt.Fprintf(&sb, "      - %s:%s\n", e.volume, e.mount)
	sb.WriteString("    environment:\n")
	for _, line := range e.composeEnvironment(config.DBPassword) {
		fmt.Fprintf(&sb, "      %s\n", line)
	}
	sb.WriteString("    healthcheck:\n")
	fmt.Fprintf(&sb, "      test: [\"CMD-SHELL\", %s]\n", composeQuote(e.healthcheck))
	fmt.Fprintf(&sb, "      interval: %s\n", e.healthInterval)
	fmt.Fprintf(&sb, "      timeout: %s\n", e.healthTimeout)
	sb.WriteString("      retries: 20\n")
	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n\n")

	return sb.String()
}

func generateAuthServerService(config *Config) string {
	var sb strings.Builder

	behindProxy := config.Deployment.behindProxy
	trustProxyHeaders := "false"
	if behindProxy {
		trustProxyHeaders = "true"
	}

	authInternalURL := "http://goiabada-authserver:9090"

	sb.WriteString("  goiabada-authserver:\n")
	fmt.Fprintf(&sb, "    image: leodip/goiabada:authserver-%s\n", imageTag)
	sb.WriteString("    restart: unless-stopped\n")

	if config.Engine.hasServer {
		sb.WriteString("    depends_on:\n")
		fmt.Fprintf(&sb, "      %s:\n", config.Engine.composeService)
		sb.WriteString("        condition: service_healthy\n")
	}

	// Always expose ports - for local testing expose to all interfaces,
	// for production bind to localhost only (nginx access)
	sb.WriteString("    ports:\n")
	if behindProxy {
		sb.WriteString("      - 127.0.0.1:9090:9090\n")
	} else {
		sb.WriteString("      - 9090:9090\n")
	}

	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n")
	sb.WriteString("    healthcheck:\n")
	sb.WriteString("      test: [\"CMD\", \"wget\", \"--spider\", \"http://localhost:9090/health\"]\n")
	sb.WriteString("      interval: 10s\n")
	sb.WriteString("      timeout: 5s\n")
	sb.WriteString("      retries: 3\n")
	sb.WriteString("      start_period: 10s\n")

	if !config.Engine.hasServer {
		sb.WriteString("    volumes:\n")
		fmt.Fprintf(&sb, "      - %s:%s\n", config.Engine.volume, config.Engine.mount)
	}

	sb.WriteString("    environment:\n")
	sb.WriteString("      - TZ=UTC\n")
	writeComposeVariable(&sb, "GOIABADA_ADMIN_EMAIL", config.AdminEmail)
	writeComposeVariable(&sb, "GOIABADA_ADMIN_PASSWORD", config.AdminPassword)
	sb.WriteString("      - GOIABADA_APPNAME=Goiabada\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", authInternalURL)
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTP=0.0.0.0\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTP=9090\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_HOST_HTTPS=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LISTEN_PORT_HTTPS=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_CERTFILE=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_KEYFILE=\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_TRUST_PROXY_HEADERS", trustProxyHeaders)
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=true\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_LEVEL=info\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_FORMAT=text\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_LOG_SQL=false\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_STATICDIR=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_TEMPLATEDIR=\n")
	sb.WriteString("      - GOIABADA_AUTHSERVER_DEBUG_API_REQUESTS=false\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY", config.AuthSessionAuthKey)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY", config.AuthSessionEncKey)
	writeComposeVariable(&sb, "GOIABADA_AES_ENCRYPTION_KEY", config.AESEncryptionKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeComposeVariable(&sb, "GOIABADA_DB_TYPE", config.Engine.name)

	if config.Engine.hasServer {
		writeComposeVariable(&sb, "GOIABADA_DB_USERNAME", config.Engine.defaultUser)
		writeComposeVariable(&sb, "GOIABADA_DB_PASSWORD", config.DBPassword)
		writeComposeVariable(&sb, "GOIABADA_DB_HOST", config.Engine.composeService)
		writeComposeVariable(&sb, "GOIABADA_DB_PORT", config.Engine.defaultPort)
		sb.WriteString("      - GOIABADA_DB_NAME=goiabada\n")
	} else {
		writeComposeVariable(&sb, "GOIABADA_DB_DSN", config.Engine.mount+"/goiabada.db")
	}

	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	sb.WriteString("\n")

	return sb.String()
}

func generateAdminConsoleService(config *Config) string {
	var sb strings.Builder

	behindProxy := config.Deployment.behindProxy
	trustProxyHeaders := "false"
	if behindProxy {
		trustProxyHeaders = "true"
	}

	authInternalURL := "http://goiabada-authserver:9090"

	sb.WriteString("  goiabada-adminconsole:\n")
	fmt.Fprintf(&sb, "    image: leodip/goiabada:adminconsole-%s\n", imageTag)
	sb.WriteString("    restart: unless-stopped\n")
	sb.WriteString("    depends_on:\n")
	sb.WriteString("      goiabada-authserver:\n")
	sb.WriteString("        condition: service_healthy\n")

	// Always expose ports - for local testing expose to all interfaces,
	// for production bind to localhost only (nginx access)
	sb.WriteString("    ports:\n")
	if behindProxy {
		sb.WriteString("      - 127.0.0.1:9091:9091\n")
	} else {
		sb.WriteString("      - 9091:9091\n")
	}

	sb.WriteString("    networks:\n")
	sb.WriteString("      - goiabada-network\n")
	sb.WriteString("    environment:\n")
	sb.WriteString("      - TZ=UTC\n")
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY", config.AdminSessionAuthKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY", config.AdminSessionEncKey)
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTP=0.0.0.0\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTP=9091\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTPS=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTPS=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_CERTFILE=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_KEYFILE=\n")
	writeComposeVariable(&sb, "GOIABADA_ADMINCONSOLE_TRUST_PROXY_HEADERS", trustProxyHeaders)
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=true\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_LEVEL=info\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_LOG_FORMAT=text\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_STATICDIR=\n")
	sb.WriteString("      - GOIABADA_ADMINCONSOLE_TEMPLATEDIR=\n")
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	writeComposeVariable(&sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", authInternalURL)
	sb.WriteString("\n")

	return sb.String()
}

// writeComposeVariable writes one entry of a service's list-form environment, quoted whole, so
// the `=` is inside the scalar and the value is read back as it is (compose-spec, services.
// environment; composeQuote).
func writeComposeVariable(sb *strings.Builder, name, value string) {
	fmt.Fprintf(sb, "      - %s\n", composeQuote(name+"="+value))
}
