package main

import (
	"fmt"
	"strings"
)

func generateEnvFile(config *Config) string {
	var sb strings.Builder

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Environment file for native binary deployment\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage:\n")
	sb.WriteString("#   set -a && . ./goiabada.env && set +a && ./goiabada-authserver\n")
	sb.WriteString("#   set -a && . ./goiabada.env && set +a && ./goiabada-adminconsole\n")
	sb.WriteString("#\n")
	sb.WriteString("# Or with systemd, add EnvironmentFile=/path/to/goiabada.env\n")
	sb.WriteString("#\n")
	sb.WriteString("# IMPORTANT: The database must be empty for initial deployment.\n")
	sb.WriteString("# Goiabada will seed it with OAuth clients configured for the URLs below.\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Application settings\n")
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("GOIABADA_APPNAME=\"Goiabada\"\n")
	writeEnvVariable(&sb, "GOIABADA_ADMIN_EMAIL", config.AdminEmail)
	writeEnvVariable(&sb, "GOIABADA_ADMIN_PASSWORD", config.AdminPassword)
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Database settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_DB_TYPE", config.Engine.name)
	if !config.Engine.hasServer {
		sb.WriteString("GOIABADA_DB_DSN=\"./goiabada.db\"\n")
	} else {
		writeEnvVariable(&sb, "GOIABADA_DB_HOST", config.DBHost)
		writeEnvVariable(&sb, "GOIABADA_DB_PORT", config.DBPort)
		writeEnvVariable(&sb, "GOIABADA_DB_NAME", config.DBName)
		writeEnvVariable(&sb, "GOIABADA_DB_USERNAME", config.DBUsername)
		writeEnvVariable(&sb, "GOIABADA_DB_PASSWORD", config.DBPassword)
	}
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Auth server settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	sb.WriteString("GOIABADA_AUTHSERVER_LISTEN_HOST_HTTP=\"0.0.0.0\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LISTEN_PORT_HTTP=\"9090\"\n")
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY", config.AuthSessionAuthKey)
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY", config.AuthSessionEncKey)
	writeEnvVariable(&sb, "GOIABADA_AES_ENCRYPTION_KEY", config.AESEncryptionKey)
	sb.WriteString("GOIABADA_AUTHSERVER_TRUST_PROXY_HEADERS=\"true\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=\"true\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_LEVEL=\"info\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_FORMAT=\"text\"\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Admin console settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	sb.WriteString("GOIABADA_ADMINCONSOLE_LISTEN_HOST_HTTP=\"0.0.0.0\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LISTEN_PORT_HTTP=\"9091\"\n")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY", config.AdminSessionAuthKey)
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY", config.AdminSessionEncKey)
	sb.WriteString("GOIABADA_ADMINCONSOLE_TRUST_PROXY_HEADERS=\"true\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=\"true\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_LEVEL=\"info\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_FORMAT=\"text\"\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# OAuth client for admin console\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", config.AuthServerURL)
	sb.WriteString("\n")

	return sb.String()
}

// writeEnvVariable writes one assignment, with no `export`: systemd's EnvironmentFile= reads the
// key up to the `=` and drops an assignment whose key is not a valid name, so `export KEY` lost
// every line, while `set -a` before `.` exports each assignment to the servers the shell starts
// (#430). The value goes through envQuote, which both read back as it is.
func writeEnvVariable(sb *strings.Builder, name, value string) {
	fmt.Fprintf(sb, "%s=%s\n", name, envQuote(value))
}
