package main

import (
	"fmt"
	"strconv"
	"strings"
)

func generateEnvFile(config *Config, paths outputPaths) string {
	var sb strings.Builder

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Environment file for native binary deployment\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage:\n")
	fmt.Fprintf(&sb, "#   %s\n", nativeStartCommand(paths, "goiabada-authserver"))
	fmt.Fprintf(&sb, "#   %s\n", nativeStartCommand(paths, "goiabada-adminconsole"))
	sb.WriteString("#\n")
	fmt.Fprintf(&sb, "# %s\n", systemdEnvironmentFileHint(paths))
	sb.WriteString("#\n")
	sb.WriteString("# IMPORTANT: The database must be empty for initial deployment.\n")
	sb.WriteString("# Goiabada will seed it with OAuth clients configured for the URLs below.\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Application settings\n")
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("GOIABADA_APPNAME=\"Goiabada\"\n")
	writeEnvVariable(&sb, "GOIABADA_ADMIN_EMAIL", config.AdminEmail)
	writeEnvVariable(&sb, "GOIABADA_ADMIN_PASSWORD", config.AdminPassword)
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Database settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_DB_TYPE", config.Engine.name)
	if !config.Engine.hasServer {
		sb.WriteString("GOIABADA_DB_DSN=\"./goiabada.db\"\n")
	} else {
		writeEnvVariable(&sb, "GOIABADA_DB_HOST", config.DBHost)
		writeEnvVariable(&sb, "GOIABADA_DB_PORT", config.DBPort)
		writeEnvVariable(&sb, "GOIABADA_DB_NAME", config.DBName)
		writeEnvVariable(&sb, "GOIABADA_DB_USERNAME", config.DBUsername)
		writeEnvVariable(&sb, "GOIABADA_DB_PASSWORD", config.DBPassword)
	}
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Auth server settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_BASEURL", config.AuthServerURL)
	writeEnvListenerAndTrust(&sb, config, "AUTHSERVER", "9090", "9443")
	for _, line := range config.rateLimiterComment() {
		fmt.Fprintf(&sb, "# %s\n", line)
	}
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_RATELIMITER_ENABLED", strconv.FormatBool(config.RateLimiter))
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY", config.AuthSessionAuthKey)
	writeEnvVariable(&sb, "GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY", config.AuthSessionEncKey)
	for _, line := range aesKeyComment() {
		fmt.Fprintf(&sb, "# %s\n", line)
	}
	writeEnvVariable(&sb, "GOIABADA_AES_ENCRYPTION_KEY", config.AESEncryptionKey)
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_HTTP_REQUESTS=\"true\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_LEVEL=\"info\"\n")
	sb.WriteString("GOIABADA_AUTHSERVER_LOG_FORMAT=\"text\"\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Admin console settings\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_BASEURL", config.AdminConsoleURL)
	writeEnvListenerAndTrust(&sb, config, "ADMINCONSOLE", "9091", "9444")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY", config.AdminSessionAuthKey)
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY", config.AdminSessionEncKey)
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_HTTP_REQUESTS=\"true\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_LEVEL=\"info\"\n")
	sb.WriteString("GOIABADA_ADMINCONSOLE_LOG_FORMAT=\"text\"\n")
	sb.WriteString("\n")

	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# OAuth client for admin console\n")
	sb.WriteString("# =============================================================================\n")
	writeEnvVariable(&sb, "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET", config.OAuthClientSecret)
	writeEnvInternalURL(&sb, config)
	sb.WriteString("\n")

	return sb.String()
}

// nativeLoopbackAuthServerURL is where the admin console reaches the auth server when a reverse proxy
// on the same machine fronts both: the auth server's own listener, which listens on 127.0.0.1.
const nativeLoopbackAuthServerURL = "http://127.0.0.1:9090"

// writeEnvInternalURL writes the URL the admin console reaches the auth server at, under the comment
// saying what that hop is. With a proxy on this machine it is the auth server's loopback listener,
// as the Compose file's is the auth server's service: the admin console waits for the auth server
// before it listens (#542), and through the public URL it would wait for the proxy, DNS and the
// certificates of a later step, or forever on a host that cannot reach its own public address.
// Without a proxy the auth server serves HTTPS itself on every interface, and plain HTTP goes once
// it does, so the public URL is the one address that keeps working.
func writeEnvInternalURL(sb *strings.Builder, config *Config) {
	if config.LocalProxy {
		sb.WriteString("# The admin console reaches the auth server over loopback: plain HTTP that never leaves\n")
		sb.WriteString("# this machine. Change it too if you change the auth server's listen host or port.\n")
		writeEnvVariable(sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", nativeLoopbackAuthServerURL)
		return
	}
	sb.WriteString("# The admin console reaches the auth server at its public URL, so it waits to listen\n")
	sb.WriteString("# until the auth server serves HTTPS there.\n")
	writeEnvVariable(sb, "GOIABADA_AUTHSERVER_INTERNALBASEURL", config.AuthServerURL)
}

// writeEnvListenerAndTrust writes one server's HTTP listener and its proxy trust, which the answer
// to the local proxy question decides together, under the comment saying whom it trusts (#396
// decision 7). server is the variables' infix, AUTHSERVER or ADMINCONSOLE, and httpsPort the
// server's own default HTTPS port, which the comment names.
func writeEnvListenerAndTrust(sb *strings.Builder, config *Config, server, port, httpsPort string) {
	prefix := "GOIABADA_" + server + "_"
	if config.LocalProxy {
		sb.WriteString("# A reverse proxy on this machine forwards to this server, so it listens on 127.0.0.1\n")
		sb.WriteString("# alone, and trusts the forwarded headers of a connection from 127.0.0.1 alone. For a\n")
		sb.WriteString("# proxy on another host, set the listen host to an address that host reaches, and the\n")
		sb.WriteString("# trusted proxies to that host's address.\n")
		fmt.Fprintf(sb, "%sLISTEN_HOST_HTTP=\"127.0.0.1\"\n", prefix)
		fmt.Fprintf(sb, "%sLISTEN_PORT_HTTP=\"%s\"\n", prefix, port)
		sb.WriteString("# The client is the rightmost X-Forwarded-For entry the proxy appends, read only from a\n")
		sb.WriteString("# connection that comes from 127.0.0.1.\n")
		fmt.Fprintf(sb, "%sTRUST_PROXY_HEADERS=\"true\"\n", prefix)
		fmt.Fprintf(sb, "%sTRUSTED_PROXIES=\"127.0.0.1\"\n", prefix)
		return
	}
	sb.WriteString("# No reverse proxy fronts this server: it listens on every interface and trusts no\n")
	sb.WriteString("# forwarded header, so each client is the address it connects from. It serves plain HTTP\n")
	fmt.Fprintf(sb, "# until you set %sCERTFILE and %sKEYFILE, which turn\n", prefix, prefix)
	fmt.Fprintf(sb, "# on HTTPS at 0.0.0.0:%s (%sLISTEN_HOST_HTTPS and _LISTEN_PORT_HTTPS\n", httpsPort, prefix)
	sb.WriteString("# change it); then set the HTTP listen host below empty to stop serving plain HTTP.\n")
	fmt.Fprintf(sb, "%sLISTEN_HOST_HTTP=\"0.0.0.0\"\n", prefix)
	fmt.Fprintf(sb, "%sLISTEN_PORT_HTTP=\"%s\"\n", prefix, port)
	fmt.Fprintf(sb, "%sTRUST_PROXY_HEADERS=\"false\"\n", prefix)
}

// writeEnvVariable writes one assignment, with no `export`: systemd's EnvironmentFile= reads the
// key up to the `=` and drops an assignment whose key is not a valid name, so `export KEY` lost
// every line, while `set -a` before `.` exports each assignment to the servers the shell starts
// (#430). The value goes through envQuote, which both read back as it is.
func writeEnvVariable(sb *strings.Builder, name, value string) {
	fmt.Fprintf(sb, "%s=%s\n", name, envQuote(value))
}
