package main

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// The grace periods restate each server's shutdown budget, which this module cannot read: the wizard
// imports only core, and the budgets are the servers' own unexported constants. A test in each
// server's unit tier holds the goldens, the generator's output, to that server's budget, so raising
// a constant fails there until these follow (#390 decision 3).
const (
	// preStopPauseSeconds holds each container for this long before it is signalled, while the
	// gateway learns the pod is going; both servers close their listener on the signal (#390
	// decision 2).
	preStopPauseSeconds = 5

	// terminationGracePeriodSeconds is the pause, plus the auth server's longest clean stop (15s to
	// drain its listeners, 15s for the work handed off after responses, 20s for the cleanup worker),
	// plus 10s of headroom. One value for both Deployments, since it is a ceiling and the admin
	// console exits once its 15s drain is done (#390 decision 4).
	terminationGracePeriodSeconds = preStopPauseSeconds + 60
)

func generateKubernetesManifests(config *Config) string {
	var sb strings.Builder

	ns := config.K8sNamespace

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Apply with: kubectl apply -f goiabada-k8s.yaml\n")
	sb.WriteString("#\n")
	sb.WriteString("# IMPORTANT: The database must be empty for initial deployment.\n")
	sb.WriteString("# Goiabada will seed it with OAuth clients configured for the URLs below.\n")
	sb.WriteString("# If redeploying with different URLs, use a fresh database.\n")
	sb.WriteString("\n")

	// Namespace
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Namespace\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(&sb, "  name: %s\n", yamlQuote(ns))
	sb.WriteString("\n")

	// Secret
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Secret\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-secrets\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("type: Opaque\n")
	// base64 spells any bytes in characters YAML reads as they are, so the Secret's values are
	// the one set of interpolated values not written through yamlQuote.
	sb.WriteString("data:\n")
	fmt.Fprintf(&sb, "  db-password: %s\n", base64Encode(config.DBPassword))
	fmt.Fprintf(&sb, "  admin-password: %s\n", base64Encode(config.AdminPassword))
	fmt.Fprintf(&sb, "  auth-session-auth-key: %s\n", base64Encode(config.AuthSessionAuthKey))
	fmt.Fprintf(&sb, "  auth-session-enc-key: %s\n", base64Encode(config.AuthSessionEncKey))
	fmt.Fprintf(&sb, "  admin-session-auth-key: %s\n", base64Encode(config.AdminSessionAuthKey))
	fmt.Fprintf(&sb, "  admin-session-enc-key: %s\n", base64Encode(config.AdminSessionEncKey))
	fmt.Fprintf(&sb, "  aes-encryption-key: %s\n", base64Encode(config.AESEncryptionKey))
	fmt.Fprintf(&sb, "  oauth-client-secret: %s\n", base64Encode(config.OAuthClientSecret))
	sb.WriteString("\n")

	// ConfigMap
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: ConfigMap\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-config\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("data:\n")
	sb.WriteString("  GOIABADA_APPNAME: \"Goiabada\"\n")
	fmt.Fprintf(&sb, "  GOIABADA_ADMIN_EMAIL: %s\n", yamlQuote(config.AdminEmail))
	fmt.Fprintf(&sb, "  GOIABADA_AUTHSERVER_BASEURL: %s\n", yamlQuote(config.AuthServerURL))
	sb.WriteString("  GOIABADA_AUTHSERVER_INTERNALBASEURL: \"http://goiabada-authserver:9090\"\n")
	fmt.Fprintf(&sb, "  GOIABADA_ADMINCONSOLE_BASEURL: %s\n", yamlQuote(config.AdminConsoleURL))
	sb.WriteString("  GOIABADA_AUTHSERVER_TRUST_PROXY_HEADERS: \"true\"\n")
	sb.WriteString("  GOIABADA_ADMINCONSOLE_TRUST_PROXY_HEADERS: \"true\"\n")
	fmt.Fprintf(&sb, "  GOIABADA_DB_TYPE: %s\n", yamlQuote(config.Engine.name))
	fmt.Fprintf(&sb, "  GOIABADA_DB_HOST: %s\n", yamlQuote(config.DBHost))
	fmt.Fprintf(&sb, "  GOIABADA_DB_PORT: %s\n", yamlQuote(config.DBPort))
	fmt.Fprintf(&sb, "  GOIABADA_DB_NAME: %s\n", yamlQuote(config.DBName))
	fmt.Fprintf(&sb, "  GOIABADA_DB_USERNAME: %s\n", yamlQuote(config.DBUsername))
	sb.WriteString("\n")

	// Auth Server Deployment
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: apps/v1\n")
	sb.WriteString("kind: Deployment\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-authserver\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  replicas: 1\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    matchLabels:\n")
	sb.WriteString("      app: goiabada-authserver\n")
	sb.WriteString("  template:\n")
	sb.WriteString("    metadata:\n")
	sb.WriteString("      labels:\n")
	sb.WriteString("        app: goiabada-authserver\n")
	sb.WriteString("    spec:\n")
	writeTerminationGracePeriod(&sb, "Set lower, it cuts the cleanup worker short first.")
	sb.WriteString("      containers:\n")
	sb.WriteString("      - name: authserver\n")
	fmt.Fprintf(&sb, "        image: leodip/goiabada:authserver-%s\n", imageTag)
	sb.WriteString("        ports:\n")
	sb.WriteString("        - containerPort: 9090\n")
	sb.WriteString("        envFrom:\n")
	sb.WriteString("        - configMapRef:\n")
	sb.WriteString("            name: goiabada-config\n")
	sb.WriteString("        env:\n")
	sb.WriteString("        - name: GOIABADA_ADMIN_PASSWORD\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-password\n")
	sb.WriteString("        - name: GOIABADA_DB_PASSWORD\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: db-password\n")
	sb.WriteString("        - name: GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: auth-session-auth-key\n")
	sb.WriteString("        - name: GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: auth-session-enc-key\n")
	sb.WriteString("        - name: GOIABADA_AES_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: aes-encryption-key\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: oauth-client-secret\n")
	sb.WriteString("        livenessProbe:\n")
	sb.WriteString("          httpGet:\n")
	sb.WriteString("            path: /health\n")
	sb.WriteString("            port: 9090\n")
	sb.WriteString("          initialDelaySeconds: 10\n")
	sb.WriteString("          periodSeconds: 10\n")
	sb.WriteString("        readinessProbe:\n")
	sb.WriteString("          httpGet:\n")
	sb.WriteString("            path: /health\n")
	sb.WriteString("            port: 9090\n")
	sb.WriteString("          initialDelaySeconds: 5\n")
	sb.WriteString("          periodSeconds: 5\n")
	writePreStopPause(&sb)
	sb.WriteString("        resources:\n")
	sb.WriteString("          requests:\n")
	sb.WriteString("            memory: \"128Mi\"\n")
	sb.WriteString("            cpu: \"100m\"\n")
	sb.WriteString("          limits:\n")
	sb.WriteString("            memory: \"512Mi\"\n")
	sb.WriteString("            cpu: \"500m\"\n")
	sb.WriteString("\n")

	// Admin Console Deployment
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: apps/v1\n")
	sb.WriteString("kind: Deployment\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-adminconsole\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  replicas: 1\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    matchLabels:\n")
	sb.WriteString("      app: goiabada-adminconsole\n")
	sb.WriteString("  template:\n")
	sb.WriteString("    metadata:\n")
	sb.WriteString("      labels:\n")
	sb.WriteString("        app: goiabada-adminconsole\n")
	sb.WriteString("    spec:\n")
	writeTerminationGracePeriod(&sb,
		"The auth server's value: this server stops within its 15s drain, and a grace period",
		"is a ceiling, not a wait.")
	sb.WriteString("      containers:\n")
	sb.WriteString("      - name: adminconsole\n")
	fmt.Fprintf(&sb, "        image: leodip/goiabada:adminconsole-%s\n", imageTag)
	sb.WriteString("        ports:\n")
	sb.WriteString("        - containerPort: 9091\n")
	sb.WriteString("        envFrom:\n")
	sb.WriteString("        - configMapRef:\n")
	sb.WriteString("            name: goiabada-config\n")
	sb.WriteString("        env:\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: oauth-client-secret\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-session-auth-key\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-session-enc-key\n")
	sb.WriteString("        livenessProbe:\n")
	sb.WriteString("          httpGet:\n")
	sb.WriteString("            path: /health\n")
	sb.WriteString("            port: 9091\n")
	sb.WriteString("          initialDelaySeconds: 10\n")
	sb.WriteString("          periodSeconds: 10\n")
	sb.WriteString("        readinessProbe:\n")
	sb.WriteString("          httpGet:\n")
	sb.WriteString("            path: /health\n")
	sb.WriteString("            port: 9091\n")
	sb.WriteString("          initialDelaySeconds: 5\n")
	sb.WriteString("          periodSeconds: 5\n")
	writePreStopPause(&sb)
	sb.WriteString("        resources:\n")
	sb.WriteString("          requests:\n")
	sb.WriteString("            memory: \"128Mi\"\n")
	sb.WriteString("            cpu: \"100m\"\n")
	sb.WriteString("          limits:\n")
	sb.WriteString("            memory: \"512Mi\"\n")
	sb.WriteString("            cpu: \"500m\"\n")
	sb.WriteString("\n")

	// Services
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Service\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-authserver\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    app: goiabada-authserver\n")
	sb.WriteString("  ports:\n")
	sb.WriteString("  - port: 9090\n")
	sb.WriteString("    targetPort: 9090\n")
	sb.WriteString("\n")

	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Service\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-adminconsole\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    app: goiabada-adminconsole\n")
	sb.WriteString("  ports:\n")
	sb.WriteString("  - port: 9091\n")
	sb.WriteString("    targetPort: 9091\n")
	sb.WriteString("\n")

	// Routing is Gateway API rather than Ingress: the one controller the Ingresses were written
	// for, ingress-nginx, is retired and gets no more security fixes, and SIG Network points its
	// users at Gateway API (kubernetes.io blog, 2025-11-11). Nothing below names an
	// implementation except gatewayClassName, which the completion message has the operator
	// create for Envoy Gateway (#430).
	authHost := hostOf(config.AuthServerURL)
	adminHost := hostOf(config.AdminConsoleURL)

	// The Gateway: plain HTTP for the redirect and for cert-manager's HTTP-01 challenges, and one
	// HTTPS listener per host. cert-manager reads the annotation and issues each listener's
	// certificateRefs for its hostname (cert-manager docs, usage/gateway.md).
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: Gateway\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("  annotations:\n")
	sb.WriteString("    cert-manager.io/cluster-issuer: \"letsencrypt-prod\"\n")
	sb.WriteString("spec:\n")
	sb.WriteString("  gatewayClassName: eg\n")
	sb.WriteString("  listeners:\n")
	sb.WriteString("  - name: http\n")
	sb.WriteString("    protocol: HTTP\n")
	sb.WriteString("    port: 80\n")
	writeHTTPSListener(&sb, "auth-https", authHost, "goiabada-tls-auth")
	writeHTTPSListener(&sb, "admin-https", adminHost, "goiabada-tls-admin")
	sb.WriteString("\n")

	writeHTTPRoute(&sb, ns, "goiabada-authserver", "auth-https", authHost, 9090)
	sb.WriteString("\n")
	writeHTTPRoute(&sb, ns, "goiabada-adminconsole", "admin-https", adminHost, 9091)
	sb.WriteString("\n")

	// Plain HTTP on either host is sent to HTTPS, which ingress-nginx did by default for a host
	// with TLS. No port is written: with a scheme and no port "the redirect port MUST be the
	// well-known port associated with the redirect scheme", 443 for https
	// (HTTPRequestRedirectFilter.Port, Gateway API v1.6.1 apis/v1/httproute_types.go). An explicit
	// 443 changes nothing on Envoy Gateway v1.9.1, which renders either as Envoy's scheme redirect
	// alone: that drops a Host's :80 and keeps any other port it names (#430).
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: HTTPRoute\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-https-redirect\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  parentRefs:\n")
	sb.WriteString("  - name: goiabada\n")
	sb.WriteString("    sectionName: http\n")
	sb.WriteString("  hostnames:\n")
	fmt.Fprintf(&sb, "  - %s\n", yamlQuote(authHost))
	fmt.Fprintf(&sb, "  - %s\n", yamlQuote(adminHost))
	sb.WriteString("  rules:\n")
	sb.WriteString("  - filters:\n")
	sb.WriteString("    - type: RequestRedirect\n")
	sb.WriteString("      requestRedirect:\n")
	sb.WriteString("        scheme: https\n")
	sb.WriteString("        statusCode: 301\n")

	return sb.String()
}

// writeTerminationGracePeriod writes a pod spec's grace period under the formula an operator who
// changes one of its terms recomputes it from, and then the lines saying what it means for this pod.
func writeTerminationGracePeriod(sb *strings.Builder, consequence ...string) {
	sb.WriteString("      # The most Kubernetes waits after deleting the pod before it kills the container: the\n")
	fmt.Fprintf(sb, "      # %ds preStop pause, plus up to 50s for the auth server to stop cleanly (15s to drain\n", preStopPauseSeconds)
	sb.WriteString("      # requests, 15s for work handed off after responses, 20s for the cleanup worker),\n")
	sb.WriteString("      # plus 10s of headroom.\n")
	for _, line := range consequence {
		fmt.Fprintf(sb, "      # %s\n", line)
	}
	fmt.Fprintf(sb, "      terminationGracePeriodSeconds: %d\n", terminationGracePeriodSeconds)
}

// writePreStopPause writes a container's preStop sleep, through Kubernetes' native sleep action
// rather than an exec of a sleep binary the image may not carry (#390 decision 2).
func writePreStopPause(sb *strings.Builder) {
	sb.WriteString("        # Keep serving for a few seconds after the pod is deleted, while the gateway learns\n")
	sb.WriteString("        # it is gone: the server closes its listener the moment it is signalled, and a\n")
	sb.WriteString("        # connection the gateway opens before then would be refused.\n")
	sb.WriteString("        lifecycle:\n")
	sb.WriteString("          preStop:\n")
	sb.WriteString("            sleep:\n")
	fmt.Fprintf(sb, "              seconds: %d\n", preStopPauseSeconds)
}

// writeHTTPSListener writes one HTTPS listener of the Gateway, terminating TLS for host with the
// certificate cert-manager keeps in the Secret certificate.
func writeHTTPSListener(sb *strings.Builder, name, host, certificate string) {
	fmt.Fprintf(sb, "  - name: %s\n", name)
	sb.WriteString("    protocol: HTTPS\n")
	sb.WriteString("    port: 443\n")
	fmt.Fprintf(sb, "    hostname: %s\n", yamlQuote(host))
	sb.WriteString("    tls:\n")
	sb.WriteString("      mode: Terminate\n")
	sb.WriteString("      certificateRefs:\n")
	fmt.Fprintf(sb, "      - name: %s\n", certificate)
}

// writeHTTPRoute writes the HTTPRoute sending host, on the Gateway's listener, to service's port.
func writeHTTPRoute(sb *strings.Builder, ns, service, listener, host string, port int) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: HTTPRoute\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(sb, "  name: %s\n", service)
	fmt.Fprintf(sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  parentRefs:\n")
	sb.WriteString("  - name: goiabada\n")
	fmt.Fprintf(sb, "    sectionName: %s\n", listener)
	sb.WriteString("  hostnames:\n")
	fmt.Fprintf(sb, "  - %s\n", yamlQuote(host))
	sb.WriteString("  rules:\n")
	sb.WriteString("  - backendRefs:\n")
	fmt.Fprintf(sb, "    - name: %s\n", service)
	fmt.Fprintf(sb, "      port: %d\n", port)
}

func base64Encode(s string) string {
	return base64.StdEncoding.EncodeToString([]byte(s))
}
