package main

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// The grace periods restate each server's shutdown budget, which this module cannot read: the wizard
// imports only core, and the budgets are the servers' own unexported constants. A test in each
// server's unit tier holds the goldens, the generator's output, to that server's budget, so raising
// a constant fails there until these follow (#390 decision 3).
const (
	// preStopPauseSeconds holds each container for this long before it is signalled, while the
	// gateway learns the pod is going; both servers close their listener on the signal (#390
	// decision 2).
	preStopPauseSeconds = 5

	// terminationGracePeriodSeconds is the pause, plus the auth server's longest clean stop (15s to
	// drain its listeners, 15s for the work handed off after responses, 20s for the cleanup worker),
	// plus 10s of headroom. One value for both Deployments, since it is a ceiling and the admin
	// console exits once its 15s drain is done (#390 decision 4).
	terminationGracePeriodSeconds = preStopPauseSeconds + 60
)

// The startup probe's budget, five minutes, is its period times the failures it allows; Compose's
// start_period for the auth server is the same five minutes (#390 decision 5).
const (
	startupProbePeriodSeconds    = 5
	startupProbeFailureThreshold = 60
)

func generateKubernetesManifests(config *Config) string {
	var sb strings.Builder

	ns := config.K8sNamespace

	sb.WriteString("# Generated by goiabada-setup\n")
	sb.WriteString("# Apply with: kubectl apply -f goiabada-k8s.yaml\n")
	sb.WriteString("#\n")
	sb.WriteString("# IMPORTANT: The database must be empty for initial deployment.\n")
	sb.WriteString("# Goiabada will seed it with OAuth clients configured for the URLs below.\n")
	sb.WriteString("# If redeploying with different URLs, use a fresh database.\n")
	sb.WriteString("\n")

	// Namespace
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Namespace\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(&sb, "  name: %s\n", yamlQuote(ns))
	sb.WriteString("  # Pod Security admission warns on apply, and writes to the audit log, for any pod in this\n")
	sb.WriteString("  # namespace that breaks the restricted standard, and refuses none. If you own the namespace\n")
	sb.WriteString("  # outright, add pod-security.kubernetes.io/enforce: restricted to refuse such pods; check\n")
	sb.WriteString("  # first that everything else running here meets it, cert-manager's HTTP-01 solver pods\n")
	sb.WriteString("  # included, which run here while a certificate is issued.\n")
	sb.WriteString("  labels:\n")
	sb.WriteString("    pod-security.kubernetes.io/warn: restricted\n")
	sb.WriteString("    pod-security.kubernetes.io/audit: restricted\n")
	sb.WriteString("\n")

	// Secret
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Secret\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-secrets\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("type: Opaque\n")
	// base64 spells any bytes in characters YAML reads as they are, so the Secret's values are
	// the one set of interpolated values not written through yamlQuote.
	sb.WriteString("data:\n")
	fmt.Fprintf(&sb, "  db-password: %s\n", base64Encode(config.DBPassword))
	fmt.Fprintf(&sb, "  admin-password: %s\n", base64Encode(config.AdminPassword))
	fmt.Fprintf(&sb, "  auth-session-auth-key: %s\n", base64Encode(config.AuthSessionAuthKey))
	fmt.Fprintf(&sb, "  auth-session-enc-key: %s\n", base64Encode(config.AuthSessionEncKey))
	fmt.Fprintf(&sb, "  admin-session-auth-key: %s\n", base64Encode(config.AdminSessionAuthKey))
	fmt.Fprintf(&sb, "  admin-session-enc-key: %s\n", base64Encode(config.AdminSessionEncKey))
	fmt.Fprintf(&sb, "  aes-encryption-key: %s\n", base64Encode(config.AESEncryptionKey))
	fmt.Fprintf(&sb, "  oauth-client-secret: %s\n", base64Encode(config.OAuthClientSecret))
	sb.WriteString("\n")

	// One ConfigMap per process, holding exactly what that process reads, so neither is handed the
	// other's settings; each server's unit tier holds its container to that (#396 decision 13).
	writeConfigMapHead(&sb, ns, "goiabada-authserver-config", "What the auth server reads.")
	writeSharedURLs(&sb, config)
	sb.WriteString("  GOIABADA_APPNAME: \"Goiabada\"\n")
	fmt.Fprintf(&sb, "  GOIABADA_ADMIN_EMAIL: %s\n", yamlQuote(config.AdminEmail))
	writeKubernetesTrust(&sb, "AUTHSERVER")
	fmt.Fprintf(&sb, "  GOIABADA_DB_TYPE: %s\n", yamlQuote(config.Engine.name))
	fmt.Fprintf(&sb, "  GOIABADA_DB_HOST: %s\n", yamlQuote(config.DBHost))
	fmt.Fprintf(&sb, "  GOIABADA_DB_PORT: %s\n", yamlQuote(config.DBPort))
	fmt.Fprintf(&sb, "  GOIABADA_DB_NAME: %s\n", yamlQuote(config.DBName))
	fmt.Fprintf(&sb, "  GOIABADA_DB_USERNAME: %s\n", yamlQuote(config.DBUsername))
	sb.WriteString("\n")

	writeConfigMapHead(&sb, ns, "goiabada-adminconsole-config", "What the admin console reads.")
	writeSharedURLs(&sb, config)
	writeKubernetesTrust(&sb, "ADMINCONSOLE")
	sb.WriteString("\n")

	// Auth Server Deployment
	writeDeploymentHead(&sb, ns, "goiabada-authserver",
		"The surge pod opens its own database connections: the docs' connection arithmetic counts it.")
	writeTerminationGracePeriod(&sb, "Set lower, it cuts the cleanup worker short first.")
	writeTopologySpread(&sb, "goiabada-authserver")
	sb.WriteString("      containers:\n")
	writeContainerHead(&sb, "authserver")
	sb.WriteString("        ports:\n")
	sb.WriteString("        - containerPort: 9090\n")
	sb.WriteString("        envFrom:\n")
	sb.WriteString("        - configMapRef:\n")
	sb.WriteString("            name: goiabada-authserver-config\n")
	sb.WriteString("        env:\n")
	sb.WriteString("        - name: GOIABADA_ADMIN_PASSWORD\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-password\n")
	sb.WriteString("        - name: GOIABADA_DB_PASSWORD\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: db-password\n")
	sb.WriteString("        - name: GOIABADA_AUTHSERVER_SESSION_AUTHENTICATION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: auth-session-auth-key\n")
	sb.WriteString("        - name: GOIABADA_AUTHSERVER_SESSION_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: auth-session-enc-key\n")
	sb.WriteString("        - name: GOIABADA_AES_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: aes-encryption-key\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: oauth-client-secret\n")
	writeProbes(&sb, 9090,
		"The auth server opens the database, runs any outstanding migrations and seeds an",
		"empty one before it listens; with several replicas, the first pod migrates and the",
		"others wait for its lock. If an upgrade's migrations take longer, raise",
		"failureThreshold until it times periodSeconds covers them, or the container is",
		"restarted mid-migration.")
	writePreStopPause(&sb)
	writeResources(&sb,
		"A sign-in costs one bcrypt check at cost 10, about 35ms of CPU on a modern core, which no",
		"limit slows on its own. At the 500m limit a pod verifies about 14 a second, and a burst",
		"queues behind that: 16 at once take about 1.2s, and every other request on the pod waits",
		"with them. Cloud cores are often slower than the one measured, and the 100m request is all",
		"the scheduler guarantees on a busy node. For a higher sign-in peak, raise the limit or add",
		"replicas.")
	sb.WriteString("\n")
	writeDisruptionBudget(&sb, ns, "goiabada-authserver")
	sb.WriteString("\n")

	// Admin Console Deployment
	writeDeploymentHead(&sb, ns, "goiabada-adminconsole",
		"This server opens no database connections, so its surge pod costs the database nothing.")
	writeTerminationGracePeriod(&sb,
		"The auth server's value: this server stops within its 15s drain, and a grace period",
		"is a ceiling, not a wait.")
	writeTopologySpread(&sb, "goiabada-adminconsole")
	sb.WriteString("      containers:\n")
	writeContainerHead(&sb, "adminconsole")
	sb.WriteString("        ports:\n")
	sb.WriteString("        - containerPort: 9091\n")
	sb.WriteString("        envFrom:\n")
	sb.WriteString("        - configMapRef:\n")
	sb.WriteString("            name: goiabada-adminconsole-config\n")
	sb.WriteString("        env:\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: oauth-client-secret\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_SESSION_AUTHENTICATION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-session-auth-key\n")
	sb.WriteString("        - name: GOIABADA_ADMINCONSOLE_SESSION_ENCRYPTION_KEY\n")
	sb.WriteString("          valueFrom:\n")
	sb.WriteString("            secretKeyRef:\n")
	sb.WriteString("              name: goiabada-secrets\n")
	sb.WriteString("              key: admin-session-enc-key\n")
	writeProbes(&sb, 9091,
		"The auth server's budget: this server starts in seconds.")
	writePreStopPause(&sb)
	writeResources(&sb,
		"The auth server's numbers. This server verifies no passwords and needs less.")
	sb.WriteString("\n")
	writeDisruptionBudget(&sb, ns, "goiabada-adminconsole")
	sb.WriteString("\n")

	// Services
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Service\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-authserver\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    app: goiabada-authserver\n")
	sb.WriteString("  ports:\n")
	sb.WriteString("  - port: 9090\n")
	sb.WriteString("    targetPort: 9090\n")
	sb.WriteString("\n")

	sb.WriteString("---\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: Service\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-adminconsole\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    app: goiabada-adminconsole\n")
	sb.WriteString("  ports:\n")
	sb.WriteString("  - port: 9091\n")
	sb.WriteString("    targetPort: 9091\n")
	sb.WriteString("\n")

	// Routing is Gateway API rather than Ingress: the one controller the Ingresses were written
	// for, ingress-nginx, is retired and gets no more security fixes, and SIG Network points its
	// users at Gateway API (kubernetes.io blog, 2025-11-11). Nothing below names an
	// implementation except gatewayClassName, which the completion message has the operator
	// create for Envoy Gateway (#430).
	authHost := hostOf(config.AuthServerURL)
	adminHost := hostOf(config.AdminConsoleURL)

	// The Gateway: plain HTTP for the redirect and for cert-manager's HTTP-01 challenges, and one
	// HTTPS listener per host. cert-manager reads the annotation and issues each listener's
	// certificateRefs for its hostname (cert-manager docs, usage/gateway.md).
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: Gateway\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("  annotations:\n")
	sb.WriteString("    cert-manager.io/cluster-issuer: \"letsencrypt-prod\"\n")
	sb.WriteString("spec:\n")
	sb.WriteString("  gatewayClassName: eg\n")
	sb.WriteString("  listeners:\n")
	sb.WriteString("  - name: http\n")
	sb.WriteString("    protocol: HTTP\n")
	sb.WriteString("    port: 80\n")
	writeHTTPSListener(&sb, "auth-https", authHost, "goiabada-tls-auth")
	writeHTTPSListener(&sb, "admin-https", adminHost, "goiabada-tls-admin")
	sb.WriteString("\n")

	writeHTTPRoute(&sb, ns, "goiabada-authserver", "auth-https", authHost, 9090)
	sb.WriteString("\n")
	writeHTTPRoute(&sb, ns, "goiabada-adminconsole", "admin-https", adminHost, 9091)
	sb.WriteString("\n")

	// Plain HTTP on either host is sent to HTTPS, which ingress-nginx did by default for a host
	// with TLS. No port is written: with a scheme and no port "the redirect port MUST be the
	// well-known port associated with the redirect scheme", 443 for https
	// (HTTPRequestRedirectFilter.Port, Gateway API v1.6.1 apis/v1/httproute_types.go). An explicit
	// 443 changes nothing on Envoy Gateway v1.9.1, which renders either as Envoy's scheme redirect
	// alone: that drops a Host's :80 and keeps any other port it names (#430).
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: HTTPRoute\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  name: goiabada-https-redirect\n")
	fmt.Fprintf(&sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  parentRefs:\n")
	sb.WriteString("  - name: goiabada\n")
	sb.WriteString("    sectionName: http\n")
	sb.WriteString("  hostnames:\n")
	fmt.Fprintf(&sb, "  - %s\n", yamlQuote(authHost))
	fmt.Fprintf(&sb, "  - %s\n", yamlQuote(adminHost))
	sb.WriteString("  rules:\n")
	sb.WriteString("  - filters:\n")
	sb.WriteString("    - type: RequestRedirect\n")
	sb.WriteString("      requestRedirect:\n")
	sb.WriteString("        scheme: https\n")
	sb.WriteString("        statusCode: 301\n")

	return sb.String()
}

// writeConfigMapHead opens the ConfigMap name, under a comment saying whose it is.
func writeConfigMapHead(sb *strings.Builder, ns, name, whose string) {
	sb.WriteString("---\n")
	fmt.Fprintf(sb, "# %s\n", whose)
	sb.WriteString("# The three URLs are in both ConfigMaps, written from the same answers; change them in both.\n")
	sb.WriteString("apiVersion: v1\n")
	sb.WriteString("kind: ConfigMap\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(sb, "  name: %s\n", name)
	fmt.Fprintf(sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("data:\n")
}

// writeSharedURLs writes the three URLs both processes read, the one place either ConfigMap takes
// them from, so the two cannot disagree.
func writeSharedURLs(sb *strings.Builder, config *Config) {
	fmt.Fprintf(sb, "  GOIABADA_AUTHSERVER_BASEURL: %s\n", yamlQuote(config.AuthServerURL))
	sb.WriteString("  GOIABADA_AUTHSERVER_INTERNALBASEURL: \"http://goiabada-authserver:9090\"\n")
	fmt.Fprintf(sb, "  GOIABADA_ADMINCONSOLE_BASEURL: %s\n", yamlQuote(config.AdminConsoleURL))
}

// writeDeploymentHead opens the Deployment name, whose pods carry the label app: name, down to its
// pod spec's first fields: its rollout, under the line saying what its surge pod costs, and the two
// things Kubernetes hands a pod unasked that neither server uses.
func writeDeploymentHead(sb *strings.Builder, ns, name, surge string) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: apps/v1\n")
	sb.WriteString("kind: Deployment\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(sb, "  name: %s\n", name)
	fmt.Fprintf(sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  replicas: 1\n")
	sb.WriteString("  # A rollout starts one new pod and waits for it to be ready before it stops an old one, so\n")
	sb.WriteString("  # it never runs fewer pods than replicas.\n")
	fmt.Fprintf(sb, "  # %s\n", surge)
	sb.WriteString("  strategy:\n")
	sb.WriteString("    type: RollingUpdate\n")
	sb.WriteString("    rollingUpdate:\n")
	sb.WriteString("      maxUnavailable: 0\n")
	sb.WriteString("      maxSurge: 1\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    matchLabels:\n")
	fmt.Fprintf(sb, "      app: %s\n", name)
	sb.WriteString("  template:\n")
	sb.WriteString("    metadata:\n")
	sb.WriteString("      labels:\n")
	fmt.Fprintf(sb, "        app: %s\n", name)
	sb.WriteString("    spec:\n")
	sb.WriteString("      # Neither server calls the Kubernetes API, so the pod mounts no service account token.\n")
	sb.WriteString("      automountServiceAccountToken: false\n")
	sb.WriteString("      # Kubernetes would otherwise give the container variables for every Service in the\n")
	sb.WriteString("      # namespace, GOIABADA_AUTHSERVER_PORT and GOIABADA_ADMINCONSOLE_SERVICE_HOST among them,\n")
	sb.WriteString("      # none of which either server reads.\n")
	sb.WriteString("      enableServiceLinks: false\n")
}

// writeTopologySpread writes a pod spec's preference for one pod of the Deployment name per node.
func writeTopologySpread(sb *strings.Builder, name string) {
	sb.WriteString("      # Spread the pods over nodes, so losing or draining one takes as few as it can. Inert at\n")
	sb.WriteString("      # one replica; with more, a pod is still scheduled when the nodes cannot be balanced.\n")
	sb.WriteString("      topologySpreadConstraints:\n")
	sb.WriteString("      - maxSkew: 1\n")
	sb.WriteString("        topologyKey: kubernetes.io/hostname\n")
	sb.WriteString("        whenUnsatisfiable: ScheduleAnyway\n")
	sb.WriteString("        labelSelector:\n")
	sb.WriteString("          matchLabels:\n")
	fmt.Fprintf(sb, "            app: %s\n", name)
}

// writeContainerHead opens the container name, running the image of the same name at the wizard's
// tag, with the pull policy that tag needs and the container's securityContext.
func writeContainerHead(sb *strings.Builder, name string) {
	fmt.Fprintf(sb, "      - name: %s\n", name)
	fmt.Fprintf(sb, "        image: leodip/goiabada:%s-%s\n", name, imageTag)
	if imageTag == "latest" {
		sb.WriteString("        # latest is a moving tag: each start pulls whatever release it names then, so pods can\n")
		sb.WriteString("        # run different releases. Replace it with a release version to pin the image.\n")
		sb.WriteString("        imagePullPolicy: Always\n")
	} else {
		sb.WriteString("        # A version tag names one build, so a node pulls it once.\n")
		sb.WriteString("        imagePullPolicy: IfNotPresent\n")
	}
	sb.WriteString("        # Everything the restricted Pod Security Standard requires, and a read-only root besides.\n")
	sb.WriteString("        # Neither server writes to its filesystem here: the legacy bootstrap file is unused under\n")
	sb.WriteString("        # Kubernetes, and the auth server's one other write, Go spilling an upload over the size\n")
	sb.WriteString("        # limit to /tmp, is refused as FILE_TOO_LARGE rather than by the image check, a 400 either\n")
	sb.WriteString("        # way. No writable mount is needed.\n")
	sb.WriteString("        securityContext:\n")
	sb.WriteString("          runAsNonRoot: true\n")
	sb.WriteString("          runAsUser: 10001\n")
	sb.WriteString("          runAsGroup: 10001\n")
	sb.WriteString("          allowPrivilegeEscalation: false\n")
	sb.WriteString("          readOnlyRootFilesystem: true\n")
	sb.WriteString("          capabilities:\n")
	sb.WriteString("            drop: [\"ALL\"]\n")
	sb.WriteString("          seccompProfile:\n")
	sb.WriteString("            type: RuntimeDefault\n")
}

// writeResources writes a container's requests and limits under the lines saying what they mean
// for it (#396 decision 12).
func writeResources(sb *strings.Builder, meaning ...string) {
	for _, line := range meaning {
		fmt.Fprintf(sb, "        # %s\n", line)
	}
	sb.WriteString("        resources:\n")
	sb.WriteString("          requests:\n")
	sb.WriteString("            memory: \"128Mi\"\n")
	sb.WriteString("            cpu: \"100m\"\n")
	sb.WriteString("          limits:\n")
	sb.WriteString("            memory: \"512Mi\"\n")
	sb.WriteString("            cpu: \"500m\"\n")
}

// writeDisruptionBudget writes the PodDisruptionBudget of the Deployment name.
func writeDisruptionBudget(sb *strings.Builder, ns, name string) {
	sb.WriteString("---\n")
	sb.WriteString("# A voluntary disruption, such as a node drain or a cluster upgrade, evicts one pod at a\n")
	sb.WriteString("# time. At one replica that pod is still evicted, and the server is down until its\n")
	sb.WriteString("# replacement is ready; at n replicas, n-1 keep serving.\n")
	sb.WriteString("apiVersion: policy/v1\n")
	sb.WriteString("kind: PodDisruptionBudget\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(sb, "  name: %s\n", name)
	fmt.Fprintf(sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  maxUnavailable: 1\n")
	sb.WriteString("  selector:\n")
	sb.WriteString("    matchLabels:\n")
	fmt.Fprintf(sb, "      app: %s\n", name)
}

// writeTerminationGracePeriod writes a pod spec's grace period under the formula an operator who
// changes one of its terms recomputes it from, and then the lines saying what it means for this pod.
func writeTerminationGracePeriod(sb *strings.Builder, consequence ...string) {
	sb.WriteString("      # The most Kubernetes waits after deleting the pod before it kills the container: the\n")
	fmt.Fprintf(sb, "      # %ds preStop pause, plus up to 50s for the auth server to stop cleanly (15s to drain\n", preStopPauseSeconds)
	sb.WriteString("      # requests, 15s for work handed off after responses, 20s for the cleanup worker),\n")
	sb.WriteString("      # plus 10s of headroom.\n")
	for _, line := range consequence {
		fmt.Fprintf(sb, "      # %s\n", line)
	}
	fmt.Fprintf(sb, "      terminationGracePeriodSeconds: %d\n", terminationGracePeriodSeconds)
}

// writeProbes writes a container's startup, liveness and readiness probes, all on its static
// /health, each stating its period, timeout and failure threshold, then the lines saying what the
// startup budget means for this container. Liveness and readiness keep the values Kubernetes applied
// before; the startup probe, rather than an initial delay, holds them off.
func writeProbes(sb *strings.Builder, port int, startupComment ...string) {
	fmt.Fprintf(sb, "        # Allows the container up to %d minutes (%d failures, %ds apart) to start listening;\n",
		startupProbePeriodSeconds*startupProbeFailureThreshold/60, startupProbeFailureThreshold, startupProbePeriodSeconds)
	sb.WriteString("        # liveness and readiness wait for it, and its first success ends it.\n")
	for _, line := range startupComment {
		fmt.Fprintf(sb, "        # %s\n", line)
	}
	writeProbe(sb, "startupProbe", port, startupProbePeriodSeconds, startupProbeFailureThreshold)
	sb.WriteString("        # /health answers 200 whenever the process is up and touches neither the database nor\n")
	sb.WriteString("        # the auth server. Keep liveness on it: a check that follows a dependency would restart\n")
	sb.WriteString("        # every pod at once when that dependency has a short outage.\n")
	writeProbe(sb, "livenessProbe", port, 10, 3)
	writeProbe(sb, "readinessProbe", port, 5, 3)
}

// writeProbe writes one probe asking for /health on port, with a one-second timeout, Kubernetes'
// default, stated so that every threshold a probe acts on is in the manifest.
func writeProbe(sb *strings.Builder, name string, port, periodSeconds, failureThreshold int) {
	fmt.Fprintf(sb, "        %s:\n", name)
	sb.WriteString("          httpGet:\n")
	sb.WriteString("            path: /health\n")
	fmt.Fprintf(sb, "            port: %d\n", port)
	fmt.Fprintf(sb, "          periodSeconds: %d\n", periodSeconds)
	sb.WriteString("          timeoutSeconds: 1\n")
	fmt.Fprintf(sb, "          failureThreshold: %d\n", failureThreshold)
}

// writePreStopPause writes a container's preStop sleep, through Kubernetes' native sleep action
// rather than an exec of a sleep binary the image may not carry (#390 decision 2).
func writePreStopPause(sb *strings.Builder) {
	sb.WriteString("        # Keep serving for a few seconds after the pod is deleted, while the gateway learns\n")
	sb.WriteString("        # it is gone: the server closes its listener the moment it is signalled, and a\n")
	sb.WriteString("        # connection the gateway opens before then would be refused.\n")
	sb.WriteString("        lifecycle:\n")
	sb.WriteString("          preStop:\n")
	sb.WriteString("            sleep:\n")
	fmt.Fprintf(sb, "              seconds: %d\n", preStopPauseSeconds)
}

// writeHTTPSListener writes one HTTPS listener of the Gateway, terminating TLS for host with the
// certificate cert-manager keeps in the Secret certificate.
func writeHTTPSListener(sb *strings.Builder, name, host, certificate string) {
	fmt.Fprintf(sb, "  - name: %s\n", name)
	sb.WriteString("    protocol: HTTPS\n")
	sb.WriteString("    port: 443\n")
	fmt.Fprintf(sb, "    hostname: %s\n", yamlQuote(host))
	sb.WriteString("    tls:\n")
	sb.WriteString("      mode: Terminate\n")
	sb.WriteString("      certificateRefs:\n")
	fmt.Fprintf(sb, "      - name: %s\n", certificate)
}

// writeHTTPRoute writes the HTTPRoute sending host, on the Gateway's listener, to service's port.
func writeHTTPRoute(sb *strings.Builder, ns, service, listener, host string, port int) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: gateway.networking.k8s.io/v1\n")
	sb.WriteString("kind: HTTPRoute\n")
	sb.WriteString("metadata:\n")
	fmt.Fprintf(sb, "  name: %s\n", service)
	fmt.Fprintf(sb, "  namespace: %s\n", yamlQuote(ns))
	sb.WriteString("spec:\n")
	sb.WriteString("  parentRefs:\n")
	sb.WriteString("  - name: goiabada\n")
	fmt.Fprintf(sb, "    sectionName: %s\n", listener)
	sb.WriteString("  hostnames:\n")
	fmt.Fprintf(sb, "  - %s\n", yamlQuote(host))
	sb.WriteString("  rules:\n")
	sb.WriteString("  - backendRefs:\n")
	fmt.Fprintf(sb, "    - name: %s\n", service)
	fmt.Fprintf(sb, "      port: %d\n", port)
}

// writeKubernetesTrust writes one ConfigMap's proxy trust: one hop, with the list beside it set
// empty, under the comment saying why. Envoy appends the address it received each connection from,
// so the rightmost X-Forwarded-For entry is Envoy's own observation; a private-range or pod-CIDR
// list would instead adopt a forged entry wherever nodes or pods share those addresses, and no list
// stops a pod calling the Service around Envoy (#396 decision 3). server is the variables' infix,
// AUTHSERVER or ADMINCONSOLE.
func writeKubernetesTrust(sb *strings.Builder, server string) {
	sb.WriteString("  # Envoy, the one gateway in front, appends the address it received each connection from\n")
	sb.WriteString("  # to X-Forwarded-For, so trusting one hop, the rightmost entry, needs no list. Set the list\n")
	sb.WriteString("  # only when a CDN or a second load balancer sits in front of Envoy, naming every hop, the\n")
	sb.WriteString("  # Envoy pods included. A pod that calls the Service directly, around Envoy, chooses the\n")
	sb.WriteString("  # address it is counted and audited under: a NetworkPolicy admitting only Envoy stops\n")
	sb.WriteString("  # that, and no list does.\n")
	fmt.Fprintf(sb, "  GOIABADA_%s_TRUST_PROXY_HEADERS: \"true\"\n", server)
	fmt.Fprintf(sb, "  GOIABADA_%s_TRUSTED_PROXIES: \"\"\n", server)
}

func base64Encode(s string) string {
	return base64.StdEncoding.EncodeToString([]byte(s))
}
