package main

import (
	"os"
	"strings"
	"testing"
)

// The two variables the admin console stopped reading. The client id is the compile-time
// constant `admin-console-client` and the issuer comes from the auth server's public
// settings, so a deployment artifact that sets either is asking an operator for a value
// they cannot choose, and the admin console now refuses to start when the issuer one is
// present at all (#285).
//
// These generators are pure and their output is what an operator pastes into a server, so
// a reintroduced line here ships silently: nothing else in the repository reads what they
// produce. Before this file the module had no tests at all, and `go test ./...` reported
// `[no test files]` with the removed lines restored.
var removedAdminConsoleVars = []string{
	"GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_ID",
	"GOIABADA_ADMINCONSOLE_ISSUER",
}

// testConfig is a fully populated wizard answer set. Every field carries a distinguishable
// value so a generator that emitted the wrong one would still be visible in a failure.
func testConfig() *Config {
	return &Config{
		DeploymentType:      "2",
		DBType:              "postgres",
		DBImage:             "postgres:17",
		DBPort:              "5432",
		DBHost:              "goiabada-db",
		DBName:              "goiabada",
		DBUsername:          "goiabada-user",
		DBPassword:          "db-password",
		AuthServerURL:       "https://auth.example.com",
		AdminConsoleURL:     "https://admin.example.com",
		AdminEmail:          "admin@example.com",
		AdminPassword:       "admin-password",
		AuthSessionAuthKey:  "auth-session-auth-key",
		AuthSessionEncKey:   "auth-session-enc-key",
		AdminSessionAuthKey: "admin-session-auth-key",
		AdminSessionEncKey:  "admin-session-enc-key",
		AESEncryptionKey:    "aes-encryption-key",
		OAuthClientSecret:   "oauth-client-secret",
		K8sNamespace:        "goiabada",
	}
}

func TestGeneratedOutputsOmitTheRemovedAdminConsoleVars(t *testing.T) {
	config := testConfig()

	// Each case names a line the generator must still emit. Absence alone would pass
	// against a generator that returned nothing, which is the way this test could go
	// quietly false as the wizard changes.
	testCases := []struct {
		name         string
		generated    string
		stillEmitted string
	}{
		{
			name:         "admin console compose service",
			generated:    generateAdminConsoleService(config),
			stillEmitted: "GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET=oauth-client-secret",
		},
		{
			name:         "whole compose file",
			generated:    generateDockerCompose(config),
			stillEmitted: "goiabada-adminconsole:",
		},
		{
			name:         "env file for native binaries",
			generated:    generateEnvFile(config),
			stillEmitted: `export GOIABADA_ADMINCONSOLE_OAUTH_CLIENT_SECRET="oauth-client-secret"`,
		},
		{
			name:         "kubernetes manifests",
			generated:    generateKubernetesManifests(config),
			stillEmitted: "GOIABADA_ADMINCONSOLE_BASEURL: \"https://admin.example.com\"",
		},
	}

	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			for _, removed := range removedAdminConsoleVars {
				if strings.Contains(testCase.generated, removed) {
					t.Errorf("output sets %s, which the admin console no longer reads", removed)
				}
			}
			if !strings.Contains(testCase.generated, testCase.stillEmitted) {
				t.Errorf("output does not contain %q, so the absence checks above proved nothing",
					testCase.stillEmitted)
			}
		})
	}
}

// The two files beside main.go are outputs of a wizard run, committed into the source
// directory and kept in step with the generators by hand. Nothing regenerates them, so
// they drift on their own schedule.
func TestCommittedOutputsOmitTheRemovedAdminConsoleVars(t *testing.T) {
	for _, name := range []string{"docker-compose.yml", "goiabada-k8s.yaml"} {
		t.Run(name, func(t *testing.T) {
			contents, err := os.ReadFile(name)
			if err != nil {
				t.Fatalf("reading %s: %v", name, err)
			}
			for _, removed := range removedAdminConsoleVars {
				if strings.Contains(string(contents), removed) {
					t.Errorf("%s sets %s, which the admin console no longer reads", name, removed)
				}
			}
			if !strings.Contains(string(contents), "# Generated by goiabada-setup") {
				t.Errorf("%s lost its generated-by banner, so this file is no longer the wizard's output", name)
			}
		})
	}
}
