on:  
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run tests (sqlite)
        id: run-tests-sqlite
        continue-on-error: true
        run: |
          cd authserver/src        
          pwd
          ls -la
          docker images
          docker ps -a
          docker compose -f ../docker/docker-compose-test.yml down --remove-orphans --volumes          
          docker compose -f ../docker/docker-compose-test.yml run goiabada-test-sqlite
          docker compose -f ../docker/docker-compose-test.yml down --remove-orphans --volumes
          docker ps -a
      
      - name: Run tests (mysql)
        id: run-tests-mysql
        continue-on-error: true
        run: |
          cd authserver/src        
          pwd
          ls -la
          docker images
          docker ps -a
          docker compose -f ../docker/docker-compose-test.yml down --remove-orphans --volumes          
          docker compose -f ../docker/docker-compose-test.yml run goiabada-test-mysql
          docker compose -f ../docker/docker-compose-test.yml down --remove-orphans --volumes
          docker ps -a
