package communication

import (
	"encoding/base64"
	"net/smtp"

	"github.com/leodip/goiabada/core/errs"
)

// RFC 5321 section 4.5.3.1.4: "The maximum total length of a command line including the command
// word and the <CRLF> is 512 octets."
const smtpCommandLineLimit = 512

// plainResponse is RFC 4616's message: an empty authzid, then the authcid and the password, NUL
// separated. net/smtp base64 encodes whatever an Auth hands it, so this is the raw form.
func plainResponse(username, password string) []byte {
	return []byte("\x00" + username + "\x00" + password)
}

// plainInitialResponseFits reports whether the credentials still fit on the AUTH command line.
// smtp.PlainAuth always writes them there, as `AUTH PLAIN <base64>`, and RFC 4954 section 4 says
// that "if use of the initial response argument would cause the AUTH command to exceed this
// length, the client MUST NOT use the initial response parameter". Nothing bounds the SMTP
// password on the way into the settings -- apihandlers.HandleAPISettingsEmailPut bounds the host,
// username, from-name and from-address and not the password -- so a password an admin can save
// today is enough to overrun the line against a server that enforces it (#274).
func plainInitialResponseFits(username, password string) bool {
	encoded := base64.StdEncoding.EncodedLen(len(plainResponse(username, password)))
	return len("AUTH PLAIN ")+encoded+len("\r\n") <= smtpCommandLineLimit
}

// plainAuth is PLAIN without an initial response: the bare `AUTH PLAIN`, then the credentials on a
// line of their own after the server's empty 334 challenge. It is used only where the inline form
// would not fit, because that costs a round trip the ordinary send has no reason to pay.
//
// The continuation line carries no such limit: RFC 4954 section 4 requires both ends to "handle
// the maximum encoded size of challenges and responses generated by their supported authentication
// mechanisms", and says that "this requirement is independent of any line length limitations the
// client or server may have in other parts of its protocol implementation".
//
// There is no TLS check in this type, for the same reason loginAuth has none: SendEmail gates PLAIN
// and LOGIN on the connection being TLS or the host being loopback before it issues any AUTH
// command, so the refusal names the encryption setting to change (#274).
type plainAuth struct {
	username string
	password string
	// answered records that the credentials have gone out, so a second challenge is an error
	// rather than a second copy of the password.
	answered bool
}

func (a *plainAuth) Start(_ *smtp.ServerInfo) (string, []byte, error) {
	// A nil initial response is what makes net/smtp send `AUTH PLAIN` with nothing after it, which
	// is the form that asks the server for the empty challenge.
	return "PLAIN", nil, nil
}

func (a *plainAuth) Next(_ []byte, more bool) ([]byte, error) {
	if !more {
		return nil, nil
	}
	if a.answered {
		return nil, errs.New("unexpected server challenge")
	}
	a.answered = true
	return plainResponse(a.username, a.password), nil
}
