package constants

const SystemClientIdentifier = "system-website"

const AuthServerResourceIdentifier = "authserver"

const UserinfoPermissionIdentifier = "userinfo"
const ManageAccountPermissionIdentifier = "manage-account"
const AdminWebsitePermissionIdentifier = "admin-website"

const AuditAuthFailedPwd = "auth_failed_pwd"
const AuditAuthFailedOtp = "auth_failed_otp"
const AuditAuthSuccessPwd = "auth_success_pwd"
const AuditAuthSuccessOtp = "auth_success_otp"
const AuditUserDisabled = "user_disabled"
const AuditStartedNewUserSesson = "started_new_user_session"
const AuditBumpedUserSession = "bumped_user_session"
const AuditCreatedAuthCode = "created_auth_code"
const AuditRotatedKeys = "rotated_keys"
const AuditRevokedKey = "revoked_key"
const AuditDeletedUserSession = "deleted_user_session"
const AuditSavedConsent = "saved_consent"
const AuditCreatedPreRegistration = "created_pre_registration"
const AuditCreatedUser = "created_user"
const AuditActivatedAccount = "activated_account"
const AuditUpdatedRedirectURIs = "updated_redirect_uris"
const AuditUpdatedClientPermissions = "updated_client_permissions"
const AuditDeletedClient = "deleted_client"
const AuditCreatedClient = "created_client"
const AuditUpdatedResourcePermissions = "updated_resource_permissions"
